
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.js"
import * as $Class from "./internal/class.js"
import * as Prisma from "./internal/prismaNamespace.js"

export * as $Enums from './enums.js'
export * from "./enums.js"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient({
 *   adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL })
 * })
 * // Fetch zero or more RevoProjects
 * const revoProjects = await prisma.revoProject.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model RevoProject
 * 
 */
export type RevoProject = Prisma.RevoProjectModel
/**
 * Model RevoRepository
 * 
 */
export type RevoRepository = Prisma.RevoRepositoryModel
/**
 * Model TaskRun
 * 
 */
export type TaskRun = Prisma.TaskRunModel
/**
 * Model RunTask
 * 
 */
export type RunTask = Prisma.RunTaskModel
/**
 * Model RunEvent
 * 
 */
export type RunEvent = Prisma.RunEventModel
/**
 * Model RunAttempt
 * 
 */
export type RunAttempt = Prisma.RunAttemptModel
/**
 * Model InboxItem
 * 
 */
export type InboxItem = Prisma.InboxItemModel
/**
 * Model RunOutput
 * 
 */
export type RunOutput = Prisma.RunOutputModel
/**
 * Model CostLedgerEntry
 * 
 */
export type CostLedgerEntry = Prisma.CostLedgerEntryModel
/**
 * Model Branch
 * 
 */
export type Branch = Prisma.BranchModel
/**
 * Model Revision
 * 
 */
export type Revision = Prisma.RevisionModel
/**
 * Model Table
 * 
 */
export type Table = Prisma.TableModel
/**
 * Model Row
 * 
 */
export type Row = Prisma.RowModel
/**
 * Model FileBlob
 * 
 */
export type FileBlob = Prisma.FileBlobModel
/**
 * Model ProjectFileUsage
 * 
 */
export type ProjectFileUsage = Prisma.ProjectFileUsageModel
/**
 * Model TableMigration
 * 
 */
export type TableMigration = Prisma.TableMigrationModel
