
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const RevoProjectKind = {
  USER: 'USER',
  SYSTEM: 'SYSTEM'
} as const

export type RevoProjectKind = (typeof RevoProjectKind)[keyof typeof RevoProjectKind]


export const RevoProjectStatus = {
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
  DELETED: 'DELETED'
} as const

export type RevoProjectStatus = (typeof RevoProjectStatus)[keyof typeof RevoProjectStatus]
