
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  RevoProject: 'RevoProject',
  TaskRun: 'TaskRun',
  RunTask: 'RunTask',
  RunEvent: 'RunEvent',
  RunAttempt: 'RunAttempt',
  InboxItem: 'InboxItem',
  RunOutput: 'RunOutput',
  CostLedgerEntry: 'CostLedgerEntry',
  Branch: 'Branch',
  Revision: 'Revision',
  Table: 'Table',
  Row: 'Row',
  FileBlob: 'FileBlob',
  ProjectFileUsage: 'ProjectFileUsage',
  TableMigration: 'TableMigration'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const RevoProjectScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  kind: 'kind',
  name: 'name',
  slug: 'slug',
  status: 'status'
} as const

export type RevoProjectScalarFieldEnum = (typeof RevoProjectScalarFieldEnum)[keyof typeof RevoProjectScalarFieldEnum]


export const TaskRunScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  projectId: 'projectId',
  title: 'title',
  description: 'description',
  status: 'status',
  repos: 'repos',
  scope: 'scope',
  priority: 'priority',
  playbookId: 'playbookId',
  pipelineId: 'pipelineId',
  params: 'params',
  routeDecision: 'routeDecision',
  createdBy: 'createdBy'
} as const

export type TaskRunScalarFieldEnum = (typeof TaskRunScalarFieldEnum)[keyof typeof TaskRunScalarFieldEnum]


export const RunTaskScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  runId: 'runId',
  repoRef: 'repoRef',
  roleHint: 'roleHint',
  title: 'title',
  status: 'status',
  dependsOn: 'dependsOn',
  scope: 'scope',
  priority: 'priority'
} as const

export type RunTaskScalarFieldEnum = (typeof RunTaskScalarFieldEnum)[keyof typeof RunTaskScalarFieldEnum]


export const RunEventScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  sequence: 'sequence',
  runId: 'runId',
  taskId: 'taskId',
  stepId: 'stepId',
  type: 'type',
  payload: 'payload',
  actor: 'actor'
} as const

export type RunEventScalarFieldEnum = (typeof RunEventScalarFieldEnum)[keyof typeof RunEventScalarFieldEnum]


export const RunAttemptScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  runId: 'runId',
  stepId: 'stepId',
  workerId: 'workerId',
  attemptNo: 'attemptNo',
  iteration: 'iteration',
  status: 'status',
  idempotencyKey: 'idempotencyKey',
  modelProfile: 'modelProfile',
  verdict: 'verdict',
  inputTokens: 'inputTokens',
  outputTokens: 'outputTokens',
  costAmount: 'costAmount',
  currency: 'currency',
  durationMs: 'durationMs',
  outputSummary: 'outputSummary',
  artifactRef: 'artifactRef',
  stdoutTail: 'stdoutTail',
  stderrTail: 'stderrTail',
  lesson: 'lesson',
  error: 'error',
  startedAt: 'startedAt',
  finishedAt: 'finishedAt'
} as const

export type RunAttemptScalarFieldEnum = (typeof RunAttemptScalarFieldEnum)[keyof typeof RunAttemptScalarFieldEnum]


export const InboxItemScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  kind: 'kind',
  runId: 'runId',
  taskId: 'taskId',
  stepId: 'stepId',
  projectId: 'projectId',
  title: 'title',
  context: 'context',
  options: 'options',
  status: 'status',
  answer: 'answer',
  resolvedBy: 'resolvedBy',
  resolvedAt: 'resolvedAt'
} as const

export type InboxItemScalarFieldEnum = (typeof InboxItemScalarFieldEnum)[keyof typeof InboxItemScalarFieldEnum]


export const RunOutputScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  runId: 'runId',
  nodeId: 'nodeId',
  ordinal: 'ordinal',
  name: 'name',
  schemaRef: 'schemaRef',
  payload: 'payload',
  payloadRef: 'payloadRef',
  attemptId: 'attemptId',
  producedAt: 'producedAt'
} as const

export type RunOutputScalarFieldEnum = (typeof RunOutputScalarFieldEnum)[keyof typeof RunOutputScalarFieldEnum]


export const CostLedgerEntryScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  runId: 'runId',
  stepId: 'stepId',
  attemptId: 'attemptId',
  modelProfile: 'modelProfile',
  inputTokens: 'inputTokens',
  outputTokens: 'outputTokens',
  costAmount: 'costAmount',
  currency: 'currency',
  recordedAt: 'recordedAt'
} as const

export type CostLedgerEntryScalarFieldEnum = (typeof CostLedgerEntryScalarFieldEnum)[keyof typeof CostLedgerEntryScalarFieldEnum]


export const BranchScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  isRoot: 'isRoot',
  name: 'name',
  projectId: 'projectId'
} as const

export type BranchScalarFieldEnum = (typeof BranchScalarFieldEnum)[keyof typeof BranchScalarFieldEnum]


export const RevisionScalarFieldEnum = {
  id: 'id',
  sequence: 'sequence',
  createdAt: 'createdAt',
  comment: 'comment',
  isHead: 'isHead',
  isDraft: 'isDraft',
  isStart: 'isStart',
  hasChanges: 'hasChanges',
  branchId: 'branchId',
  parentId: 'parentId'
} as const

export type RevisionScalarFieldEnum = (typeof RevisionScalarFieldEnum)[keyof typeof RevisionScalarFieldEnum]


export const TableScalarFieldEnum = {
  versionId: 'versionId',
  createdId: 'createdId',
  id: 'id',
  readonly: 'readonly',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  system: 'system'
} as const

export type TableScalarFieldEnum = (typeof TableScalarFieldEnum)[keyof typeof TableScalarFieldEnum]


export const RowScalarFieldEnum = {
  versionId: 'versionId',
  createdId: 'createdId',
  id: 'id',
  readonly: 'readonly',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  publishedAt: 'publishedAt',
  data: 'data',
  meta: 'meta',
  hash: 'hash',
  schemaHash: 'schemaHash'
} as const

export type RowScalarFieldEnum = (typeof RowScalarFieldEnum)[keyof typeof RowScalarFieldEnum]


export const FileBlobScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  deletedAt: 'deletedAt',
  projectId: 'projectId',
  hash: 'hash',
  size: 'size'
} as const

export type FileBlobScalarFieldEnum = (typeof FileBlobScalarFieldEnum)[keyof typeof FileBlobScalarFieldEnum]


export const ProjectFileUsageScalarFieldEnum = {
  projectId: 'projectId',
  fileBytes: 'fileBytes',
  updatedAt: 'updatedAt'
} as const

export type ProjectFileUsageScalarFieldEnum = (typeof ProjectFileUsageScalarFieldEnum)[keyof typeof ProjectFileUsageScalarFieldEnum]


export const TableMigrationScalarFieldEnum = {
  id: 'id',
  revisionId: 'revisionId',
  tableId: 'tableId',
  sourceTableVersionId: 'sourceTableVersionId',
  shadowTableVersionId: 'shadowTableVersionId',
  status: 'status',
  phase: 'phase',
  patches: 'patches',
  previousSchema: 'previousSchema',
  previousSchemaHash: 'previousSchemaHash',
  targetSchemaHash: 'targetSchemaHash',
  totalRows: 'totalRows',
  copiedRows: 'copiedRows',
  lastCopiedRowId: 'lastCopiedRowId',
  batchSize: 'batchSize',
  currentBatch: 'currentBatch',
  totalBatches: 'totalBatches',
  createdAt: 'createdAt',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  lastProgressAt: 'lastProgressAt',
  lockedBy: 'lockedBy',
  lockedAt: 'lockedAt',
  heartbeatAt: 'heartbeatAt',
  errorMessage: 'errorMessage',
  retryCount: 'retryCount',
  maxRetries: 'maxRetries'
} as const

export type TableMigrationScalarFieldEnum = (typeof TableMigrationScalarFieldEnum)[keyof typeof TableMigrationScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const RevoProjectOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug'
} as const

export type RevoProjectOrderByRelevanceFieldEnum = (typeof RevoProjectOrderByRelevanceFieldEnum)[keyof typeof RevoProjectOrderByRelevanceFieldEnum]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const TaskRunOrderByRelevanceFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  title: 'title',
  description: 'description',
  status: 'status',
  repos: 'repos',
  scope: 'scope',
  playbookId: 'playbookId',
  pipelineId: 'pipelineId',
  createdBy: 'createdBy'
} as const

export type TaskRunOrderByRelevanceFieldEnum = (typeof TaskRunOrderByRelevanceFieldEnum)[keyof typeof TaskRunOrderByRelevanceFieldEnum]


export const RunTaskOrderByRelevanceFieldEnum = {
  id: 'id',
  runId: 'runId',
  repoRef: 'repoRef',
  roleHint: 'roleHint',
  title: 'title',
  status: 'status',
  dependsOn: 'dependsOn',
  scope: 'scope'
} as const

export type RunTaskOrderByRelevanceFieldEnum = (typeof RunTaskOrderByRelevanceFieldEnum)[keyof typeof RunTaskOrderByRelevanceFieldEnum]


export const RunEventOrderByRelevanceFieldEnum = {
  id: 'id',
  runId: 'runId',
  taskId: 'taskId',
  stepId: 'stepId',
  type: 'type',
  actor: 'actor'
} as const

export type RunEventOrderByRelevanceFieldEnum = (typeof RunEventOrderByRelevanceFieldEnum)[keyof typeof RunEventOrderByRelevanceFieldEnum]


export const RunAttemptOrderByRelevanceFieldEnum = {
  id: 'id',
  runId: 'runId',
  stepId: 'stepId',
  workerId: 'workerId',
  status: 'status',
  idempotencyKey: 'idempotencyKey',
  modelProfile: 'modelProfile',
  verdict: 'verdict',
  currency: 'currency',
  outputSummary: 'outputSummary',
  artifactRef: 'artifactRef',
  stdoutTail: 'stdoutTail',
  stderrTail: 'stderrTail',
  lesson: 'lesson',
  error: 'error'
} as const

export type RunAttemptOrderByRelevanceFieldEnum = (typeof RunAttemptOrderByRelevanceFieldEnum)[keyof typeof RunAttemptOrderByRelevanceFieldEnum]


export const InboxItemOrderByRelevanceFieldEnum = {
  id: 'id',
  kind: 'kind',
  runId: 'runId',
  taskId: 'taskId',
  stepId: 'stepId',
  projectId: 'projectId',
  title: 'title',
  options: 'options',
  status: 'status',
  resolvedBy: 'resolvedBy'
} as const

export type InboxItemOrderByRelevanceFieldEnum = (typeof InboxItemOrderByRelevanceFieldEnum)[keyof typeof InboxItemOrderByRelevanceFieldEnum]


export const RunOutputOrderByRelevanceFieldEnum = {
  id: 'id',
  runId: 'runId',
  nodeId: 'nodeId',
  name: 'name',
  schemaRef: 'schemaRef',
  payloadRef: 'payloadRef',
  attemptId: 'attemptId'
} as const

export type RunOutputOrderByRelevanceFieldEnum = (typeof RunOutputOrderByRelevanceFieldEnum)[keyof typeof RunOutputOrderByRelevanceFieldEnum]


export const CostLedgerEntryOrderByRelevanceFieldEnum = {
  id: 'id',
  runId: 'runId',
  stepId: 'stepId',
  attemptId: 'attemptId',
  modelProfile: 'modelProfile',
  currency: 'currency'
} as const

export type CostLedgerEntryOrderByRelevanceFieldEnum = (typeof CostLedgerEntryOrderByRelevanceFieldEnum)[keyof typeof CostLedgerEntryOrderByRelevanceFieldEnum]


export const BranchOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  projectId: 'projectId'
} as const

export type BranchOrderByRelevanceFieldEnum = (typeof BranchOrderByRelevanceFieldEnum)[keyof typeof BranchOrderByRelevanceFieldEnum]


export const RevisionOrderByRelevanceFieldEnum = {
  id: 'id',
  comment: 'comment',
  branchId: 'branchId',
  parentId: 'parentId'
} as const

export type RevisionOrderByRelevanceFieldEnum = (typeof RevisionOrderByRelevanceFieldEnum)[keyof typeof RevisionOrderByRelevanceFieldEnum]


export const TableOrderByRelevanceFieldEnum = {
  versionId: 'versionId',
  createdId: 'createdId',
  id: 'id'
} as const

export type TableOrderByRelevanceFieldEnum = (typeof TableOrderByRelevanceFieldEnum)[keyof typeof TableOrderByRelevanceFieldEnum]


export const RowOrderByRelevanceFieldEnum = {
  versionId: 'versionId',
  createdId: 'createdId',
  id: 'id',
  hash: 'hash',
  schemaHash: 'schemaHash'
} as const

export type RowOrderByRelevanceFieldEnum = (typeof RowOrderByRelevanceFieldEnum)[keyof typeof RowOrderByRelevanceFieldEnum]


export const FileBlobOrderByRelevanceFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  hash: 'hash'
} as const

export type FileBlobOrderByRelevanceFieldEnum = (typeof FileBlobOrderByRelevanceFieldEnum)[keyof typeof FileBlobOrderByRelevanceFieldEnum]


export const ProjectFileUsageOrderByRelevanceFieldEnum = {
  projectId: 'projectId'
} as const

export type ProjectFileUsageOrderByRelevanceFieldEnum = (typeof ProjectFileUsageOrderByRelevanceFieldEnum)[keyof typeof ProjectFileUsageOrderByRelevanceFieldEnum]


export const TableMigrationOrderByRelevanceFieldEnum = {
  id: 'id',
  revisionId: 'revisionId',
  tableId: 'tableId',
  sourceTableVersionId: 'sourceTableVersionId',
  shadowTableVersionId: 'shadowTableVersionId',
  status: 'status',
  phase: 'phase',
  previousSchemaHash: 'previousSchemaHash',
  targetSchemaHash: 'targetSchemaHash',
  lastCopiedRowId: 'lastCopiedRowId',
  lockedBy: 'lockedBy',
  errorMessage: 'errorMessage'
} as const

export type TableMigrationOrderByRelevanceFieldEnum = (typeof TableMigrationOrderByRelevanceFieldEnum)[keyof typeof TableMigrationOrderByRelevanceFieldEnum]

