
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CostLedgerEntry` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model CostLedgerEntry
 * 
 */
export type CostLedgerEntryModel = runtime.Types.Result.DefaultSelection<Prisma.$CostLedgerEntryPayload>

export type AggregateCostLedgerEntry = {
  _count: CostLedgerEntryCountAggregateOutputType | null
  _avg: CostLedgerEntryAvgAggregateOutputType | null
  _sum: CostLedgerEntrySumAggregateOutputType | null
  _min: CostLedgerEntryMinAggregateOutputType | null
  _max: CostLedgerEntryMaxAggregateOutputType | null
}

export type CostLedgerEntryAvgAggregateOutputType = {
  inputTokens: number | null
  outputTokens: number | null
  costAmount: runtime.Decimal | null
}

export type CostLedgerEntrySumAggregateOutputType = {
  inputTokens: number | null
  outputTokens: number | null
  costAmount: runtime.Decimal | null
}

export type CostLedgerEntryMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  runId: string | null
  stepId: string | null
  attemptId: string | null
  modelProfile: string | null
  inputTokens: number | null
  outputTokens: number | null
  costAmount: runtime.Decimal | null
  currency: string | null
  recordedAt: Date | null
}

export type CostLedgerEntryMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  runId: string | null
  stepId: string | null
  attemptId: string | null
  modelProfile: string | null
  inputTokens: number | null
  outputTokens: number | null
  costAmount: runtime.Decimal | null
  currency: string | null
  recordedAt: Date | null
}

export type CostLedgerEntryCountAggregateOutputType = {
  id: number
  createdAt: number
  runId: number
  stepId: number
  attemptId: number
  modelProfile: number
  inputTokens: number
  outputTokens: number
  costAmount: number
  currency: number
  recordedAt: number
  _all: number
}


export type CostLedgerEntryAvgAggregateInputType = {
  inputTokens?: true
  outputTokens?: true
  costAmount?: true
}

export type CostLedgerEntrySumAggregateInputType = {
  inputTokens?: true
  outputTokens?: true
  costAmount?: true
}

export type CostLedgerEntryMinAggregateInputType = {
  id?: true
  createdAt?: true
  runId?: true
  stepId?: true
  attemptId?: true
  modelProfile?: true
  inputTokens?: true
  outputTokens?: true
  costAmount?: true
  currency?: true
  recordedAt?: true
}

export type CostLedgerEntryMaxAggregateInputType = {
  id?: true
  createdAt?: true
  runId?: true
  stepId?: true
  attemptId?: true
  modelProfile?: true
  inputTokens?: true
  outputTokens?: true
  costAmount?: true
  currency?: true
  recordedAt?: true
}

export type CostLedgerEntryCountAggregateInputType = {
  id?: true
  createdAt?: true
  runId?: true
  stepId?: true
  attemptId?: true
  modelProfile?: true
  inputTokens?: true
  outputTokens?: true
  costAmount?: true
  currency?: true
  recordedAt?: true
  _all?: true
}

export type CostLedgerEntryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CostLedgerEntry to aggregate.
   */
  where?: Prisma.CostLedgerEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CostLedgerEntries to fetch.
   */
  orderBy?: Prisma.CostLedgerEntryOrderByWithRelationInput | Prisma.CostLedgerEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CostLedgerEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CostLedgerEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CostLedgerEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CostLedgerEntries
  **/
  _count?: true | CostLedgerEntryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CostLedgerEntryAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CostLedgerEntrySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CostLedgerEntryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CostLedgerEntryMaxAggregateInputType
}

export type GetCostLedgerEntryAggregateType<T extends CostLedgerEntryAggregateArgs> = {
      [P in keyof T & keyof AggregateCostLedgerEntry]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCostLedgerEntry[P]>
    : Prisma.GetScalarType<T[P], AggregateCostLedgerEntry[P]>
}




export type CostLedgerEntryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CostLedgerEntryWhereInput
  orderBy?: Prisma.CostLedgerEntryOrderByWithAggregationInput | Prisma.CostLedgerEntryOrderByWithAggregationInput[]
  by: Prisma.CostLedgerEntryScalarFieldEnum[] | Prisma.CostLedgerEntryScalarFieldEnum
  having?: Prisma.CostLedgerEntryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CostLedgerEntryCountAggregateInputType | true
  _avg?: CostLedgerEntryAvgAggregateInputType
  _sum?: CostLedgerEntrySumAggregateInputType
  _min?: CostLedgerEntryMinAggregateInputType
  _max?: CostLedgerEntryMaxAggregateInputType
}

export type CostLedgerEntryGroupByOutputType = {
  id: string
  createdAt: Date
  runId: string
  stepId: string
  attemptId: string
  modelProfile: string
  inputTokens: number
  outputTokens: number
  costAmount: runtime.Decimal
  currency: string
  recordedAt: Date
  _count: CostLedgerEntryCountAggregateOutputType | null
  _avg: CostLedgerEntryAvgAggregateOutputType | null
  _sum: CostLedgerEntrySumAggregateOutputType | null
  _min: CostLedgerEntryMinAggregateOutputType | null
  _max: CostLedgerEntryMaxAggregateOutputType | null
}

export type GetCostLedgerEntryGroupByPayload<T extends CostLedgerEntryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CostLedgerEntryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CostLedgerEntryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CostLedgerEntryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CostLedgerEntryGroupByOutputType[P]>
      }
    >
  >



export type CostLedgerEntryWhereInput = {
  AND?: Prisma.CostLedgerEntryWhereInput | Prisma.CostLedgerEntryWhereInput[]
  OR?: Prisma.CostLedgerEntryWhereInput[]
  NOT?: Prisma.CostLedgerEntryWhereInput | Prisma.CostLedgerEntryWhereInput[]
  id?: Prisma.StringFilter<"CostLedgerEntry"> | string
  createdAt?: Prisma.DateTimeFilter<"CostLedgerEntry"> | Date | string
  runId?: Prisma.StringFilter<"CostLedgerEntry"> | string
  stepId?: Prisma.StringFilter<"CostLedgerEntry"> | string
  attemptId?: Prisma.StringFilter<"CostLedgerEntry"> | string
  modelProfile?: Prisma.StringFilter<"CostLedgerEntry"> | string
  inputTokens?: Prisma.IntFilter<"CostLedgerEntry"> | number
  outputTokens?: Prisma.IntFilter<"CostLedgerEntry"> | number
  costAmount?: Prisma.DecimalFilter<"CostLedgerEntry"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFilter<"CostLedgerEntry"> | string
  recordedAt?: Prisma.DateTimeFilter<"CostLedgerEntry"> | Date | string
  run?: Prisma.XOR<Prisma.TaskRunScalarRelationFilter, Prisma.TaskRunWhereInput>
}

export type CostLedgerEntryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  runId?: Prisma.SortOrder
  stepId?: Prisma.SortOrder
  attemptId?: Prisma.SortOrder
  modelProfile?: Prisma.SortOrder
  inputTokens?: Prisma.SortOrder
  outputTokens?: Prisma.SortOrder
  costAmount?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  recordedAt?: Prisma.SortOrder
  run?: Prisma.TaskRunOrderByWithRelationInput
  _relevance?: Prisma.CostLedgerEntryOrderByRelevanceInput
}

export type CostLedgerEntryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CostLedgerEntryWhereInput | Prisma.CostLedgerEntryWhereInput[]
  OR?: Prisma.CostLedgerEntryWhereInput[]
  NOT?: Prisma.CostLedgerEntryWhereInput | Prisma.CostLedgerEntryWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"CostLedgerEntry"> | Date | string
  runId?: Prisma.StringFilter<"CostLedgerEntry"> | string
  stepId?: Prisma.StringFilter<"CostLedgerEntry"> | string
  attemptId?: Prisma.StringFilter<"CostLedgerEntry"> | string
  modelProfile?: Prisma.StringFilter<"CostLedgerEntry"> | string
  inputTokens?: Prisma.IntFilter<"CostLedgerEntry"> | number
  outputTokens?: Prisma.IntFilter<"CostLedgerEntry"> | number
  costAmount?: Prisma.DecimalFilter<"CostLedgerEntry"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFilter<"CostLedgerEntry"> | string
  recordedAt?: Prisma.DateTimeFilter<"CostLedgerEntry"> | Date | string
  run?: Prisma.XOR<Prisma.TaskRunScalarRelationFilter, Prisma.TaskRunWhereInput>
}, "id">

export type CostLedgerEntryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  runId?: Prisma.SortOrder
  stepId?: Prisma.SortOrder
  attemptId?: Prisma.SortOrder
  modelProfile?: Prisma.SortOrder
  inputTokens?: Prisma.SortOrder
  outputTokens?: Prisma.SortOrder
  costAmount?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  recordedAt?: Prisma.SortOrder
  _count?: Prisma.CostLedgerEntryCountOrderByAggregateInput
  _avg?: Prisma.CostLedgerEntryAvgOrderByAggregateInput
  _max?: Prisma.CostLedgerEntryMaxOrderByAggregateInput
  _min?: Prisma.CostLedgerEntryMinOrderByAggregateInput
  _sum?: Prisma.CostLedgerEntrySumOrderByAggregateInput
}

export type CostLedgerEntryScalarWhereWithAggregatesInput = {
  AND?: Prisma.CostLedgerEntryScalarWhereWithAggregatesInput | Prisma.CostLedgerEntryScalarWhereWithAggregatesInput[]
  OR?: Prisma.CostLedgerEntryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CostLedgerEntryScalarWhereWithAggregatesInput | Prisma.CostLedgerEntryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CostLedgerEntry"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CostLedgerEntry"> | Date | string
  runId?: Prisma.StringWithAggregatesFilter<"CostLedgerEntry"> | string
  stepId?: Prisma.StringWithAggregatesFilter<"CostLedgerEntry"> | string
  attemptId?: Prisma.StringWithAggregatesFilter<"CostLedgerEntry"> | string
  modelProfile?: Prisma.StringWithAggregatesFilter<"CostLedgerEntry"> | string
  inputTokens?: Prisma.IntWithAggregatesFilter<"CostLedgerEntry"> | number
  outputTokens?: Prisma.IntWithAggregatesFilter<"CostLedgerEntry"> | number
  costAmount?: Prisma.DecimalWithAggregatesFilter<"CostLedgerEntry"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringWithAggregatesFilter<"CostLedgerEntry"> | string
  recordedAt?: Prisma.DateTimeWithAggregatesFilter<"CostLedgerEntry"> | Date | string
}

export type CostLedgerEntryCreateInput = {
  id: string
  createdAt?: Date | string
  stepId?: string
  attemptId?: string
  modelProfile?: string
  inputTokens?: number
  outputTokens?: number
  costAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: string
  recordedAt?: Date | string
  run: Prisma.TaskRunCreateNestedOneWithoutCostItemsInput
}

export type CostLedgerEntryUncheckedCreateInput = {
  id: string
  createdAt?: Date | string
  runId: string
  stepId?: string
  attemptId?: string
  modelProfile?: string
  inputTokens?: number
  outputTokens?: number
  costAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: string
  recordedAt?: Date | string
}

export type CostLedgerEntryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  stepId?: Prisma.StringFieldUpdateOperationsInput | string
  attemptId?: Prisma.StringFieldUpdateOperationsInput | string
  modelProfile?: Prisma.StringFieldUpdateOperationsInput | string
  inputTokens?: Prisma.IntFieldUpdateOperationsInput | number
  outputTokens?: Prisma.IntFieldUpdateOperationsInput | number
  costAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  run?: Prisma.TaskRunUpdateOneRequiredWithoutCostItemsNestedInput
}

export type CostLedgerEntryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  runId?: Prisma.StringFieldUpdateOperationsInput | string
  stepId?: Prisma.StringFieldUpdateOperationsInput | string
  attemptId?: Prisma.StringFieldUpdateOperationsInput | string
  modelProfile?: Prisma.StringFieldUpdateOperationsInput | string
  inputTokens?: Prisma.IntFieldUpdateOperationsInput | number
  outputTokens?: Prisma.IntFieldUpdateOperationsInput | number
  costAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CostLedgerEntryCreateManyInput = {
  id: string
  createdAt?: Date | string
  runId: string
  stepId?: string
  attemptId?: string
  modelProfile?: string
  inputTokens?: number
  outputTokens?: number
  costAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: string
  recordedAt?: Date | string
}

export type CostLedgerEntryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  stepId?: Prisma.StringFieldUpdateOperationsInput | string
  attemptId?: Prisma.StringFieldUpdateOperationsInput | string
  modelProfile?: Prisma.StringFieldUpdateOperationsInput | string
  inputTokens?: Prisma.IntFieldUpdateOperationsInput | number
  outputTokens?: Prisma.IntFieldUpdateOperationsInput | number
  costAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CostLedgerEntryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  runId?: Prisma.StringFieldUpdateOperationsInput | string
  stepId?: Prisma.StringFieldUpdateOperationsInput | string
  attemptId?: Prisma.StringFieldUpdateOperationsInput | string
  modelProfile?: Prisma.StringFieldUpdateOperationsInput | string
  inputTokens?: Prisma.IntFieldUpdateOperationsInput | number
  outputTokens?: Prisma.IntFieldUpdateOperationsInput | number
  costAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CostLedgerEntryListRelationFilter = {
  every?: Prisma.CostLedgerEntryWhereInput
  some?: Prisma.CostLedgerEntryWhereInput
  none?: Prisma.CostLedgerEntryWhereInput
}

export type CostLedgerEntryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CostLedgerEntryOrderByRelevanceInput = {
  fields: Prisma.CostLedgerEntryOrderByRelevanceFieldEnum | Prisma.CostLedgerEntryOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type CostLedgerEntryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  runId?: Prisma.SortOrder
  stepId?: Prisma.SortOrder
  attemptId?: Prisma.SortOrder
  modelProfile?: Prisma.SortOrder
  inputTokens?: Prisma.SortOrder
  outputTokens?: Prisma.SortOrder
  costAmount?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  recordedAt?: Prisma.SortOrder
}

export type CostLedgerEntryAvgOrderByAggregateInput = {
  inputTokens?: Prisma.SortOrder
  outputTokens?: Prisma.SortOrder
  costAmount?: Prisma.SortOrder
}

export type CostLedgerEntryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  runId?: Prisma.SortOrder
  stepId?: Prisma.SortOrder
  attemptId?: Prisma.SortOrder
  modelProfile?: Prisma.SortOrder
  inputTokens?: Prisma.SortOrder
  outputTokens?: Prisma.SortOrder
  costAmount?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  recordedAt?: Prisma.SortOrder
}

export type CostLedgerEntryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  runId?: Prisma.SortOrder
  stepId?: Prisma.SortOrder
  attemptId?: Prisma.SortOrder
  modelProfile?: Prisma.SortOrder
  inputTokens?: Prisma.SortOrder
  outputTokens?: Prisma.SortOrder
  costAmount?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  recordedAt?: Prisma.SortOrder
}

export type CostLedgerEntrySumOrderByAggregateInput = {
  inputTokens?: Prisma.SortOrder
  outputTokens?: Prisma.SortOrder
  costAmount?: Prisma.SortOrder
}

export type CostLedgerEntryCreateNestedManyWithoutRunInput = {
  create?: Prisma.XOR<Prisma.CostLedgerEntryCreateWithoutRunInput, Prisma.CostLedgerEntryUncheckedCreateWithoutRunInput> | Prisma.CostLedgerEntryCreateWithoutRunInput[] | Prisma.CostLedgerEntryUncheckedCreateWithoutRunInput[]
  connectOrCreate?: Prisma.CostLedgerEntryCreateOrConnectWithoutRunInput | Prisma.CostLedgerEntryCreateOrConnectWithoutRunInput[]
  createMany?: Prisma.CostLedgerEntryCreateManyRunInputEnvelope
  connect?: Prisma.CostLedgerEntryWhereUniqueInput | Prisma.CostLedgerEntryWhereUniqueInput[]
}

export type CostLedgerEntryUncheckedCreateNestedManyWithoutRunInput = {
  create?: Prisma.XOR<Prisma.CostLedgerEntryCreateWithoutRunInput, Prisma.CostLedgerEntryUncheckedCreateWithoutRunInput> | Prisma.CostLedgerEntryCreateWithoutRunInput[] | Prisma.CostLedgerEntryUncheckedCreateWithoutRunInput[]
  connectOrCreate?: Prisma.CostLedgerEntryCreateOrConnectWithoutRunInput | Prisma.CostLedgerEntryCreateOrConnectWithoutRunInput[]
  createMany?: Prisma.CostLedgerEntryCreateManyRunInputEnvelope
  connect?: Prisma.CostLedgerEntryWhereUniqueInput | Prisma.CostLedgerEntryWhereUniqueInput[]
}

export type CostLedgerEntryUpdateManyWithoutRunNestedInput = {
  create?: Prisma.XOR<Prisma.CostLedgerEntryCreateWithoutRunInput, Prisma.CostLedgerEntryUncheckedCreateWithoutRunInput> | Prisma.CostLedgerEntryCreateWithoutRunInput[] | Prisma.CostLedgerEntryUncheckedCreateWithoutRunInput[]
  connectOrCreate?: Prisma.CostLedgerEntryCreateOrConnectWithoutRunInput | Prisma.CostLedgerEntryCreateOrConnectWithoutRunInput[]
  upsert?: Prisma.CostLedgerEntryUpsertWithWhereUniqueWithoutRunInput | Prisma.CostLedgerEntryUpsertWithWhereUniqueWithoutRunInput[]
  createMany?: Prisma.CostLedgerEntryCreateManyRunInputEnvelope
  set?: Prisma.CostLedgerEntryWhereUniqueInput | Prisma.CostLedgerEntryWhereUniqueInput[]
  disconnect?: Prisma.CostLedgerEntryWhereUniqueInput | Prisma.CostLedgerEntryWhereUniqueInput[]
  delete?: Prisma.CostLedgerEntryWhereUniqueInput | Prisma.CostLedgerEntryWhereUniqueInput[]
  connect?: Prisma.CostLedgerEntryWhereUniqueInput | Prisma.CostLedgerEntryWhereUniqueInput[]
  update?: Prisma.CostLedgerEntryUpdateWithWhereUniqueWithoutRunInput | Prisma.CostLedgerEntryUpdateWithWhereUniqueWithoutRunInput[]
  updateMany?: Prisma.CostLedgerEntryUpdateManyWithWhereWithoutRunInput | Prisma.CostLedgerEntryUpdateManyWithWhereWithoutRunInput[]
  deleteMany?: Prisma.CostLedgerEntryScalarWhereInput | Prisma.CostLedgerEntryScalarWhereInput[]
}

export type CostLedgerEntryUncheckedUpdateManyWithoutRunNestedInput = {
  create?: Prisma.XOR<Prisma.CostLedgerEntryCreateWithoutRunInput, Prisma.CostLedgerEntryUncheckedCreateWithoutRunInput> | Prisma.CostLedgerEntryCreateWithoutRunInput[] | Prisma.CostLedgerEntryUncheckedCreateWithoutRunInput[]
  connectOrCreate?: Prisma.CostLedgerEntryCreateOrConnectWithoutRunInput | Prisma.CostLedgerEntryCreateOrConnectWithoutRunInput[]
  upsert?: Prisma.CostLedgerEntryUpsertWithWhereUniqueWithoutRunInput | Prisma.CostLedgerEntryUpsertWithWhereUniqueWithoutRunInput[]
  createMany?: Prisma.CostLedgerEntryCreateManyRunInputEnvelope
  set?: Prisma.CostLedgerEntryWhereUniqueInput | Prisma.CostLedgerEntryWhereUniqueInput[]
  disconnect?: Prisma.CostLedgerEntryWhereUniqueInput | Prisma.CostLedgerEntryWhereUniqueInput[]
  delete?: Prisma.CostLedgerEntryWhereUniqueInput | Prisma.CostLedgerEntryWhereUniqueInput[]
  connect?: Prisma.CostLedgerEntryWhereUniqueInput | Prisma.CostLedgerEntryWhereUniqueInput[]
  update?: Prisma.CostLedgerEntryUpdateWithWhereUniqueWithoutRunInput | Prisma.CostLedgerEntryUpdateWithWhereUniqueWithoutRunInput[]
  updateMany?: Prisma.CostLedgerEntryUpdateManyWithWhereWithoutRunInput | Prisma.CostLedgerEntryUpdateManyWithWhereWithoutRunInput[]
  deleteMany?: Prisma.CostLedgerEntryScalarWhereInput | Prisma.CostLedgerEntryScalarWhereInput[]
}

export type CostLedgerEntryCreateWithoutRunInput = {
  id: string
  createdAt?: Date | string
  stepId?: string
  attemptId?: string
  modelProfile?: string
  inputTokens?: number
  outputTokens?: number
  costAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: string
  recordedAt?: Date | string
}

export type CostLedgerEntryUncheckedCreateWithoutRunInput = {
  id: string
  createdAt?: Date | string
  stepId?: string
  attemptId?: string
  modelProfile?: string
  inputTokens?: number
  outputTokens?: number
  costAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: string
  recordedAt?: Date | string
}

export type CostLedgerEntryCreateOrConnectWithoutRunInput = {
  where: Prisma.CostLedgerEntryWhereUniqueInput
  create: Prisma.XOR<Prisma.CostLedgerEntryCreateWithoutRunInput, Prisma.CostLedgerEntryUncheckedCreateWithoutRunInput>
}

export type CostLedgerEntryCreateManyRunInputEnvelope = {
  data: Prisma.CostLedgerEntryCreateManyRunInput | Prisma.CostLedgerEntryCreateManyRunInput[]
  skipDuplicates?: boolean
}

export type CostLedgerEntryUpsertWithWhereUniqueWithoutRunInput = {
  where: Prisma.CostLedgerEntryWhereUniqueInput
  update: Prisma.XOR<Prisma.CostLedgerEntryUpdateWithoutRunInput, Prisma.CostLedgerEntryUncheckedUpdateWithoutRunInput>
  create: Prisma.XOR<Prisma.CostLedgerEntryCreateWithoutRunInput, Prisma.CostLedgerEntryUncheckedCreateWithoutRunInput>
}

export type CostLedgerEntryUpdateWithWhereUniqueWithoutRunInput = {
  where: Prisma.CostLedgerEntryWhereUniqueInput
  data: Prisma.XOR<Prisma.CostLedgerEntryUpdateWithoutRunInput, Prisma.CostLedgerEntryUncheckedUpdateWithoutRunInput>
}

export type CostLedgerEntryUpdateManyWithWhereWithoutRunInput = {
  where: Prisma.CostLedgerEntryScalarWhereInput
  data: Prisma.XOR<Prisma.CostLedgerEntryUpdateManyMutationInput, Prisma.CostLedgerEntryUncheckedUpdateManyWithoutRunInput>
}

export type CostLedgerEntryScalarWhereInput = {
  AND?: Prisma.CostLedgerEntryScalarWhereInput | Prisma.CostLedgerEntryScalarWhereInput[]
  OR?: Prisma.CostLedgerEntryScalarWhereInput[]
  NOT?: Prisma.CostLedgerEntryScalarWhereInput | Prisma.CostLedgerEntryScalarWhereInput[]
  id?: Prisma.StringFilter<"CostLedgerEntry"> | string
  createdAt?: Prisma.DateTimeFilter<"CostLedgerEntry"> | Date | string
  runId?: Prisma.StringFilter<"CostLedgerEntry"> | string
  stepId?: Prisma.StringFilter<"CostLedgerEntry"> | string
  attemptId?: Prisma.StringFilter<"CostLedgerEntry"> | string
  modelProfile?: Prisma.StringFilter<"CostLedgerEntry"> | string
  inputTokens?: Prisma.IntFilter<"CostLedgerEntry"> | number
  outputTokens?: Prisma.IntFilter<"CostLedgerEntry"> | number
  costAmount?: Prisma.DecimalFilter<"CostLedgerEntry"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFilter<"CostLedgerEntry"> | string
  recordedAt?: Prisma.DateTimeFilter<"CostLedgerEntry"> | Date | string
}

export type CostLedgerEntryCreateManyRunInput = {
  id: string
  createdAt?: Date | string
  stepId?: string
  attemptId?: string
  modelProfile?: string
  inputTokens?: number
  outputTokens?: number
  costAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: string
  recordedAt?: Date | string
}

export type CostLedgerEntryUpdateWithoutRunInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  stepId?: Prisma.StringFieldUpdateOperationsInput | string
  attemptId?: Prisma.StringFieldUpdateOperationsInput | string
  modelProfile?: Prisma.StringFieldUpdateOperationsInput | string
  inputTokens?: Prisma.IntFieldUpdateOperationsInput | number
  outputTokens?: Prisma.IntFieldUpdateOperationsInput | number
  costAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CostLedgerEntryUncheckedUpdateWithoutRunInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  stepId?: Prisma.StringFieldUpdateOperationsInput | string
  attemptId?: Prisma.StringFieldUpdateOperationsInput | string
  modelProfile?: Prisma.StringFieldUpdateOperationsInput | string
  inputTokens?: Prisma.IntFieldUpdateOperationsInput | number
  outputTokens?: Prisma.IntFieldUpdateOperationsInput | number
  costAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CostLedgerEntryUncheckedUpdateManyWithoutRunInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  stepId?: Prisma.StringFieldUpdateOperationsInput | string
  attemptId?: Prisma.StringFieldUpdateOperationsInput | string
  modelProfile?: Prisma.StringFieldUpdateOperationsInput | string
  inputTokens?: Prisma.IntFieldUpdateOperationsInput | number
  outputTokens?: Prisma.IntFieldUpdateOperationsInput | number
  costAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CostLedgerEntrySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  runId?: boolean
  stepId?: boolean
  attemptId?: boolean
  modelProfile?: boolean
  inputTokens?: boolean
  outputTokens?: boolean
  costAmount?: boolean
  currency?: boolean
  recordedAt?: boolean
  run?: boolean | Prisma.TaskRunDefaultArgs<ExtArgs>
}, ExtArgs["result"]["costLedgerEntry"]>

export type CostLedgerEntrySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  runId?: boolean
  stepId?: boolean
  attemptId?: boolean
  modelProfile?: boolean
  inputTokens?: boolean
  outputTokens?: boolean
  costAmount?: boolean
  currency?: boolean
  recordedAt?: boolean
  run?: boolean | Prisma.TaskRunDefaultArgs<ExtArgs>
}, ExtArgs["result"]["costLedgerEntry"]>

export type CostLedgerEntrySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  runId?: boolean
  stepId?: boolean
  attemptId?: boolean
  modelProfile?: boolean
  inputTokens?: boolean
  outputTokens?: boolean
  costAmount?: boolean
  currency?: boolean
  recordedAt?: boolean
  run?: boolean | Prisma.TaskRunDefaultArgs<ExtArgs>
}, ExtArgs["result"]["costLedgerEntry"]>

export type CostLedgerEntrySelectScalar = {
  id?: boolean
  createdAt?: boolean
  runId?: boolean
  stepId?: boolean
  attemptId?: boolean
  modelProfile?: boolean
  inputTokens?: boolean
  outputTokens?: boolean
  costAmount?: boolean
  currency?: boolean
  recordedAt?: boolean
}

export type CostLedgerEntryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "runId" | "stepId" | "attemptId" | "modelProfile" | "inputTokens" | "outputTokens" | "costAmount" | "currency" | "recordedAt", ExtArgs["result"]["costLedgerEntry"]>
export type CostLedgerEntryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  run?: boolean | Prisma.TaskRunDefaultArgs<ExtArgs>
}
export type CostLedgerEntryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  run?: boolean | Prisma.TaskRunDefaultArgs<ExtArgs>
}
export type CostLedgerEntryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  run?: boolean | Prisma.TaskRunDefaultArgs<ExtArgs>
}

export type $CostLedgerEntryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CostLedgerEntry"
  objects: {
    run: Prisma.$TaskRunPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    runId: string
    stepId: string
    attemptId: string
    modelProfile: string
    inputTokens: number
    outputTokens: number
    costAmount: runtime.Decimal
    currency: string
    recordedAt: Date
  }, ExtArgs["result"]["costLedgerEntry"]>
  composites: {}
}

export type CostLedgerEntryGetPayload<S extends boolean | null | undefined | CostLedgerEntryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CostLedgerEntryPayload, S>

export type CostLedgerEntryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CostLedgerEntryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CostLedgerEntryCountAggregateInputType | true
  }

export interface CostLedgerEntryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CostLedgerEntry'], meta: { name: 'CostLedgerEntry' } }
  /**
   * Find zero or one CostLedgerEntry that matches the filter.
   * @param {CostLedgerEntryFindUniqueArgs} args - Arguments to find a CostLedgerEntry
   * @example
   * // Get one CostLedgerEntry
   * const costLedgerEntry = await prisma.costLedgerEntry.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CostLedgerEntryFindUniqueArgs>(args: Prisma.SelectSubset<T, CostLedgerEntryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CostLedgerEntryClient<runtime.Types.Result.GetResult<Prisma.$CostLedgerEntryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CostLedgerEntry that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CostLedgerEntryFindUniqueOrThrowArgs} args - Arguments to find a CostLedgerEntry
   * @example
   * // Get one CostLedgerEntry
   * const costLedgerEntry = await prisma.costLedgerEntry.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CostLedgerEntryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CostLedgerEntryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CostLedgerEntryClient<runtime.Types.Result.GetResult<Prisma.$CostLedgerEntryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CostLedgerEntry that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CostLedgerEntryFindFirstArgs} args - Arguments to find a CostLedgerEntry
   * @example
   * // Get one CostLedgerEntry
   * const costLedgerEntry = await prisma.costLedgerEntry.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CostLedgerEntryFindFirstArgs>(args?: Prisma.SelectSubset<T, CostLedgerEntryFindFirstArgs<ExtArgs>>): Prisma.Prisma__CostLedgerEntryClient<runtime.Types.Result.GetResult<Prisma.$CostLedgerEntryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CostLedgerEntry that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CostLedgerEntryFindFirstOrThrowArgs} args - Arguments to find a CostLedgerEntry
   * @example
   * // Get one CostLedgerEntry
   * const costLedgerEntry = await prisma.costLedgerEntry.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CostLedgerEntryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CostLedgerEntryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CostLedgerEntryClient<runtime.Types.Result.GetResult<Prisma.$CostLedgerEntryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CostLedgerEntries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CostLedgerEntryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CostLedgerEntries
   * const costLedgerEntries = await prisma.costLedgerEntry.findMany()
   * 
   * // Get first 10 CostLedgerEntries
   * const costLedgerEntries = await prisma.costLedgerEntry.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const costLedgerEntryWithIdOnly = await prisma.costLedgerEntry.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CostLedgerEntryFindManyArgs>(args?: Prisma.SelectSubset<T, CostLedgerEntryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CostLedgerEntryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CostLedgerEntry.
   * @param {CostLedgerEntryCreateArgs} args - Arguments to create a CostLedgerEntry.
   * @example
   * // Create one CostLedgerEntry
   * const CostLedgerEntry = await prisma.costLedgerEntry.create({
   *   data: {
   *     // ... data to create a CostLedgerEntry
   *   }
   * })
   * 
   */
  create<T extends CostLedgerEntryCreateArgs>(args: Prisma.SelectSubset<T, CostLedgerEntryCreateArgs<ExtArgs>>): Prisma.Prisma__CostLedgerEntryClient<runtime.Types.Result.GetResult<Prisma.$CostLedgerEntryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CostLedgerEntries.
   * @param {CostLedgerEntryCreateManyArgs} args - Arguments to create many CostLedgerEntries.
   * @example
   * // Create many CostLedgerEntries
   * const costLedgerEntry = await prisma.costLedgerEntry.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CostLedgerEntryCreateManyArgs>(args?: Prisma.SelectSubset<T, CostLedgerEntryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CostLedgerEntries and returns the data saved in the database.
   * @param {CostLedgerEntryCreateManyAndReturnArgs} args - Arguments to create many CostLedgerEntries.
   * @example
   * // Create many CostLedgerEntries
   * const costLedgerEntry = await prisma.costLedgerEntry.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CostLedgerEntries and only return the `id`
   * const costLedgerEntryWithIdOnly = await prisma.costLedgerEntry.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CostLedgerEntryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CostLedgerEntryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CostLedgerEntryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CostLedgerEntry.
   * @param {CostLedgerEntryDeleteArgs} args - Arguments to delete one CostLedgerEntry.
   * @example
   * // Delete one CostLedgerEntry
   * const CostLedgerEntry = await prisma.costLedgerEntry.delete({
   *   where: {
   *     // ... filter to delete one CostLedgerEntry
   *   }
   * })
   * 
   */
  delete<T extends CostLedgerEntryDeleteArgs>(args: Prisma.SelectSubset<T, CostLedgerEntryDeleteArgs<ExtArgs>>): Prisma.Prisma__CostLedgerEntryClient<runtime.Types.Result.GetResult<Prisma.$CostLedgerEntryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CostLedgerEntry.
   * @param {CostLedgerEntryUpdateArgs} args - Arguments to update one CostLedgerEntry.
   * @example
   * // Update one CostLedgerEntry
   * const costLedgerEntry = await prisma.costLedgerEntry.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CostLedgerEntryUpdateArgs>(args: Prisma.SelectSubset<T, CostLedgerEntryUpdateArgs<ExtArgs>>): Prisma.Prisma__CostLedgerEntryClient<runtime.Types.Result.GetResult<Prisma.$CostLedgerEntryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CostLedgerEntries.
   * @param {CostLedgerEntryDeleteManyArgs} args - Arguments to filter CostLedgerEntries to delete.
   * @example
   * // Delete a few CostLedgerEntries
   * const { count } = await prisma.costLedgerEntry.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CostLedgerEntryDeleteManyArgs>(args?: Prisma.SelectSubset<T, CostLedgerEntryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CostLedgerEntries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CostLedgerEntryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CostLedgerEntries
   * const costLedgerEntry = await prisma.costLedgerEntry.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CostLedgerEntryUpdateManyArgs>(args: Prisma.SelectSubset<T, CostLedgerEntryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CostLedgerEntries and returns the data updated in the database.
   * @param {CostLedgerEntryUpdateManyAndReturnArgs} args - Arguments to update many CostLedgerEntries.
   * @example
   * // Update many CostLedgerEntries
   * const costLedgerEntry = await prisma.costLedgerEntry.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CostLedgerEntries and only return the `id`
   * const costLedgerEntryWithIdOnly = await prisma.costLedgerEntry.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CostLedgerEntryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CostLedgerEntryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CostLedgerEntryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CostLedgerEntry.
   * @param {CostLedgerEntryUpsertArgs} args - Arguments to update or create a CostLedgerEntry.
   * @example
   * // Update or create a CostLedgerEntry
   * const costLedgerEntry = await prisma.costLedgerEntry.upsert({
   *   create: {
   *     // ... data to create a CostLedgerEntry
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CostLedgerEntry we want to update
   *   }
   * })
   */
  upsert<T extends CostLedgerEntryUpsertArgs>(args: Prisma.SelectSubset<T, CostLedgerEntryUpsertArgs<ExtArgs>>): Prisma.Prisma__CostLedgerEntryClient<runtime.Types.Result.GetResult<Prisma.$CostLedgerEntryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CostLedgerEntries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CostLedgerEntryCountArgs} args - Arguments to filter CostLedgerEntries to count.
   * @example
   * // Count the number of CostLedgerEntries
   * const count = await prisma.costLedgerEntry.count({
   *   where: {
   *     // ... the filter for the CostLedgerEntries we want to count
   *   }
   * })
  **/
  count<T extends CostLedgerEntryCountArgs>(
    args?: Prisma.Subset<T, CostLedgerEntryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CostLedgerEntryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CostLedgerEntry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CostLedgerEntryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CostLedgerEntryAggregateArgs>(args: Prisma.Subset<T, CostLedgerEntryAggregateArgs>): Prisma.PrismaPromise<GetCostLedgerEntryAggregateType<T>>

  /**
   * Group by CostLedgerEntry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CostLedgerEntryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CostLedgerEntryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CostLedgerEntryGroupByArgs['orderBy'] }
      : { orderBy?: CostLedgerEntryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CostLedgerEntryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCostLedgerEntryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CostLedgerEntry model
 */
readonly fields: CostLedgerEntryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CostLedgerEntry.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CostLedgerEntryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  run<T extends Prisma.TaskRunDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TaskRunDefaultArgs<ExtArgs>>): Prisma.Prisma__TaskRunClient<runtime.Types.Result.GetResult<Prisma.$TaskRunPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CostLedgerEntry model
 */
export interface CostLedgerEntryFieldRefs {
  readonly id: Prisma.FieldRef<"CostLedgerEntry", 'String'>
  readonly createdAt: Prisma.FieldRef<"CostLedgerEntry", 'DateTime'>
  readonly runId: Prisma.FieldRef<"CostLedgerEntry", 'String'>
  readonly stepId: Prisma.FieldRef<"CostLedgerEntry", 'String'>
  readonly attemptId: Prisma.FieldRef<"CostLedgerEntry", 'String'>
  readonly modelProfile: Prisma.FieldRef<"CostLedgerEntry", 'String'>
  readonly inputTokens: Prisma.FieldRef<"CostLedgerEntry", 'Int'>
  readonly outputTokens: Prisma.FieldRef<"CostLedgerEntry", 'Int'>
  readonly costAmount: Prisma.FieldRef<"CostLedgerEntry", 'Decimal'>
  readonly currency: Prisma.FieldRef<"CostLedgerEntry", 'String'>
  readonly recordedAt: Prisma.FieldRef<"CostLedgerEntry", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CostLedgerEntry findUnique
 */
export type CostLedgerEntryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CostLedgerEntry
   */
  select?: Prisma.CostLedgerEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CostLedgerEntry
   */
  omit?: Prisma.CostLedgerEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CostLedgerEntryInclude<ExtArgs> | null
  /**
   * Filter, which CostLedgerEntry to fetch.
   */
  where: Prisma.CostLedgerEntryWhereUniqueInput
}

/**
 * CostLedgerEntry findUniqueOrThrow
 */
export type CostLedgerEntryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CostLedgerEntry
   */
  select?: Prisma.CostLedgerEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CostLedgerEntry
   */
  omit?: Prisma.CostLedgerEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CostLedgerEntryInclude<ExtArgs> | null
  /**
   * Filter, which CostLedgerEntry to fetch.
   */
  where: Prisma.CostLedgerEntryWhereUniqueInput
}

/**
 * CostLedgerEntry findFirst
 */
export type CostLedgerEntryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CostLedgerEntry
   */
  select?: Prisma.CostLedgerEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CostLedgerEntry
   */
  omit?: Prisma.CostLedgerEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CostLedgerEntryInclude<ExtArgs> | null
  /**
   * Filter, which CostLedgerEntry to fetch.
   */
  where?: Prisma.CostLedgerEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CostLedgerEntries to fetch.
   */
  orderBy?: Prisma.CostLedgerEntryOrderByWithRelationInput | Prisma.CostLedgerEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CostLedgerEntries.
   */
  cursor?: Prisma.CostLedgerEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CostLedgerEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CostLedgerEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CostLedgerEntries.
   */
  distinct?: Prisma.CostLedgerEntryScalarFieldEnum | Prisma.CostLedgerEntryScalarFieldEnum[]
}

/**
 * CostLedgerEntry findFirstOrThrow
 */
export type CostLedgerEntryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CostLedgerEntry
   */
  select?: Prisma.CostLedgerEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CostLedgerEntry
   */
  omit?: Prisma.CostLedgerEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CostLedgerEntryInclude<ExtArgs> | null
  /**
   * Filter, which CostLedgerEntry to fetch.
   */
  where?: Prisma.CostLedgerEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CostLedgerEntries to fetch.
   */
  orderBy?: Prisma.CostLedgerEntryOrderByWithRelationInput | Prisma.CostLedgerEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CostLedgerEntries.
   */
  cursor?: Prisma.CostLedgerEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CostLedgerEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CostLedgerEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CostLedgerEntries.
   */
  distinct?: Prisma.CostLedgerEntryScalarFieldEnum | Prisma.CostLedgerEntryScalarFieldEnum[]
}

/**
 * CostLedgerEntry findMany
 */
export type CostLedgerEntryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CostLedgerEntry
   */
  select?: Prisma.CostLedgerEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CostLedgerEntry
   */
  omit?: Prisma.CostLedgerEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CostLedgerEntryInclude<ExtArgs> | null
  /**
   * Filter, which CostLedgerEntries to fetch.
   */
  where?: Prisma.CostLedgerEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CostLedgerEntries to fetch.
   */
  orderBy?: Prisma.CostLedgerEntryOrderByWithRelationInput | Prisma.CostLedgerEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CostLedgerEntries.
   */
  cursor?: Prisma.CostLedgerEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CostLedgerEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CostLedgerEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CostLedgerEntries.
   */
  distinct?: Prisma.CostLedgerEntryScalarFieldEnum | Prisma.CostLedgerEntryScalarFieldEnum[]
}

/**
 * CostLedgerEntry create
 */
export type CostLedgerEntryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CostLedgerEntry
   */
  select?: Prisma.CostLedgerEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CostLedgerEntry
   */
  omit?: Prisma.CostLedgerEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CostLedgerEntryInclude<ExtArgs> | null
  /**
   * The data needed to create a CostLedgerEntry.
   */
  data: Prisma.XOR<Prisma.CostLedgerEntryCreateInput, Prisma.CostLedgerEntryUncheckedCreateInput>
}

/**
 * CostLedgerEntry createMany
 */
export type CostLedgerEntryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CostLedgerEntries.
   */
  data: Prisma.CostLedgerEntryCreateManyInput | Prisma.CostLedgerEntryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CostLedgerEntry createManyAndReturn
 */
export type CostLedgerEntryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CostLedgerEntry
   */
  select?: Prisma.CostLedgerEntrySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CostLedgerEntry
   */
  omit?: Prisma.CostLedgerEntryOmit<ExtArgs> | null
  /**
   * The data used to create many CostLedgerEntries.
   */
  data: Prisma.CostLedgerEntryCreateManyInput | Prisma.CostLedgerEntryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CostLedgerEntryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CostLedgerEntry update
 */
export type CostLedgerEntryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CostLedgerEntry
   */
  select?: Prisma.CostLedgerEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CostLedgerEntry
   */
  omit?: Prisma.CostLedgerEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CostLedgerEntryInclude<ExtArgs> | null
  /**
   * The data needed to update a CostLedgerEntry.
   */
  data: Prisma.XOR<Prisma.CostLedgerEntryUpdateInput, Prisma.CostLedgerEntryUncheckedUpdateInput>
  /**
   * Choose, which CostLedgerEntry to update.
   */
  where: Prisma.CostLedgerEntryWhereUniqueInput
}

/**
 * CostLedgerEntry updateMany
 */
export type CostLedgerEntryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CostLedgerEntries.
   */
  data: Prisma.XOR<Prisma.CostLedgerEntryUpdateManyMutationInput, Prisma.CostLedgerEntryUncheckedUpdateManyInput>
  /**
   * Filter which CostLedgerEntries to update
   */
  where?: Prisma.CostLedgerEntryWhereInput
  /**
   * Limit how many CostLedgerEntries to update.
   */
  limit?: number
}

/**
 * CostLedgerEntry updateManyAndReturn
 */
export type CostLedgerEntryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CostLedgerEntry
   */
  select?: Prisma.CostLedgerEntrySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CostLedgerEntry
   */
  omit?: Prisma.CostLedgerEntryOmit<ExtArgs> | null
  /**
   * The data used to update CostLedgerEntries.
   */
  data: Prisma.XOR<Prisma.CostLedgerEntryUpdateManyMutationInput, Prisma.CostLedgerEntryUncheckedUpdateManyInput>
  /**
   * Filter which CostLedgerEntries to update
   */
  where?: Prisma.CostLedgerEntryWhereInput
  /**
   * Limit how many CostLedgerEntries to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CostLedgerEntryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CostLedgerEntry upsert
 */
export type CostLedgerEntryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CostLedgerEntry
   */
  select?: Prisma.CostLedgerEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CostLedgerEntry
   */
  omit?: Prisma.CostLedgerEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CostLedgerEntryInclude<ExtArgs> | null
  /**
   * The filter to search for the CostLedgerEntry to update in case it exists.
   */
  where: Prisma.CostLedgerEntryWhereUniqueInput
  /**
   * In case the CostLedgerEntry found by the `where` argument doesn't exist, create a new CostLedgerEntry with this data.
   */
  create: Prisma.XOR<Prisma.CostLedgerEntryCreateInput, Prisma.CostLedgerEntryUncheckedCreateInput>
  /**
   * In case the CostLedgerEntry was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CostLedgerEntryUpdateInput, Prisma.CostLedgerEntryUncheckedUpdateInput>
}

/**
 * CostLedgerEntry delete
 */
export type CostLedgerEntryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CostLedgerEntry
   */
  select?: Prisma.CostLedgerEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CostLedgerEntry
   */
  omit?: Prisma.CostLedgerEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CostLedgerEntryInclude<ExtArgs> | null
  /**
   * Filter which CostLedgerEntry to delete.
   */
  where: Prisma.CostLedgerEntryWhereUniqueInput
}

/**
 * CostLedgerEntry deleteMany
 */
export type CostLedgerEntryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CostLedgerEntries to delete
   */
  where?: Prisma.CostLedgerEntryWhereInput
  /**
   * Limit how many CostLedgerEntries to delete.
   */
  limit?: number
}

/**
 * CostLedgerEntry without action
 */
export type CostLedgerEntryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CostLedgerEntry
   */
  select?: Prisma.CostLedgerEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CostLedgerEntry
   */
  omit?: Prisma.CostLedgerEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CostLedgerEntryInclude<ExtArgs> | null
}
