
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `InboxItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model InboxItem
 * 
 */
export type InboxItemModel = runtime.Types.Result.DefaultSelection<Prisma.$InboxItemPayload>

export type AggregateInboxItem = {
  _count: InboxItemCountAggregateOutputType | null
  _min: InboxItemMinAggregateOutputType | null
  _max: InboxItemMaxAggregateOutputType | null
}

export type InboxItemMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  kind: string | null
  runId: string | null
  taskId: string | null
  stepId: string | null
  projectId: string | null
  title: string | null
  status: string | null
  resolvedBy: string | null
  resolvedAt: Date | null
}

export type InboxItemMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  kind: string | null
  runId: string | null
  taskId: string | null
  stepId: string | null
  projectId: string | null
  title: string | null
  status: string | null
  resolvedBy: string | null
  resolvedAt: Date | null
}

export type InboxItemCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  kind: number
  runId: number
  taskId: number
  stepId: number
  projectId: number
  title: number
  context: number
  options: number
  status: number
  answer: number
  resolvedBy: number
  resolvedAt: number
  _all: number
}


export type InboxItemMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  kind?: true
  runId?: true
  taskId?: true
  stepId?: true
  projectId?: true
  title?: true
  status?: true
  resolvedBy?: true
  resolvedAt?: true
}

export type InboxItemMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  kind?: true
  runId?: true
  taskId?: true
  stepId?: true
  projectId?: true
  title?: true
  status?: true
  resolvedBy?: true
  resolvedAt?: true
}

export type InboxItemCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  kind?: true
  runId?: true
  taskId?: true
  stepId?: true
  projectId?: true
  title?: true
  context?: true
  options?: true
  status?: true
  answer?: true
  resolvedBy?: true
  resolvedAt?: true
  _all?: true
}

export type InboxItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which InboxItem to aggregate.
   */
  where?: Prisma.InboxItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InboxItems to fetch.
   */
  orderBy?: Prisma.InboxItemOrderByWithRelationInput | Prisma.InboxItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.InboxItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InboxItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InboxItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned InboxItems
  **/
  _count?: true | InboxItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: InboxItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: InboxItemMaxAggregateInputType
}

export type GetInboxItemAggregateType<T extends InboxItemAggregateArgs> = {
      [P in keyof T & keyof AggregateInboxItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateInboxItem[P]>
    : Prisma.GetScalarType<T[P], AggregateInboxItem[P]>
}




export type InboxItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InboxItemWhereInput
  orderBy?: Prisma.InboxItemOrderByWithAggregationInput | Prisma.InboxItemOrderByWithAggregationInput[]
  by: Prisma.InboxItemScalarFieldEnum[] | Prisma.InboxItemScalarFieldEnum
  having?: Prisma.InboxItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: InboxItemCountAggregateInputType | true
  _min?: InboxItemMinAggregateInputType
  _max?: InboxItemMaxAggregateInputType
}

export type InboxItemGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  kind: string
  runId: string | null
  taskId: string
  stepId: string
  projectId: string
  title: string
  context: runtime.JsonValue
  options: string[]
  status: string
  answer: runtime.JsonValue | null
  resolvedBy: string
  resolvedAt: Date | null
  _count: InboxItemCountAggregateOutputType | null
  _min: InboxItemMinAggregateOutputType | null
  _max: InboxItemMaxAggregateOutputType | null
}

export type GetInboxItemGroupByPayload<T extends InboxItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<InboxItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof InboxItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], InboxItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], InboxItemGroupByOutputType[P]>
      }
    >
  >



export type InboxItemWhereInput = {
  AND?: Prisma.InboxItemWhereInput | Prisma.InboxItemWhereInput[]
  OR?: Prisma.InboxItemWhereInput[]
  NOT?: Prisma.InboxItemWhereInput | Prisma.InboxItemWhereInput[]
  id?: Prisma.StringFilter<"InboxItem"> | string
  createdAt?: Prisma.DateTimeFilter<"InboxItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"InboxItem"> | Date | string
  kind?: Prisma.StringFilter<"InboxItem"> | string
  runId?: Prisma.StringNullableFilter<"InboxItem"> | string | null
  taskId?: Prisma.StringFilter<"InboxItem"> | string
  stepId?: Prisma.StringFilter<"InboxItem"> | string
  projectId?: Prisma.StringFilter<"InboxItem"> | string
  title?: Prisma.StringFilter<"InboxItem"> | string
  context?: Prisma.JsonFilter<"InboxItem">
  options?: Prisma.StringNullableListFilter<"InboxItem">
  status?: Prisma.StringFilter<"InboxItem"> | string
  answer?: Prisma.JsonNullableFilter<"InboxItem">
  resolvedBy?: Prisma.StringFilter<"InboxItem"> | string
  resolvedAt?: Prisma.DateTimeNullableFilter<"InboxItem"> | Date | string | null
  run?: Prisma.XOR<Prisma.TaskRunNullableScalarRelationFilter, Prisma.TaskRunWhereInput> | null
}

export type InboxItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  runId?: Prisma.SortOrderInput | Prisma.SortOrder
  taskId?: Prisma.SortOrder
  stepId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  context?: Prisma.SortOrder
  options?: Prisma.SortOrder
  status?: Prisma.SortOrder
  answer?: Prisma.SortOrderInput | Prisma.SortOrder
  resolvedBy?: Prisma.SortOrder
  resolvedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  run?: Prisma.TaskRunOrderByWithRelationInput
  _relevance?: Prisma.InboxItemOrderByRelevanceInput
}

export type InboxItemWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.InboxItemWhereInput | Prisma.InboxItemWhereInput[]
  OR?: Prisma.InboxItemWhereInput[]
  NOT?: Prisma.InboxItemWhereInput | Prisma.InboxItemWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"InboxItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"InboxItem"> | Date | string
  kind?: Prisma.StringFilter<"InboxItem"> | string
  runId?: Prisma.StringNullableFilter<"InboxItem"> | string | null
  taskId?: Prisma.StringFilter<"InboxItem"> | string
  stepId?: Prisma.StringFilter<"InboxItem"> | string
  projectId?: Prisma.StringFilter<"InboxItem"> | string
  title?: Prisma.StringFilter<"InboxItem"> | string
  context?: Prisma.JsonFilter<"InboxItem">
  options?: Prisma.StringNullableListFilter<"InboxItem">
  status?: Prisma.StringFilter<"InboxItem"> | string
  answer?: Prisma.JsonNullableFilter<"InboxItem">
  resolvedBy?: Prisma.StringFilter<"InboxItem"> | string
  resolvedAt?: Prisma.DateTimeNullableFilter<"InboxItem"> | Date | string | null
  run?: Prisma.XOR<Prisma.TaskRunNullableScalarRelationFilter, Prisma.TaskRunWhereInput> | null
}, "id">

export type InboxItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  runId?: Prisma.SortOrderInput | Prisma.SortOrder
  taskId?: Prisma.SortOrder
  stepId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  context?: Prisma.SortOrder
  options?: Prisma.SortOrder
  status?: Prisma.SortOrder
  answer?: Prisma.SortOrderInput | Prisma.SortOrder
  resolvedBy?: Prisma.SortOrder
  resolvedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.InboxItemCountOrderByAggregateInput
  _max?: Prisma.InboxItemMaxOrderByAggregateInput
  _min?: Prisma.InboxItemMinOrderByAggregateInput
}

export type InboxItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.InboxItemScalarWhereWithAggregatesInput | Prisma.InboxItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.InboxItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.InboxItemScalarWhereWithAggregatesInput | Prisma.InboxItemScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"InboxItem"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"InboxItem"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"InboxItem"> | Date | string
  kind?: Prisma.StringWithAggregatesFilter<"InboxItem"> | string
  runId?: Prisma.StringNullableWithAggregatesFilter<"InboxItem"> | string | null
  taskId?: Prisma.StringWithAggregatesFilter<"InboxItem"> | string
  stepId?: Prisma.StringWithAggregatesFilter<"InboxItem"> | string
  projectId?: Prisma.StringWithAggregatesFilter<"InboxItem"> | string
  title?: Prisma.StringWithAggregatesFilter<"InboxItem"> | string
  context?: Prisma.JsonWithAggregatesFilter<"InboxItem">
  options?: Prisma.StringNullableListFilter<"InboxItem">
  status?: Prisma.StringWithAggregatesFilter<"InboxItem"> | string
  answer?: Prisma.JsonNullableWithAggregatesFilter<"InboxItem">
  resolvedBy?: Prisma.StringWithAggregatesFilter<"InboxItem"> | string
  resolvedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"InboxItem"> | Date | string | null
}

export type InboxItemCreateInput = {
  id: string
  createdAt?: Date | string
  updatedAt?: Date | string
  kind: string
  taskId?: string
  stepId?: string
  projectId?: string
  title: string
  context?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  options?: Prisma.InboxItemCreateoptionsInput | string[]
  status: string
  answer?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  resolvedBy?: string
  resolvedAt?: Date | string | null
  run?: Prisma.TaskRunCreateNestedOneWithoutInboxInput
}

export type InboxItemUncheckedCreateInput = {
  id: string
  createdAt?: Date | string
  updatedAt?: Date | string
  kind: string
  runId?: string | null
  taskId?: string
  stepId?: string
  projectId?: string
  title: string
  context?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  options?: Prisma.InboxItemCreateoptionsInput | string[]
  status: string
  answer?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  resolvedBy?: string
  resolvedAt?: Date | string | null
}

export type InboxItemUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  kind?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  stepId?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  options?: Prisma.InboxItemUpdateoptionsInput | string[]
  status?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  resolvedBy?: Prisma.StringFieldUpdateOperationsInput | string
  resolvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  run?: Prisma.TaskRunUpdateOneWithoutInboxNestedInput
}

export type InboxItemUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  kind?: Prisma.StringFieldUpdateOperationsInput | string
  runId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  stepId?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  options?: Prisma.InboxItemUpdateoptionsInput | string[]
  status?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  resolvedBy?: Prisma.StringFieldUpdateOperationsInput | string
  resolvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type InboxItemCreateManyInput = {
  id: string
  createdAt?: Date | string
  updatedAt?: Date | string
  kind: string
  runId?: string | null
  taskId?: string
  stepId?: string
  projectId?: string
  title: string
  context?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  options?: Prisma.InboxItemCreateoptionsInput | string[]
  status: string
  answer?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  resolvedBy?: string
  resolvedAt?: Date | string | null
}

export type InboxItemUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  kind?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  stepId?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  options?: Prisma.InboxItemUpdateoptionsInput | string[]
  status?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  resolvedBy?: Prisma.StringFieldUpdateOperationsInput | string
  resolvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type InboxItemUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  kind?: Prisma.StringFieldUpdateOperationsInput | string
  runId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  stepId?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  options?: Prisma.InboxItemUpdateoptionsInput | string[]
  status?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  resolvedBy?: Prisma.StringFieldUpdateOperationsInput | string
  resolvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type InboxItemListRelationFilter = {
  every?: Prisma.InboxItemWhereInput
  some?: Prisma.InboxItemWhereInput
  none?: Prisma.InboxItemWhereInput
}

export type InboxItemOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type InboxItemOrderByRelevanceInput = {
  fields: Prisma.InboxItemOrderByRelevanceFieldEnum | Prisma.InboxItemOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type InboxItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  runId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  stepId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  context?: Prisma.SortOrder
  options?: Prisma.SortOrder
  status?: Prisma.SortOrder
  answer?: Prisma.SortOrder
  resolvedBy?: Prisma.SortOrder
  resolvedAt?: Prisma.SortOrder
}

export type InboxItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  runId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  stepId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  status?: Prisma.SortOrder
  resolvedBy?: Prisma.SortOrder
  resolvedAt?: Prisma.SortOrder
}

export type InboxItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  runId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  stepId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  status?: Prisma.SortOrder
  resolvedBy?: Prisma.SortOrder
  resolvedAt?: Prisma.SortOrder
}

export type InboxItemCreateNestedManyWithoutRunInput = {
  create?: Prisma.XOR<Prisma.InboxItemCreateWithoutRunInput, Prisma.InboxItemUncheckedCreateWithoutRunInput> | Prisma.InboxItemCreateWithoutRunInput[] | Prisma.InboxItemUncheckedCreateWithoutRunInput[]
  connectOrCreate?: Prisma.InboxItemCreateOrConnectWithoutRunInput | Prisma.InboxItemCreateOrConnectWithoutRunInput[]
  createMany?: Prisma.InboxItemCreateManyRunInputEnvelope
  connect?: Prisma.InboxItemWhereUniqueInput | Prisma.InboxItemWhereUniqueInput[]
}

export type InboxItemUncheckedCreateNestedManyWithoutRunInput = {
  create?: Prisma.XOR<Prisma.InboxItemCreateWithoutRunInput, Prisma.InboxItemUncheckedCreateWithoutRunInput> | Prisma.InboxItemCreateWithoutRunInput[] | Prisma.InboxItemUncheckedCreateWithoutRunInput[]
  connectOrCreate?: Prisma.InboxItemCreateOrConnectWithoutRunInput | Prisma.InboxItemCreateOrConnectWithoutRunInput[]
  createMany?: Prisma.InboxItemCreateManyRunInputEnvelope
  connect?: Prisma.InboxItemWhereUniqueInput | Prisma.InboxItemWhereUniqueInput[]
}

export type InboxItemUpdateManyWithoutRunNestedInput = {
  create?: Prisma.XOR<Prisma.InboxItemCreateWithoutRunInput, Prisma.InboxItemUncheckedCreateWithoutRunInput> | Prisma.InboxItemCreateWithoutRunInput[] | Prisma.InboxItemUncheckedCreateWithoutRunInput[]
  connectOrCreate?: Prisma.InboxItemCreateOrConnectWithoutRunInput | Prisma.InboxItemCreateOrConnectWithoutRunInput[]
  upsert?: Prisma.InboxItemUpsertWithWhereUniqueWithoutRunInput | Prisma.InboxItemUpsertWithWhereUniqueWithoutRunInput[]
  createMany?: Prisma.InboxItemCreateManyRunInputEnvelope
  set?: Prisma.InboxItemWhereUniqueInput | Prisma.InboxItemWhereUniqueInput[]
  disconnect?: Prisma.InboxItemWhereUniqueInput | Prisma.InboxItemWhereUniqueInput[]
  delete?: Prisma.InboxItemWhereUniqueInput | Prisma.InboxItemWhereUniqueInput[]
  connect?: Prisma.InboxItemWhereUniqueInput | Prisma.InboxItemWhereUniqueInput[]
  update?: Prisma.InboxItemUpdateWithWhereUniqueWithoutRunInput | Prisma.InboxItemUpdateWithWhereUniqueWithoutRunInput[]
  updateMany?: Prisma.InboxItemUpdateManyWithWhereWithoutRunInput | Prisma.InboxItemUpdateManyWithWhereWithoutRunInput[]
  deleteMany?: Prisma.InboxItemScalarWhereInput | Prisma.InboxItemScalarWhereInput[]
}

export type InboxItemUncheckedUpdateManyWithoutRunNestedInput = {
  create?: Prisma.XOR<Prisma.InboxItemCreateWithoutRunInput, Prisma.InboxItemUncheckedCreateWithoutRunInput> | Prisma.InboxItemCreateWithoutRunInput[] | Prisma.InboxItemUncheckedCreateWithoutRunInput[]
  connectOrCreate?: Prisma.InboxItemCreateOrConnectWithoutRunInput | Prisma.InboxItemCreateOrConnectWithoutRunInput[]
  upsert?: Prisma.InboxItemUpsertWithWhereUniqueWithoutRunInput | Prisma.InboxItemUpsertWithWhereUniqueWithoutRunInput[]
  createMany?: Prisma.InboxItemCreateManyRunInputEnvelope
  set?: Prisma.InboxItemWhereUniqueInput | Prisma.InboxItemWhereUniqueInput[]
  disconnect?: Prisma.InboxItemWhereUniqueInput | Prisma.InboxItemWhereUniqueInput[]
  delete?: Prisma.InboxItemWhereUniqueInput | Prisma.InboxItemWhereUniqueInput[]
  connect?: Prisma.InboxItemWhereUniqueInput | Prisma.InboxItemWhereUniqueInput[]
  update?: Prisma.InboxItemUpdateWithWhereUniqueWithoutRunInput | Prisma.InboxItemUpdateWithWhereUniqueWithoutRunInput[]
  updateMany?: Prisma.InboxItemUpdateManyWithWhereWithoutRunInput | Prisma.InboxItemUpdateManyWithWhereWithoutRunInput[]
  deleteMany?: Prisma.InboxItemScalarWhereInput | Prisma.InboxItemScalarWhereInput[]
}

export type InboxItemCreateoptionsInput = {
  set: string[]
}

export type InboxItemUpdateoptionsInput = {
  set?: string[]
  push?: string | string[]
}

export type InboxItemCreateWithoutRunInput = {
  id: string
  createdAt?: Date | string
  updatedAt?: Date | string
  kind: string
  taskId?: string
  stepId?: string
  projectId?: string
  title: string
  context?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  options?: Prisma.InboxItemCreateoptionsInput | string[]
  status: string
  answer?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  resolvedBy?: string
  resolvedAt?: Date | string | null
}

export type InboxItemUncheckedCreateWithoutRunInput = {
  id: string
  createdAt?: Date | string
  updatedAt?: Date | string
  kind: string
  taskId?: string
  stepId?: string
  projectId?: string
  title: string
  context?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  options?: Prisma.InboxItemCreateoptionsInput | string[]
  status: string
  answer?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  resolvedBy?: string
  resolvedAt?: Date | string | null
}

export type InboxItemCreateOrConnectWithoutRunInput = {
  where: Prisma.InboxItemWhereUniqueInput
  create: Prisma.XOR<Prisma.InboxItemCreateWithoutRunInput, Prisma.InboxItemUncheckedCreateWithoutRunInput>
}

export type InboxItemCreateManyRunInputEnvelope = {
  data: Prisma.InboxItemCreateManyRunInput | Prisma.InboxItemCreateManyRunInput[]
  skipDuplicates?: boolean
}

export type InboxItemUpsertWithWhereUniqueWithoutRunInput = {
  where: Prisma.InboxItemWhereUniqueInput
  update: Prisma.XOR<Prisma.InboxItemUpdateWithoutRunInput, Prisma.InboxItemUncheckedUpdateWithoutRunInput>
  create: Prisma.XOR<Prisma.InboxItemCreateWithoutRunInput, Prisma.InboxItemUncheckedCreateWithoutRunInput>
}

export type InboxItemUpdateWithWhereUniqueWithoutRunInput = {
  where: Prisma.InboxItemWhereUniqueInput
  data: Prisma.XOR<Prisma.InboxItemUpdateWithoutRunInput, Prisma.InboxItemUncheckedUpdateWithoutRunInput>
}

export type InboxItemUpdateManyWithWhereWithoutRunInput = {
  where: Prisma.InboxItemScalarWhereInput
  data: Prisma.XOR<Prisma.InboxItemUpdateManyMutationInput, Prisma.InboxItemUncheckedUpdateManyWithoutRunInput>
}

export type InboxItemScalarWhereInput = {
  AND?: Prisma.InboxItemScalarWhereInput | Prisma.InboxItemScalarWhereInput[]
  OR?: Prisma.InboxItemScalarWhereInput[]
  NOT?: Prisma.InboxItemScalarWhereInput | Prisma.InboxItemScalarWhereInput[]
  id?: Prisma.StringFilter<"InboxItem"> | string
  createdAt?: Prisma.DateTimeFilter<"InboxItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"InboxItem"> | Date | string
  kind?: Prisma.StringFilter<"InboxItem"> | string
  runId?: Prisma.StringNullableFilter<"InboxItem"> | string | null
  taskId?: Prisma.StringFilter<"InboxItem"> | string
  stepId?: Prisma.StringFilter<"InboxItem"> | string
  projectId?: Prisma.StringFilter<"InboxItem"> | string
  title?: Prisma.StringFilter<"InboxItem"> | string
  context?: Prisma.JsonFilter<"InboxItem">
  options?: Prisma.StringNullableListFilter<"InboxItem">
  status?: Prisma.StringFilter<"InboxItem"> | string
  answer?: Prisma.JsonNullableFilter<"InboxItem">
  resolvedBy?: Prisma.StringFilter<"InboxItem"> | string
  resolvedAt?: Prisma.DateTimeNullableFilter<"InboxItem"> | Date | string | null
}

export type InboxItemCreateManyRunInput = {
  id: string
  createdAt?: Date | string
  updatedAt?: Date | string
  kind: string
  taskId?: string
  stepId?: string
  projectId?: string
  title: string
  context?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  options?: Prisma.InboxItemCreateoptionsInput | string[]
  status: string
  answer?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  resolvedBy?: string
  resolvedAt?: Date | string | null
}

export type InboxItemUpdateWithoutRunInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  kind?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  stepId?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  options?: Prisma.InboxItemUpdateoptionsInput | string[]
  status?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  resolvedBy?: Prisma.StringFieldUpdateOperationsInput | string
  resolvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type InboxItemUncheckedUpdateWithoutRunInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  kind?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  stepId?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  options?: Prisma.InboxItemUpdateoptionsInput | string[]
  status?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  resolvedBy?: Prisma.StringFieldUpdateOperationsInput | string
  resolvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type InboxItemUncheckedUpdateManyWithoutRunInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  kind?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  stepId?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  options?: Prisma.InboxItemUpdateoptionsInput | string[]
  status?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  resolvedBy?: Prisma.StringFieldUpdateOperationsInput | string
  resolvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type InboxItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  kind?: boolean
  runId?: boolean
  taskId?: boolean
  stepId?: boolean
  projectId?: boolean
  title?: boolean
  context?: boolean
  options?: boolean
  status?: boolean
  answer?: boolean
  resolvedBy?: boolean
  resolvedAt?: boolean
  run?: boolean | Prisma.InboxItem$runArgs<ExtArgs>
}, ExtArgs["result"]["inboxItem"]>

export type InboxItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  kind?: boolean
  runId?: boolean
  taskId?: boolean
  stepId?: boolean
  projectId?: boolean
  title?: boolean
  context?: boolean
  options?: boolean
  status?: boolean
  answer?: boolean
  resolvedBy?: boolean
  resolvedAt?: boolean
  run?: boolean | Prisma.InboxItem$runArgs<ExtArgs>
}, ExtArgs["result"]["inboxItem"]>

export type InboxItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  kind?: boolean
  runId?: boolean
  taskId?: boolean
  stepId?: boolean
  projectId?: boolean
  title?: boolean
  context?: boolean
  options?: boolean
  status?: boolean
  answer?: boolean
  resolvedBy?: boolean
  resolvedAt?: boolean
  run?: boolean | Prisma.InboxItem$runArgs<ExtArgs>
}, ExtArgs["result"]["inboxItem"]>

export type InboxItemSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  kind?: boolean
  runId?: boolean
  taskId?: boolean
  stepId?: boolean
  projectId?: boolean
  title?: boolean
  context?: boolean
  options?: boolean
  status?: boolean
  answer?: boolean
  resolvedBy?: boolean
  resolvedAt?: boolean
}

export type InboxItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "kind" | "runId" | "taskId" | "stepId" | "projectId" | "title" | "context" | "options" | "status" | "answer" | "resolvedBy" | "resolvedAt", ExtArgs["result"]["inboxItem"]>
export type InboxItemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  run?: boolean | Prisma.InboxItem$runArgs<ExtArgs>
}
export type InboxItemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  run?: boolean | Prisma.InboxItem$runArgs<ExtArgs>
}
export type InboxItemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  run?: boolean | Prisma.InboxItem$runArgs<ExtArgs>
}

export type $InboxItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "InboxItem"
  objects: {
    run: Prisma.$TaskRunPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    kind: string
    runId: string | null
    taskId: string
    stepId: string
    projectId: string
    title: string
    context: runtime.JsonValue
    options: string[]
    status: string
    answer: runtime.JsonValue | null
    resolvedBy: string
    resolvedAt: Date | null
  }, ExtArgs["result"]["inboxItem"]>
  composites: {}
}

export type InboxItemGetPayload<S extends boolean | null | undefined | InboxItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$InboxItemPayload, S>

export type InboxItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<InboxItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: InboxItemCountAggregateInputType | true
  }

export interface InboxItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['InboxItem'], meta: { name: 'InboxItem' } }
  /**
   * Find zero or one InboxItem that matches the filter.
   * @param {InboxItemFindUniqueArgs} args - Arguments to find a InboxItem
   * @example
   * // Get one InboxItem
   * const inboxItem = await prisma.inboxItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends InboxItemFindUniqueArgs>(args: Prisma.SelectSubset<T, InboxItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__InboxItemClient<runtime.Types.Result.GetResult<Prisma.$InboxItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one InboxItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {InboxItemFindUniqueOrThrowArgs} args - Arguments to find a InboxItem
   * @example
   * // Get one InboxItem
   * const inboxItem = await prisma.inboxItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends InboxItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, InboxItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__InboxItemClient<runtime.Types.Result.GetResult<Prisma.$InboxItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first InboxItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InboxItemFindFirstArgs} args - Arguments to find a InboxItem
   * @example
   * // Get one InboxItem
   * const inboxItem = await prisma.inboxItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends InboxItemFindFirstArgs>(args?: Prisma.SelectSubset<T, InboxItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__InboxItemClient<runtime.Types.Result.GetResult<Prisma.$InboxItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first InboxItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InboxItemFindFirstOrThrowArgs} args - Arguments to find a InboxItem
   * @example
   * // Get one InboxItem
   * const inboxItem = await prisma.inboxItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends InboxItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, InboxItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__InboxItemClient<runtime.Types.Result.GetResult<Prisma.$InboxItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more InboxItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InboxItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all InboxItems
   * const inboxItems = await prisma.inboxItem.findMany()
   * 
   * // Get first 10 InboxItems
   * const inboxItems = await prisma.inboxItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const inboxItemWithIdOnly = await prisma.inboxItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends InboxItemFindManyArgs>(args?: Prisma.SelectSubset<T, InboxItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InboxItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a InboxItem.
   * @param {InboxItemCreateArgs} args - Arguments to create a InboxItem.
   * @example
   * // Create one InboxItem
   * const InboxItem = await prisma.inboxItem.create({
   *   data: {
   *     // ... data to create a InboxItem
   *   }
   * })
   * 
   */
  create<T extends InboxItemCreateArgs>(args: Prisma.SelectSubset<T, InboxItemCreateArgs<ExtArgs>>): Prisma.Prisma__InboxItemClient<runtime.Types.Result.GetResult<Prisma.$InboxItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many InboxItems.
   * @param {InboxItemCreateManyArgs} args - Arguments to create many InboxItems.
   * @example
   * // Create many InboxItems
   * const inboxItem = await prisma.inboxItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends InboxItemCreateManyArgs>(args?: Prisma.SelectSubset<T, InboxItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many InboxItems and returns the data saved in the database.
   * @param {InboxItemCreateManyAndReturnArgs} args - Arguments to create many InboxItems.
   * @example
   * // Create many InboxItems
   * const inboxItem = await prisma.inboxItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many InboxItems and only return the `id`
   * const inboxItemWithIdOnly = await prisma.inboxItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends InboxItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, InboxItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InboxItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a InboxItem.
   * @param {InboxItemDeleteArgs} args - Arguments to delete one InboxItem.
   * @example
   * // Delete one InboxItem
   * const InboxItem = await prisma.inboxItem.delete({
   *   where: {
   *     // ... filter to delete one InboxItem
   *   }
   * })
   * 
   */
  delete<T extends InboxItemDeleteArgs>(args: Prisma.SelectSubset<T, InboxItemDeleteArgs<ExtArgs>>): Prisma.Prisma__InboxItemClient<runtime.Types.Result.GetResult<Prisma.$InboxItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one InboxItem.
   * @param {InboxItemUpdateArgs} args - Arguments to update one InboxItem.
   * @example
   * // Update one InboxItem
   * const inboxItem = await prisma.inboxItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends InboxItemUpdateArgs>(args: Prisma.SelectSubset<T, InboxItemUpdateArgs<ExtArgs>>): Prisma.Prisma__InboxItemClient<runtime.Types.Result.GetResult<Prisma.$InboxItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more InboxItems.
   * @param {InboxItemDeleteManyArgs} args - Arguments to filter InboxItems to delete.
   * @example
   * // Delete a few InboxItems
   * const { count } = await prisma.inboxItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends InboxItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, InboxItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more InboxItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InboxItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many InboxItems
   * const inboxItem = await prisma.inboxItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends InboxItemUpdateManyArgs>(args: Prisma.SelectSubset<T, InboxItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more InboxItems and returns the data updated in the database.
   * @param {InboxItemUpdateManyAndReturnArgs} args - Arguments to update many InboxItems.
   * @example
   * // Update many InboxItems
   * const inboxItem = await prisma.inboxItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more InboxItems and only return the `id`
   * const inboxItemWithIdOnly = await prisma.inboxItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends InboxItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, InboxItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InboxItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one InboxItem.
   * @param {InboxItemUpsertArgs} args - Arguments to update or create a InboxItem.
   * @example
   * // Update or create a InboxItem
   * const inboxItem = await prisma.inboxItem.upsert({
   *   create: {
   *     // ... data to create a InboxItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the InboxItem we want to update
   *   }
   * })
   */
  upsert<T extends InboxItemUpsertArgs>(args: Prisma.SelectSubset<T, InboxItemUpsertArgs<ExtArgs>>): Prisma.Prisma__InboxItemClient<runtime.Types.Result.GetResult<Prisma.$InboxItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of InboxItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InboxItemCountArgs} args - Arguments to filter InboxItems to count.
   * @example
   * // Count the number of InboxItems
   * const count = await prisma.inboxItem.count({
   *   where: {
   *     // ... the filter for the InboxItems we want to count
   *   }
   * })
  **/
  count<T extends InboxItemCountArgs>(
    args?: Prisma.Subset<T, InboxItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], InboxItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a InboxItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InboxItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends InboxItemAggregateArgs>(args: Prisma.Subset<T, InboxItemAggregateArgs>): Prisma.PrismaPromise<GetInboxItemAggregateType<T>>

  /**
   * Group by InboxItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InboxItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends InboxItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: InboxItemGroupByArgs['orderBy'] }
      : { orderBy?: InboxItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, InboxItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetInboxItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the InboxItem model
 */
readonly fields: InboxItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for InboxItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__InboxItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  run<T extends Prisma.InboxItem$runArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.InboxItem$runArgs<ExtArgs>>): Prisma.Prisma__TaskRunClient<runtime.Types.Result.GetResult<Prisma.$TaskRunPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the InboxItem model
 */
export interface InboxItemFieldRefs {
  readonly id: Prisma.FieldRef<"InboxItem", 'String'>
  readonly createdAt: Prisma.FieldRef<"InboxItem", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"InboxItem", 'DateTime'>
  readonly kind: Prisma.FieldRef<"InboxItem", 'String'>
  readonly runId: Prisma.FieldRef<"InboxItem", 'String'>
  readonly taskId: Prisma.FieldRef<"InboxItem", 'String'>
  readonly stepId: Prisma.FieldRef<"InboxItem", 'String'>
  readonly projectId: Prisma.FieldRef<"InboxItem", 'String'>
  readonly title: Prisma.FieldRef<"InboxItem", 'String'>
  readonly context: Prisma.FieldRef<"InboxItem", 'Json'>
  readonly options: Prisma.FieldRef<"InboxItem", 'String[]'>
  readonly status: Prisma.FieldRef<"InboxItem", 'String'>
  readonly answer: Prisma.FieldRef<"InboxItem", 'Json'>
  readonly resolvedBy: Prisma.FieldRef<"InboxItem", 'String'>
  readonly resolvedAt: Prisma.FieldRef<"InboxItem", 'DateTime'>
}
    

// Custom InputTypes
/**
 * InboxItem findUnique
 */
export type InboxItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InboxItem
   */
  select?: Prisma.InboxItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InboxItem
   */
  omit?: Prisma.InboxItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InboxItemInclude<ExtArgs> | null
  /**
   * Filter, which InboxItem to fetch.
   */
  where: Prisma.InboxItemWhereUniqueInput
}

/**
 * InboxItem findUniqueOrThrow
 */
export type InboxItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InboxItem
   */
  select?: Prisma.InboxItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InboxItem
   */
  omit?: Prisma.InboxItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InboxItemInclude<ExtArgs> | null
  /**
   * Filter, which InboxItem to fetch.
   */
  where: Prisma.InboxItemWhereUniqueInput
}

/**
 * InboxItem findFirst
 */
export type InboxItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InboxItem
   */
  select?: Prisma.InboxItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InboxItem
   */
  omit?: Prisma.InboxItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InboxItemInclude<ExtArgs> | null
  /**
   * Filter, which InboxItem to fetch.
   */
  where?: Prisma.InboxItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InboxItems to fetch.
   */
  orderBy?: Prisma.InboxItemOrderByWithRelationInput | Prisma.InboxItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for InboxItems.
   */
  cursor?: Prisma.InboxItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InboxItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InboxItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InboxItems.
   */
  distinct?: Prisma.InboxItemScalarFieldEnum | Prisma.InboxItemScalarFieldEnum[]
}

/**
 * InboxItem findFirstOrThrow
 */
export type InboxItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InboxItem
   */
  select?: Prisma.InboxItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InboxItem
   */
  omit?: Prisma.InboxItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InboxItemInclude<ExtArgs> | null
  /**
   * Filter, which InboxItem to fetch.
   */
  where?: Prisma.InboxItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InboxItems to fetch.
   */
  orderBy?: Prisma.InboxItemOrderByWithRelationInput | Prisma.InboxItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for InboxItems.
   */
  cursor?: Prisma.InboxItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InboxItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InboxItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InboxItems.
   */
  distinct?: Prisma.InboxItemScalarFieldEnum | Prisma.InboxItemScalarFieldEnum[]
}

/**
 * InboxItem findMany
 */
export type InboxItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InboxItem
   */
  select?: Prisma.InboxItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InboxItem
   */
  omit?: Prisma.InboxItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InboxItemInclude<ExtArgs> | null
  /**
   * Filter, which InboxItems to fetch.
   */
  where?: Prisma.InboxItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InboxItems to fetch.
   */
  orderBy?: Prisma.InboxItemOrderByWithRelationInput | Prisma.InboxItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing InboxItems.
   */
  cursor?: Prisma.InboxItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InboxItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InboxItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InboxItems.
   */
  distinct?: Prisma.InboxItemScalarFieldEnum | Prisma.InboxItemScalarFieldEnum[]
}

/**
 * InboxItem create
 */
export type InboxItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InboxItem
   */
  select?: Prisma.InboxItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InboxItem
   */
  omit?: Prisma.InboxItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InboxItemInclude<ExtArgs> | null
  /**
   * The data needed to create a InboxItem.
   */
  data: Prisma.XOR<Prisma.InboxItemCreateInput, Prisma.InboxItemUncheckedCreateInput>
}

/**
 * InboxItem createMany
 */
export type InboxItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many InboxItems.
   */
  data: Prisma.InboxItemCreateManyInput | Prisma.InboxItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * InboxItem createManyAndReturn
 */
export type InboxItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InboxItem
   */
  select?: Prisma.InboxItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the InboxItem
   */
  omit?: Prisma.InboxItemOmit<ExtArgs> | null
  /**
   * The data used to create many InboxItems.
   */
  data: Prisma.InboxItemCreateManyInput | Prisma.InboxItemCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InboxItemIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * InboxItem update
 */
export type InboxItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InboxItem
   */
  select?: Prisma.InboxItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InboxItem
   */
  omit?: Prisma.InboxItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InboxItemInclude<ExtArgs> | null
  /**
   * The data needed to update a InboxItem.
   */
  data: Prisma.XOR<Prisma.InboxItemUpdateInput, Prisma.InboxItemUncheckedUpdateInput>
  /**
   * Choose, which InboxItem to update.
   */
  where: Prisma.InboxItemWhereUniqueInput
}

/**
 * InboxItem updateMany
 */
export type InboxItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update InboxItems.
   */
  data: Prisma.XOR<Prisma.InboxItemUpdateManyMutationInput, Prisma.InboxItemUncheckedUpdateManyInput>
  /**
   * Filter which InboxItems to update
   */
  where?: Prisma.InboxItemWhereInput
  /**
   * Limit how many InboxItems to update.
   */
  limit?: number
}

/**
 * InboxItem updateManyAndReturn
 */
export type InboxItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InboxItem
   */
  select?: Prisma.InboxItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the InboxItem
   */
  omit?: Prisma.InboxItemOmit<ExtArgs> | null
  /**
   * The data used to update InboxItems.
   */
  data: Prisma.XOR<Prisma.InboxItemUpdateManyMutationInput, Prisma.InboxItemUncheckedUpdateManyInput>
  /**
   * Filter which InboxItems to update
   */
  where?: Prisma.InboxItemWhereInput
  /**
   * Limit how many InboxItems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InboxItemIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * InboxItem upsert
 */
export type InboxItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InboxItem
   */
  select?: Prisma.InboxItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InboxItem
   */
  omit?: Prisma.InboxItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InboxItemInclude<ExtArgs> | null
  /**
   * The filter to search for the InboxItem to update in case it exists.
   */
  where: Prisma.InboxItemWhereUniqueInput
  /**
   * In case the InboxItem found by the `where` argument doesn't exist, create a new InboxItem with this data.
   */
  create: Prisma.XOR<Prisma.InboxItemCreateInput, Prisma.InboxItemUncheckedCreateInput>
  /**
   * In case the InboxItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.InboxItemUpdateInput, Prisma.InboxItemUncheckedUpdateInput>
}

/**
 * InboxItem delete
 */
export type InboxItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InboxItem
   */
  select?: Prisma.InboxItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InboxItem
   */
  omit?: Prisma.InboxItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InboxItemInclude<ExtArgs> | null
  /**
   * Filter which InboxItem to delete.
   */
  where: Prisma.InboxItemWhereUniqueInput
}

/**
 * InboxItem deleteMany
 */
export type InboxItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which InboxItems to delete
   */
  where?: Prisma.InboxItemWhereInput
  /**
   * Limit how many InboxItems to delete.
   */
  limit?: number
}

/**
 * InboxItem.run
 */
export type InboxItem$runArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskRun
   */
  select?: Prisma.TaskRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskRun
   */
  omit?: Prisma.TaskRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskRunInclude<ExtArgs> | null
  where?: Prisma.TaskRunWhereInput
}

/**
 * InboxItem without action
 */
export type InboxItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InboxItem
   */
  select?: Prisma.InboxItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InboxItem
   */
  omit?: Prisma.InboxItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InboxItemInclude<ExtArgs> | null
}
