
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RevoRepository` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model RevoRepository
 * 
 */
export type RevoRepositoryModel = runtime.Types.Result.DefaultSelection<Prisma.$RevoRepositoryPayload>

export type AggregateRevoRepository = {
  _count: RevoRepositoryCountAggregateOutputType | null
  _min: RevoRepositoryMinAggregateOutputType | null
  _max: RevoRepositoryMaxAggregateOutputType | null
}

export type RevoRepositoryMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  projectId: string | null
  name: string | null
  remoteUrl: string | null
  localPath: string | null
  defaultBranch: string | null
}

export type RevoRepositoryMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  projectId: string | null
  name: string | null
  remoteUrl: string | null
  localPath: string | null
  defaultBranch: string | null
}

export type RevoRepositoryCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  projectId: number
  name: number
  remoteUrl: number
  localPath: number
  defaultBranch: number
  _all: number
}


export type RevoRepositoryMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  projectId?: true
  name?: true
  remoteUrl?: true
  localPath?: true
  defaultBranch?: true
}

export type RevoRepositoryMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  projectId?: true
  name?: true
  remoteUrl?: true
  localPath?: true
  defaultBranch?: true
}

export type RevoRepositoryCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  projectId?: true
  name?: true
  remoteUrl?: true
  localPath?: true
  defaultBranch?: true
  _all?: true
}

export type RevoRepositoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RevoRepository to aggregate.
   */
  where?: Prisma.RevoRepositoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RevoRepositories to fetch.
   */
  orderBy?: Prisma.RevoRepositoryOrderByWithRelationInput | Prisma.RevoRepositoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RevoRepositoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RevoRepositories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RevoRepositories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RevoRepositories
  **/
  _count?: true | RevoRepositoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RevoRepositoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RevoRepositoryMaxAggregateInputType
}

export type GetRevoRepositoryAggregateType<T extends RevoRepositoryAggregateArgs> = {
      [P in keyof T & keyof AggregateRevoRepository]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRevoRepository[P]>
    : Prisma.GetScalarType<T[P], AggregateRevoRepository[P]>
}




export type RevoRepositoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RevoRepositoryWhereInput
  orderBy?: Prisma.RevoRepositoryOrderByWithAggregationInput | Prisma.RevoRepositoryOrderByWithAggregationInput[]
  by: Prisma.RevoRepositoryScalarFieldEnum[] | Prisma.RevoRepositoryScalarFieldEnum
  having?: Prisma.RevoRepositoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RevoRepositoryCountAggregateInputType | true
  _min?: RevoRepositoryMinAggregateInputType
  _max?: RevoRepositoryMaxAggregateInputType
}

export type RevoRepositoryGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  projectId: string
  name: string
  remoteUrl: string | null
  localPath: string | null
  defaultBranch: string | null
  _count: RevoRepositoryCountAggregateOutputType | null
  _min: RevoRepositoryMinAggregateOutputType | null
  _max: RevoRepositoryMaxAggregateOutputType | null
}

export type GetRevoRepositoryGroupByPayload<T extends RevoRepositoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RevoRepositoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RevoRepositoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RevoRepositoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RevoRepositoryGroupByOutputType[P]>
      }
    >
  >



export type RevoRepositoryWhereInput = {
  AND?: Prisma.RevoRepositoryWhereInput | Prisma.RevoRepositoryWhereInput[]
  OR?: Prisma.RevoRepositoryWhereInput[]
  NOT?: Prisma.RevoRepositoryWhereInput | Prisma.RevoRepositoryWhereInput[]
  id?: Prisma.StringFilter<"RevoRepository"> | string
  createdAt?: Prisma.DateTimeFilter<"RevoRepository"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RevoRepository"> | Date | string
  projectId?: Prisma.StringFilter<"RevoRepository"> | string
  name?: Prisma.StringFilter<"RevoRepository"> | string
  remoteUrl?: Prisma.StringNullableFilter<"RevoRepository"> | string | null
  localPath?: Prisma.StringNullableFilter<"RevoRepository"> | string | null
  defaultBranch?: Prisma.StringNullableFilter<"RevoRepository"> | string | null
  project?: Prisma.XOR<Prisma.RevoProjectScalarRelationFilter, Prisma.RevoProjectWhereInput>
}

export type RevoRepositoryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  remoteUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  localPath?: Prisma.SortOrderInput | Prisma.SortOrder
  defaultBranch?: Prisma.SortOrderInput | Prisma.SortOrder
  project?: Prisma.RevoProjectOrderByWithRelationInput
  _relevance?: Prisma.RevoRepositoryOrderByRelevanceInput
}

export type RevoRepositoryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  projectId_name?: Prisma.RevoRepositoryProjectIdNameCompoundUniqueInput
  AND?: Prisma.RevoRepositoryWhereInput | Prisma.RevoRepositoryWhereInput[]
  OR?: Prisma.RevoRepositoryWhereInput[]
  NOT?: Prisma.RevoRepositoryWhereInput | Prisma.RevoRepositoryWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"RevoRepository"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RevoRepository"> | Date | string
  projectId?: Prisma.StringFilter<"RevoRepository"> | string
  name?: Prisma.StringFilter<"RevoRepository"> | string
  remoteUrl?: Prisma.StringNullableFilter<"RevoRepository"> | string | null
  localPath?: Prisma.StringNullableFilter<"RevoRepository"> | string | null
  defaultBranch?: Prisma.StringNullableFilter<"RevoRepository"> | string | null
  project?: Prisma.XOR<Prisma.RevoProjectScalarRelationFilter, Prisma.RevoProjectWhereInput>
}, "id" | "projectId_name">

export type RevoRepositoryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  remoteUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  localPath?: Prisma.SortOrderInput | Prisma.SortOrder
  defaultBranch?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.RevoRepositoryCountOrderByAggregateInput
  _max?: Prisma.RevoRepositoryMaxOrderByAggregateInput
  _min?: Prisma.RevoRepositoryMinOrderByAggregateInput
}

export type RevoRepositoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.RevoRepositoryScalarWhereWithAggregatesInput | Prisma.RevoRepositoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.RevoRepositoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RevoRepositoryScalarWhereWithAggregatesInput | Prisma.RevoRepositoryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"RevoRepository"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"RevoRepository"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"RevoRepository"> | Date | string
  projectId?: Prisma.StringWithAggregatesFilter<"RevoRepository"> | string
  name?: Prisma.StringWithAggregatesFilter<"RevoRepository"> | string
  remoteUrl?: Prisma.StringNullableWithAggregatesFilter<"RevoRepository"> | string | null
  localPath?: Prisma.StringNullableWithAggregatesFilter<"RevoRepository"> | string | null
  defaultBranch?: Prisma.StringNullableWithAggregatesFilter<"RevoRepository"> | string | null
}

export type RevoRepositoryCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  remoteUrl?: string | null
  localPath?: string | null
  defaultBranch?: string | null
  project: Prisma.RevoProjectCreateNestedOneWithoutRepositoriesInput
}

export type RevoRepositoryUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  projectId: string
  name: string
  remoteUrl?: string | null
  localPath?: string | null
  defaultBranch?: string | null
}

export type RevoRepositoryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  remoteUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  localPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  defaultBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  project?: Prisma.RevoProjectUpdateOneRequiredWithoutRepositoriesNestedInput
}

export type RevoRepositoryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  remoteUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  localPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  defaultBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RevoRepositoryCreateManyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  projectId: string
  name: string
  remoteUrl?: string | null
  localPath?: string | null
  defaultBranch?: string | null
}

export type RevoRepositoryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  remoteUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  localPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  defaultBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RevoRepositoryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  remoteUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  localPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  defaultBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RevoRepositoryListRelationFilter = {
  every?: Prisma.RevoRepositoryWhereInput
  some?: Prisma.RevoRepositoryWhereInput
  none?: Prisma.RevoRepositoryWhereInput
}

export type RevoRepositoryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RevoRepositoryOrderByRelevanceInput = {
  fields: Prisma.RevoRepositoryOrderByRelevanceFieldEnum | Prisma.RevoRepositoryOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type RevoRepositoryProjectIdNameCompoundUniqueInput = {
  projectId: string
  name: string
}

export type RevoRepositoryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  remoteUrl?: Prisma.SortOrder
  localPath?: Prisma.SortOrder
  defaultBranch?: Prisma.SortOrder
}

export type RevoRepositoryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  remoteUrl?: Prisma.SortOrder
  localPath?: Prisma.SortOrder
  defaultBranch?: Prisma.SortOrder
}

export type RevoRepositoryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  remoteUrl?: Prisma.SortOrder
  localPath?: Prisma.SortOrder
  defaultBranch?: Prisma.SortOrder
}

export type RevoRepositoryCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.RevoRepositoryCreateWithoutProjectInput, Prisma.RevoRepositoryUncheckedCreateWithoutProjectInput> | Prisma.RevoRepositoryCreateWithoutProjectInput[] | Prisma.RevoRepositoryUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.RevoRepositoryCreateOrConnectWithoutProjectInput | Prisma.RevoRepositoryCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.RevoRepositoryCreateManyProjectInputEnvelope
  connect?: Prisma.RevoRepositoryWhereUniqueInput | Prisma.RevoRepositoryWhereUniqueInput[]
}

export type RevoRepositoryUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.RevoRepositoryCreateWithoutProjectInput, Prisma.RevoRepositoryUncheckedCreateWithoutProjectInput> | Prisma.RevoRepositoryCreateWithoutProjectInput[] | Prisma.RevoRepositoryUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.RevoRepositoryCreateOrConnectWithoutProjectInput | Prisma.RevoRepositoryCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.RevoRepositoryCreateManyProjectInputEnvelope
  connect?: Prisma.RevoRepositoryWhereUniqueInput | Prisma.RevoRepositoryWhereUniqueInput[]
}

export type RevoRepositoryUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.RevoRepositoryCreateWithoutProjectInput, Prisma.RevoRepositoryUncheckedCreateWithoutProjectInput> | Prisma.RevoRepositoryCreateWithoutProjectInput[] | Prisma.RevoRepositoryUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.RevoRepositoryCreateOrConnectWithoutProjectInput | Prisma.RevoRepositoryCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.RevoRepositoryUpsertWithWhereUniqueWithoutProjectInput | Prisma.RevoRepositoryUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.RevoRepositoryCreateManyProjectInputEnvelope
  set?: Prisma.RevoRepositoryWhereUniqueInput | Prisma.RevoRepositoryWhereUniqueInput[]
  disconnect?: Prisma.RevoRepositoryWhereUniqueInput | Prisma.RevoRepositoryWhereUniqueInput[]
  delete?: Prisma.RevoRepositoryWhereUniqueInput | Prisma.RevoRepositoryWhereUniqueInput[]
  connect?: Prisma.RevoRepositoryWhereUniqueInput | Prisma.RevoRepositoryWhereUniqueInput[]
  update?: Prisma.RevoRepositoryUpdateWithWhereUniqueWithoutProjectInput | Prisma.RevoRepositoryUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.RevoRepositoryUpdateManyWithWhereWithoutProjectInput | Prisma.RevoRepositoryUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.RevoRepositoryScalarWhereInput | Prisma.RevoRepositoryScalarWhereInput[]
}

export type RevoRepositoryUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.RevoRepositoryCreateWithoutProjectInput, Prisma.RevoRepositoryUncheckedCreateWithoutProjectInput> | Prisma.RevoRepositoryCreateWithoutProjectInput[] | Prisma.RevoRepositoryUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.RevoRepositoryCreateOrConnectWithoutProjectInput | Prisma.RevoRepositoryCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.RevoRepositoryUpsertWithWhereUniqueWithoutProjectInput | Prisma.RevoRepositoryUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.RevoRepositoryCreateManyProjectInputEnvelope
  set?: Prisma.RevoRepositoryWhereUniqueInput | Prisma.RevoRepositoryWhereUniqueInput[]
  disconnect?: Prisma.RevoRepositoryWhereUniqueInput | Prisma.RevoRepositoryWhereUniqueInput[]
  delete?: Prisma.RevoRepositoryWhereUniqueInput | Prisma.RevoRepositoryWhereUniqueInput[]
  connect?: Prisma.RevoRepositoryWhereUniqueInput | Prisma.RevoRepositoryWhereUniqueInput[]
  update?: Prisma.RevoRepositoryUpdateWithWhereUniqueWithoutProjectInput | Prisma.RevoRepositoryUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.RevoRepositoryUpdateManyWithWhereWithoutProjectInput | Prisma.RevoRepositoryUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.RevoRepositoryScalarWhereInput | Prisma.RevoRepositoryScalarWhereInput[]
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type RevoRepositoryCreateWithoutProjectInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  remoteUrl?: string | null
  localPath?: string | null
  defaultBranch?: string | null
}

export type RevoRepositoryUncheckedCreateWithoutProjectInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  remoteUrl?: string | null
  localPath?: string | null
  defaultBranch?: string | null
}

export type RevoRepositoryCreateOrConnectWithoutProjectInput = {
  where: Prisma.RevoRepositoryWhereUniqueInput
  create: Prisma.XOR<Prisma.RevoRepositoryCreateWithoutProjectInput, Prisma.RevoRepositoryUncheckedCreateWithoutProjectInput>
}

export type RevoRepositoryCreateManyProjectInputEnvelope = {
  data: Prisma.RevoRepositoryCreateManyProjectInput | Prisma.RevoRepositoryCreateManyProjectInput[]
  skipDuplicates?: boolean
}

export type RevoRepositoryUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.RevoRepositoryWhereUniqueInput
  update: Prisma.XOR<Prisma.RevoRepositoryUpdateWithoutProjectInput, Prisma.RevoRepositoryUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.RevoRepositoryCreateWithoutProjectInput, Prisma.RevoRepositoryUncheckedCreateWithoutProjectInput>
}

export type RevoRepositoryUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.RevoRepositoryWhereUniqueInput
  data: Prisma.XOR<Prisma.RevoRepositoryUpdateWithoutProjectInput, Prisma.RevoRepositoryUncheckedUpdateWithoutProjectInput>
}

export type RevoRepositoryUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.RevoRepositoryScalarWhereInput
  data: Prisma.XOR<Prisma.RevoRepositoryUpdateManyMutationInput, Prisma.RevoRepositoryUncheckedUpdateManyWithoutProjectInput>
}

export type RevoRepositoryScalarWhereInput = {
  AND?: Prisma.RevoRepositoryScalarWhereInput | Prisma.RevoRepositoryScalarWhereInput[]
  OR?: Prisma.RevoRepositoryScalarWhereInput[]
  NOT?: Prisma.RevoRepositoryScalarWhereInput | Prisma.RevoRepositoryScalarWhereInput[]
  id?: Prisma.StringFilter<"RevoRepository"> | string
  createdAt?: Prisma.DateTimeFilter<"RevoRepository"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RevoRepository"> | Date | string
  projectId?: Prisma.StringFilter<"RevoRepository"> | string
  name?: Prisma.StringFilter<"RevoRepository"> | string
  remoteUrl?: Prisma.StringNullableFilter<"RevoRepository"> | string | null
  localPath?: Prisma.StringNullableFilter<"RevoRepository"> | string | null
  defaultBranch?: Prisma.StringNullableFilter<"RevoRepository"> | string | null
}

export type RevoRepositoryCreateManyProjectInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  remoteUrl?: string | null
  localPath?: string | null
  defaultBranch?: string | null
}

export type RevoRepositoryUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  remoteUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  localPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  defaultBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RevoRepositoryUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  remoteUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  localPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  defaultBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RevoRepositoryUncheckedUpdateManyWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  remoteUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  localPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  defaultBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type RevoRepositorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  projectId?: boolean
  name?: boolean
  remoteUrl?: boolean
  localPath?: boolean
  defaultBranch?: boolean
  project?: boolean | Prisma.RevoProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["revoRepository"]>

export type RevoRepositorySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  projectId?: boolean
  name?: boolean
  remoteUrl?: boolean
  localPath?: boolean
  defaultBranch?: boolean
  project?: boolean | Prisma.RevoProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["revoRepository"]>

export type RevoRepositorySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  projectId?: boolean
  name?: boolean
  remoteUrl?: boolean
  localPath?: boolean
  defaultBranch?: boolean
  project?: boolean | Prisma.RevoProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["revoRepository"]>

export type RevoRepositorySelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  projectId?: boolean
  name?: boolean
  remoteUrl?: boolean
  localPath?: boolean
  defaultBranch?: boolean
}

export type RevoRepositoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "projectId" | "name" | "remoteUrl" | "localPath" | "defaultBranch", ExtArgs["result"]["revoRepository"]>
export type RevoRepositoryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.RevoProjectDefaultArgs<ExtArgs>
}
export type RevoRepositoryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.RevoProjectDefaultArgs<ExtArgs>
}
export type RevoRepositoryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.RevoProjectDefaultArgs<ExtArgs>
}

export type $RevoRepositoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RevoRepository"
  objects: {
    project: Prisma.$RevoProjectPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    projectId: string
    name: string
    remoteUrl: string | null
    localPath: string | null
    defaultBranch: string | null
  }, ExtArgs["result"]["revoRepository"]>
  composites: {}
}

export type RevoRepositoryGetPayload<S extends boolean | null | undefined | RevoRepositoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RevoRepositoryPayload, S>

export type RevoRepositoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RevoRepositoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RevoRepositoryCountAggregateInputType | true
  }

export interface RevoRepositoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RevoRepository'], meta: { name: 'RevoRepository' } }
  /**
   * Find zero or one RevoRepository that matches the filter.
   * @param {RevoRepositoryFindUniqueArgs} args - Arguments to find a RevoRepository
   * @example
   * // Get one RevoRepository
   * const revoRepository = await prisma.revoRepository.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RevoRepositoryFindUniqueArgs>(args: Prisma.SelectSubset<T, RevoRepositoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RevoRepositoryClient<runtime.Types.Result.GetResult<Prisma.$RevoRepositoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RevoRepository that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RevoRepositoryFindUniqueOrThrowArgs} args - Arguments to find a RevoRepository
   * @example
   * // Get one RevoRepository
   * const revoRepository = await prisma.revoRepository.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RevoRepositoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RevoRepositoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RevoRepositoryClient<runtime.Types.Result.GetResult<Prisma.$RevoRepositoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RevoRepository that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RevoRepositoryFindFirstArgs} args - Arguments to find a RevoRepository
   * @example
   * // Get one RevoRepository
   * const revoRepository = await prisma.revoRepository.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RevoRepositoryFindFirstArgs>(args?: Prisma.SelectSubset<T, RevoRepositoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__RevoRepositoryClient<runtime.Types.Result.GetResult<Prisma.$RevoRepositoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RevoRepository that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RevoRepositoryFindFirstOrThrowArgs} args - Arguments to find a RevoRepository
   * @example
   * // Get one RevoRepository
   * const revoRepository = await prisma.revoRepository.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RevoRepositoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RevoRepositoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RevoRepositoryClient<runtime.Types.Result.GetResult<Prisma.$RevoRepositoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RevoRepositories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RevoRepositoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RevoRepositories
   * const revoRepositories = await prisma.revoRepository.findMany()
   * 
   * // Get first 10 RevoRepositories
   * const revoRepositories = await prisma.revoRepository.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const revoRepositoryWithIdOnly = await prisma.revoRepository.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RevoRepositoryFindManyArgs>(args?: Prisma.SelectSubset<T, RevoRepositoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RevoRepositoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RevoRepository.
   * @param {RevoRepositoryCreateArgs} args - Arguments to create a RevoRepository.
   * @example
   * // Create one RevoRepository
   * const RevoRepository = await prisma.revoRepository.create({
   *   data: {
   *     // ... data to create a RevoRepository
   *   }
   * })
   * 
   */
  create<T extends RevoRepositoryCreateArgs>(args: Prisma.SelectSubset<T, RevoRepositoryCreateArgs<ExtArgs>>): Prisma.Prisma__RevoRepositoryClient<runtime.Types.Result.GetResult<Prisma.$RevoRepositoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RevoRepositories.
   * @param {RevoRepositoryCreateManyArgs} args - Arguments to create many RevoRepositories.
   * @example
   * // Create many RevoRepositories
   * const revoRepository = await prisma.revoRepository.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RevoRepositoryCreateManyArgs>(args?: Prisma.SelectSubset<T, RevoRepositoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RevoRepositories and returns the data saved in the database.
   * @param {RevoRepositoryCreateManyAndReturnArgs} args - Arguments to create many RevoRepositories.
   * @example
   * // Create many RevoRepositories
   * const revoRepository = await prisma.revoRepository.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RevoRepositories and only return the `id`
   * const revoRepositoryWithIdOnly = await prisma.revoRepository.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RevoRepositoryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RevoRepositoryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RevoRepositoryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RevoRepository.
   * @param {RevoRepositoryDeleteArgs} args - Arguments to delete one RevoRepository.
   * @example
   * // Delete one RevoRepository
   * const RevoRepository = await prisma.revoRepository.delete({
   *   where: {
   *     // ... filter to delete one RevoRepository
   *   }
   * })
   * 
   */
  delete<T extends RevoRepositoryDeleteArgs>(args: Prisma.SelectSubset<T, RevoRepositoryDeleteArgs<ExtArgs>>): Prisma.Prisma__RevoRepositoryClient<runtime.Types.Result.GetResult<Prisma.$RevoRepositoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RevoRepository.
   * @param {RevoRepositoryUpdateArgs} args - Arguments to update one RevoRepository.
   * @example
   * // Update one RevoRepository
   * const revoRepository = await prisma.revoRepository.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RevoRepositoryUpdateArgs>(args: Prisma.SelectSubset<T, RevoRepositoryUpdateArgs<ExtArgs>>): Prisma.Prisma__RevoRepositoryClient<runtime.Types.Result.GetResult<Prisma.$RevoRepositoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RevoRepositories.
   * @param {RevoRepositoryDeleteManyArgs} args - Arguments to filter RevoRepositories to delete.
   * @example
   * // Delete a few RevoRepositories
   * const { count } = await prisma.revoRepository.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RevoRepositoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, RevoRepositoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RevoRepositories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RevoRepositoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RevoRepositories
   * const revoRepository = await prisma.revoRepository.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RevoRepositoryUpdateManyArgs>(args: Prisma.SelectSubset<T, RevoRepositoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RevoRepositories and returns the data updated in the database.
   * @param {RevoRepositoryUpdateManyAndReturnArgs} args - Arguments to update many RevoRepositories.
   * @example
   * // Update many RevoRepositories
   * const revoRepository = await prisma.revoRepository.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RevoRepositories and only return the `id`
   * const revoRepositoryWithIdOnly = await prisma.revoRepository.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RevoRepositoryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RevoRepositoryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RevoRepositoryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RevoRepository.
   * @param {RevoRepositoryUpsertArgs} args - Arguments to update or create a RevoRepository.
   * @example
   * // Update or create a RevoRepository
   * const revoRepository = await prisma.revoRepository.upsert({
   *   create: {
   *     // ... data to create a RevoRepository
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RevoRepository we want to update
   *   }
   * })
   */
  upsert<T extends RevoRepositoryUpsertArgs>(args: Prisma.SelectSubset<T, RevoRepositoryUpsertArgs<ExtArgs>>): Prisma.Prisma__RevoRepositoryClient<runtime.Types.Result.GetResult<Prisma.$RevoRepositoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RevoRepositories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RevoRepositoryCountArgs} args - Arguments to filter RevoRepositories to count.
   * @example
   * // Count the number of RevoRepositories
   * const count = await prisma.revoRepository.count({
   *   where: {
   *     // ... the filter for the RevoRepositories we want to count
   *   }
   * })
  **/
  count<T extends RevoRepositoryCountArgs>(
    args?: Prisma.Subset<T, RevoRepositoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RevoRepositoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RevoRepository.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RevoRepositoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RevoRepositoryAggregateArgs>(args: Prisma.Subset<T, RevoRepositoryAggregateArgs>): Prisma.PrismaPromise<GetRevoRepositoryAggregateType<T>>

  /**
   * Group by RevoRepository.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RevoRepositoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RevoRepositoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RevoRepositoryGroupByArgs['orderBy'] }
      : { orderBy?: RevoRepositoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RevoRepositoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRevoRepositoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RevoRepository model
 */
readonly fields: RevoRepositoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RevoRepository.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RevoRepositoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  project<T extends Prisma.RevoProjectDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RevoProjectDefaultArgs<ExtArgs>>): Prisma.Prisma__RevoProjectClient<runtime.Types.Result.GetResult<Prisma.$RevoProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RevoRepository model
 */
export interface RevoRepositoryFieldRefs {
  readonly id: Prisma.FieldRef<"RevoRepository", 'String'>
  readonly createdAt: Prisma.FieldRef<"RevoRepository", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"RevoRepository", 'DateTime'>
  readonly projectId: Prisma.FieldRef<"RevoRepository", 'String'>
  readonly name: Prisma.FieldRef<"RevoRepository", 'String'>
  readonly remoteUrl: Prisma.FieldRef<"RevoRepository", 'String'>
  readonly localPath: Prisma.FieldRef<"RevoRepository", 'String'>
  readonly defaultBranch: Prisma.FieldRef<"RevoRepository", 'String'>
}
    

// Custom InputTypes
/**
 * RevoRepository findUnique
 */
export type RevoRepositoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevoRepository
   */
  select?: Prisma.RevoRepositorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevoRepository
   */
  omit?: Prisma.RevoRepositoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RevoRepositoryInclude<ExtArgs> | null
  /**
   * Filter, which RevoRepository to fetch.
   */
  where: Prisma.RevoRepositoryWhereUniqueInput
}

/**
 * RevoRepository findUniqueOrThrow
 */
export type RevoRepositoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevoRepository
   */
  select?: Prisma.RevoRepositorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevoRepository
   */
  omit?: Prisma.RevoRepositoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RevoRepositoryInclude<ExtArgs> | null
  /**
   * Filter, which RevoRepository to fetch.
   */
  where: Prisma.RevoRepositoryWhereUniqueInput
}

/**
 * RevoRepository findFirst
 */
export type RevoRepositoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevoRepository
   */
  select?: Prisma.RevoRepositorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevoRepository
   */
  omit?: Prisma.RevoRepositoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RevoRepositoryInclude<ExtArgs> | null
  /**
   * Filter, which RevoRepository to fetch.
   */
  where?: Prisma.RevoRepositoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RevoRepositories to fetch.
   */
  orderBy?: Prisma.RevoRepositoryOrderByWithRelationInput | Prisma.RevoRepositoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RevoRepositories.
   */
  cursor?: Prisma.RevoRepositoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RevoRepositories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RevoRepositories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RevoRepositories.
   */
  distinct?: Prisma.RevoRepositoryScalarFieldEnum | Prisma.RevoRepositoryScalarFieldEnum[]
}

/**
 * RevoRepository findFirstOrThrow
 */
export type RevoRepositoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevoRepository
   */
  select?: Prisma.RevoRepositorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevoRepository
   */
  omit?: Prisma.RevoRepositoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RevoRepositoryInclude<ExtArgs> | null
  /**
   * Filter, which RevoRepository to fetch.
   */
  where?: Prisma.RevoRepositoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RevoRepositories to fetch.
   */
  orderBy?: Prisma.RevoRepositoryOrderByWithRelationInput | Prisma.RevoRepositoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RevoRepositories.
   */
  cursor?: Prisma.RevoRepositoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RevoRepositories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RevoRepositories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RevoRepositories.
   */
  distinct?: Prisma.RevoRepositoryScalarFieldEnum | Prisma.RevoRepositoryScalarFieldEnum[]
}

/**
 * RevoRepository findMany
 */
export type RevoRepositoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevoRepository
   */
  select?: Prisma.RevoRepositorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevoRepository
   */
  omit?: Prisma.RevoRepositoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RevoRepositoryInclude<ExtArgs> | null
  /**
   * Filter, which RevoRepositories to fetch.
   */
  where?: Prisma.RevoRepositoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RevoRepositories to fetch.
   */
  orderBy?: Prisma.RevoRepositoryOrderByWithRelationInput | Prisma.RevoRepositoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RevoRepositories.
   */
  cursor?: Prisma.RevoRepositoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RevoRepositories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RevoRepositories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RevoRepositories.
   */
  distinct?: Prisma.RevoRepositoryScalarFieldEnum | Prisma.RevoRepositoryScalarFieldEnum[]
}

/**
 * RevoRepository create
 */
export type RevoRepositoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevoRepository
   */
  select?: Prisma.RevoRepositorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevoRepository
   */
  omit?: Prisma.RevoRepositoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RevoRepositoryInclude<ExtArgs> | null
  /**
   * The data needed to create a RevoRepository.
   */
  data: Prisma.XOR<Prisma.RevoRepositoryCreateInput, Prisma.RevoRepositoryUncheckedCreateInput>
}

/**
 * RevoRepository createMany
 */
export type RevoRepositoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RevoRepositories.
   */
  data: Prisma.RevoRepositoryCreateManyInput | Prisma.RevoRepositoryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RevoRepository createManyAndReturn
 */
export type RevoRepositoryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevoRepository
   */
  select?: Prisma.RevoRepositorySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RevoRepository
   */
  omit?: Prisma.RevoRepositoryOmit<ExtArgs> | null
  /**
   * The data used to create many RevoRepositories.
   */
  data: Prisma.RevoRepositoryCreateManyInput | Prisma.RevoRepositoryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RevoRepositoryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RevoRepository update
 */
export type RevoRepositoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevoRepository
   */
  select?: Prisma.RevoRepositorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevoRepository
   */
  omit?: Prisma.RevoRepositoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RevoRepositoryInclude<ExtArgs> | null
  /**
   * The data needed to update a RevoRepository.
   */
  data: Prisma.XOR<Prisma.RevoRepositoryUpdateInput, Prisma.RevoRepositoryUncheckedUpdateInput>
  /**
   * Choose, which RevoRepository to update.
   */
  where: Prisma.RevoRepositoryWhereUniqueInput
}

/**
 * RevoRepository updateMany
 */
export type RevoRepositoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RevoRepositories.
   */
  data: Prisma.XOR<Prisma.RevoRepositoryUpdateManyMutationInput, Prisma.RevoRepositoryUncheckedUpdateManyInput>
  /**
   * Filter which RevoRepositories to update
   */
  where?: Prisma.RevoRepositoryWhereInput
  /**
   * Limit how many RevoRepositories to update.
   */
  limit?: number
}

/**
 * RevoRepository updateManyAndReturn
 */
export type RevoRepositoryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevoRepository
   */
  select?: Prisma.RevoRepositorySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RevoRepository
   */
  omit?: Prisma.RevoRepositoryOmit<ExtArgs> | null
  /**
   * The data used to update RevoRepositories.
   */
  data: Prisma.XOR<Prisma.RevoRepositoryUpdateManyMutationInput, Prisma.RevoRepositoryUncheckedUpdateManyInput>
  /**
   * Filter which RevoRepositories to update
   */
  where?: Prisma.RevoRepositoryWhereInput
  /**
   * Limit how many RevoRepositories to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RevoRepositoryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RevoRepository upsert
 */
export type RevoRepositoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevoRepository
   */
  select?: Prisma.RevoRepositorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevoRepository
   */
  omit?: Prisma.RevoRepositoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RevoRepositoryInclude<ExtArgs> | null
  /**
   * The filter to search for the RevoRepository to update in case it exists.
   */
  where: Prisma.RevoRepositoryWhereUniqueInput
  /**
   * In case the RevoRepository found by the `where` argument doesn't exist, create a new RevoRepository with this data.
   */
  create: Prisma.XOR<Prisma.RevoRepositoryCreateInput, Prisma.RevoRepositoryUncheckedCreateInput>
  /**
   * In case the RevoRepository was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RevoRepositoryUpdateInput, Prisma.RevoRepositoryUncheckedUpdateInput>
}

/**
 * RevoRepository delete
 */
export type RevoRepositoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevoRepository
   */
  select?: Prisma.RevoRepositorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevoRepository
   */
  omit?: Prisma.RevoRepositoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RevoRepositoryInclude<ExtArgs> | null
  /**
   * Filter which RevoRepository to delete.
   */
  where: Prisma.RevoRepositoryWhereUniqueInput
}

/**
 * RevoRepository deleteMany
 */
export type RevoRepositoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RevoRepositories to delete
   */
  where?: Prisma.RevoRepositoryWhereInput
  /**
   * Limit how many RevoRepositories to delete.
   */
  limit?: number
}

/**
 * RevoRepository without action
 */
export type RevoRepositoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevoRepository
   */
  select?: Prisma.RevoRepositorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevoRepository
   */
  omit?: Prisma.RevoRepositoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RevoRepositoryInclude<ExtArgs> | null
}
