
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RevoProject` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model RevoProject
 * 
 */
export type RevoProjectModel = runtime.Types.Result.DefaultSelection<Prisma.$RevoProjectPayload>

export type AggregateRevoProject = {
  _count: RevoProjectCountAggregateOutputType | null
  _min: RevoProjectMinAggregateOutputType | null
  _max: RevoProjectMaxAggregateOutputType | null
}

export type RevoProjectMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
  kind: $Enums.RevoProjectKind | null
  name: string | null
  slug: string | null
  status: $Enums.RevoProjectStatus | null
}

export type RevoProjectMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
  kind: $Enums.RevoProjectKind | null
  name: string | null
  slug: string | null
  status: $Enums.RevoProjectStatus | null
}

export type RevoProjectCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  kind: number
  name: number
  slug: number
  status: number
  _all: number
}


export type RevoProjectMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  kind?: true
  name?: true
  slug?: true
  status?: true
}

export type RevoProjectMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  kind?: true
  name?: true
  slug?: true
  status?: true
}

export type RevoProjectCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  kind?: true
  name?: true
  slug?: true
  status?: true
  _all?: true
}

export type RevoProjectAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RevoProject to aggregate.
   */
  where?: Prisma.RevoProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RevoProjects to fetch.
   */
  orderBy?: Prisma.RevoProjectOrderByWithRelationInput | Prisma.RevoProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RevoProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RevoProjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RevoProjects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RevoProjects
  **/
  _count?: true | RevoProjectCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RevoProjectMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RevoProjectMaxAggregateInputType
}

export type GetRevoProjectAggregateType<T extends RevoProjectAggregateArgs> = {
      [P in keyof T & keyof AggregateRevoProject]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRevoProject[P]>
    : Prisma.GetScalarType<T[P], AggregateRevoProject[P]>
}




export type RevoProjectGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RevoProjectWhereInput
  orderBy?: Prisma.RevoProjectOrderByWithAggregationInput | Prisma.RevoProjectOrderByWithAggregationInput[]
  by: Prisma.RevoProjectScalarFieldEnum[] | Prisma.RevoProjectScalarFieldEnum
  having?: Prisma.RevoProjectScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RevoProjectCountAggregateInputType | true
  _min?: RevoProjectMinAggregateInputType
  _max?: RevoProjectMaxAggregateInputType
}

export type RevoProjectGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  kind: $Enums.RevoProjectKind
  name: string
  slug: string
  status: $Enums.RevoProjectStatus
  _count: RevoProjectCountAggregateOutputType | null
  _min: RevoProjectMinAggregateOutputType | null
  _max: RevoProjectMaxAggregateOutputType | null
}

export type GetRevoProjectGroupByPayload<T extends RevoProjectGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RevoProjectGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RevoProjectGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RevoProjectGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RevoProjectGroupByOutputType[P]>
      }
    >
  >



export type RevoProjectWhereInput = {
  AND?: Prisma.RevoProjectWhereInput | Prisma.RevoProjectWhereInput[]
  OR?: Prisma.RevoProjectWhereInput[]
  NOT?: Prisma.RevoProjectWhereInput | Prisma.RevoProjectWhereInput[]
  id?: Prisma.StringFilter<"RevoProject"> | string
  createdAt?: Prisma.DateTimeFilter<"RevoProject"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RevoProject"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"RevoProject"> | Date | string | null
  kind?: Prisma.EnumRevoProjectKindFilter<"RevoProject"> | $Enums.RevoProjectKind
  name?: Prisma.StringFilter<"RevoProject"> | string
  slug?: Prisma.StringFilter<"RevoProject"> | string
  status?: Prisma.EnumRevoProjectStatusFilter<"RevoProject"> | $Enums.RevoProjectStatus
  revisiumBranches?: Prisma.BranchListRelationFilter
}

export type RevoProjectOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  kind?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  status?: Prisma.SortOrder
  revisiumBranches?: Prisma.BranchOrderByRelationAggregateInput
  _relevance?: Prisma.RevoProjectOrderByRelevanceInput
}

export type RevoProjectWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  slug?: string
  AND?: Prisma.RevoProjectWhereInput | Prisma.RevoProjectWhereInput[]
  OR?: Prisma.RevoProjectWhereInput[]
  NOT?: Prisma.RevoProjectWhereInput | Prisma.RevoProjectWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"RevoProject"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RevoProject"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"RevoProject"> | Date | string | null
  kind?: Prisma.EnumRevoProjectKindFilter<"RevoProject"> | $Enums.RevoProjectKind
  name?: Prisma.StringFilter<"RevoProject"> | string
  status?: Prisma.EnumRevoProjectStatusFilter<"RevoProject"> | $Enums.RevoProjectStatus
  revisiumBranches?: Prisma.BranchListRelationFilter
}, "id" | "slug">

export type RevoProjectOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  kind?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  status?: Prisma.SortOrder
  _count?: Prisma.RevoProjectCountOrderByAggregateInput
  _max?: Prisma.RevoProjectMaxOrderByAggregateInput
  _min?: Prisma.RevoProjectMinOrderByAggregateInput
}

export type RevoProjectScalarWhereWithAggregatesInput = {
  AND?: Prisma.RevoProjectScalarWhereWithAggregatesInput | Prisma.RevoProjectScalarWhereWithAggregatesInput[]
  OR?: Prisma.RevoProjectScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RevoProjectScalarWhereWithAggregatesInput | Prisma.RevoProjectScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"RevoProject"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"RevoProject"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"RevoProject"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"RevoProject"> | Date | string | null
  kind?: Prisma.EnumRevoProjectKindWithAggregatesFilter<"RevoProject"> | $Enums.RevoProjectKind
  name?: Prisma.StringWithAggregatesFilter<"RevoProject"> | string
  slug?: Prisma.StringWithAggregatesFilter<"RevoProject"> | string
  status?: Prisma.EnumRevoProjectStatusWithAggregatesFilter<"RevoProject"> | $Enums.RevoProjectStatus
}

export type RevoProjectCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  kind?: $Enums.RevoProjectKind
  name: string
  slug: string
  status?: $Enums.RevoProjectStatus
  revisiumBranches?: Prisma.BranchCreateNestedManyWithoutRevoProjectInput
}

export type RevoProjectUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  kind?: $Enums.RevoProjectKind
  name: string
  slug: string
  status?: $Enums.RevoProjectStatus
  revisiumBranches?: Prisma.BranchUncheckedCreateNestedManyWithoutRevoProjectInput
}

export type RevoProjectUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  kind?: Prisma.EnumRevoProjectKindFieldUpdateOperationsInput | $Enums.RevoProjectKind
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumRevoProjectStatusFieldUpdateOperationsInput | $Enums.RevoProjectStatus
  revisiumBranches?: Prisma.BranchUpdateManyWithoutRevoProjectNestedInput
}

export type RevoProjectUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  kind?: Prisma.EnumRevoProjectKindFieldUpdateOperationsInput | $Enums.RevoProjectKind
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumRevoProjectStatusFieldUpdateOperationsInput | $Enums.RevoProjectStatus
  revisiumBranches?: Prisma.BranchUncheckedUpdateManyWithoutRevoProjectNestedInput
}

export type RevoProjectCreateManyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  kind?: $Enums.RevoProjectKind
  name: string
  slug: string
  status?: $Enums.RevoProjectStatus
}

export type RevoProjectUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  kind?: Prisma.EnumRevoProjectKindFieldUpdateOperationsInput | $Enums.RevoProjectKind
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumRevoProjectStatusFieldUpdateOperationsInput | $Enums.RevoProjectStatus
}

export type RevoProjectUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  kind?: Prisma.EnumRevoProjectKindFieldUpdateOperationsInput | $Enums.RevoProjectKind
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumRevoProjectStatusFieldUpdateOperationsInput | $Enums.RevoProjectStatus
}

export type RevoProjectOrderByRelevanceInput = {
  fields: Prisma.RevoProjectOrderByRelevanceFieldEnum | Prisma.RevoProjectOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type RevoProjectCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type RevoProjectMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type RevoProjectMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type RevoProjectScalarRelationFilter = {
  is?: Prisma.RevoProjectWhereInput
  isNot?: Prisma.RevoProjectWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type EnumRevoProjectKindFieldUpdateOperationsInput = {
  set?: $Enums.RevoProjectKind
}

export type EnumRevoProjectStatusFieldUpdateOperationsInput = {
  set?: $Enums.RevoProjectStatus
}

export type RevoProjectCreateNestedOneWithoutRevisiumBranchesInput = {
  create?: Prisma.XOR<Prisma.RevoProjectCreateWithoutRevisiumBranchesInput, Prisma.RevoProjectUncheckedCreateWithoutRevisiumBranchesInput>
  connectOrCreate?: Prisma.RevoProjectCreateOrConnectWithoutRevisiumBranchesInput
  connect?: Prisma.RevoProjectWhereUniqueInput
}

export type RevoProjectUpdateOneRequiredWithoutRevisiumBranchesNestedInput = {
  create?: Prisma.XOR<Prisma.RevoProjectCreateWithoutRevisiumBranchesInput, Prisma.RevoProjectUncheckedCreateWithoutRevisiumBranchesInput>
  connectOrCreate?: Prisma.RevoProjectCreateOrConnectWithoutRevisiumBranchesInput
  upsert?: Prisma.RevoProjectUpsertWithoutRevisiumBranchesInput
  connect?: Prisma.RevoProjectWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.RevoProjectUpdateToOneWithWhereWithoutRevisiumBranchesInput, Prisma.RevoProjectUpdateWithoutRevisiumBranchesInput>, Prisma.RevoProjectUncheckedUpdateWithoutRevisiumBranchesInput>
}

export type RevoProjectCreateWithoutRevisiumBranchesInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  kind?: $Enums.RevoProjectKind
  name: string
  slug: string
  status?: $Enums.RevoProjectStatus
}

export type RevoProjectUncheckedCreateWithoutRevisiumBranchesInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  kind?: $Enums.RevoProjectKind
  name: string
  slug: string
  status?: $Enums.RevoProjectStatus
}

export type RevoProjectCreateOrConnectWithoutRevisiumBranchesInput = {
  where: Prisma.RevoProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.RevoProjectCreateWithoutRevisiumBranchesInput, Prisma.RevoProjectUncheckedCreateWithoutRevisiumBranchesInput>
}

export type RevoProjectUpsertWithoutRevisiumBranchesInput = {
  update: Prisma.XOR<Prisma.RevoProjectUpdateWithoutRevisiumBranchesInput, Prisma.RevoProjectUncheckedUpdateWithoutRevisiumBranchesInput>
  create: Prisma.XOR<Prisma.RevoProjectCreateWithoutRevisiumBranchesInput, Prisma.RevoProjectUncheckedCreateWithoutRevisiumBranchesInput>
  where?: Prisma.RevoProjectWhereInput
}

export type RevoProjectUpdateToOneWithWhereWithoutRevisiumBranchesInput = {
  where?: Prisma.RevoProjectWhereInput
  data: Prisma.XOR<Prisma.RevoProjectUpdateWithoutRevisiumBranchesInput, Prisma.RevoProjectUncheckedUpdateWithoutRevisiumBranchesInput>
}

export type RevoProjectUpdateWithoutRevisiumBranchesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  kind?: Prisma.EnumRevoProjectKindFieldUpdateOperationsInput | $Enums.RevoProjectKind
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumRevoProjectStatusFieldUpdateOperationsInput | $Enums.RevoProjectStatus
}

export type RevoProjectUncheckedUpdateWithoutRevisiumBranchesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  kind?: Prisma.EnumRevoProjectKindFieldUpdateOperationsInput | $Enums.RevoProjectKind
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumRevoProjectStatusFieldUpdateOperationsInput | $Enums.RevoProjectStatus
}


/**
 * Count Type RevoProjectCountOutputType
 */

export type RevoProjectCountOutputType = {
  revisiumBranches: number
}

export type RevoProjectCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  revisiumBranches?: boolean | RevoProjectCountOutputTypeCountRevisiumBranchesArgs
}

/**
 * RevoProjectCountOutputType without action
 */
export type RevoProjectCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevoProjectCountOutputType
   */
  select?: Prisma.RevoProjectCountOutputTypeSelect<ExtArgs> | null
}

/**
 * RevoProjectCountOutputType without action
 */
export type RevoProjectCountOutputTypeCountRevisiumBranchesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BranchWhereInput
}


export type RevoProjectSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  kind?: boolean
  name?: boolean
  slug?: boolean
  status?: boolean
  revisiumBranches?: boolean | Prisma.RevoProject$revisiumBranchesArgs<ExtArgs>
  _count?: boolean | Prisma.RevoProjectCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["revoProject"]>

export type RevoProjectSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  kind?: boolean
  name?: boolean
  slug?: boolean
  status?: boolean
}, ExtArgs["result"]["revoProject"]>

export type RevoProjectSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  kind?: boolean
  name?: boolean
  slug?: boolean
  status?: boolean
}, ExtArgs["result"]["revoProject"]>

export type RevoProjectSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  kind?: boolean
  name?: boolean
  slug?: boolean
  status?: boolean
}

export type RevoProjectOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "deletedAt" | "kind" | "name" | "slug" | "status", ExtArgs["result"]["revoProject"]>
export type RevoProjectInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  revisiumBranches?: boolean | Prisma.RevoProject$revisiumBranchesArgs<ExtArgs>
  _count?: boolean | Prisma.RevoProjectCountOutputTypeDefaultArgs<ExtArgs>
}
export type RevoProjectIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type RevoProjectIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $RevoProjectPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RevoProject"
  objects: {
    revisiumBranches: Prisma.$BranchPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
    kind: $Enums.RevoProjectKind
    name: string
    slug: string
    status: $Enums.RevoProjectStatus
  }, ExtArgs["result"]["revoProject"]>
  composites: {}
}

export type RevoProjectGetPayload<S extends boolean | null | undefined | RevoProjectDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RevoProjectPayload, S>

export type RevoProjectCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RevoProjectFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RevoProjectCountAggregateInputType | true
  }

export interface RevoProjectDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RevoProject'], meta: { name: 'RevoProject' } }
  /**
   * Find zero or one RevoProject that matches the filter.
   * @param {RevoProjectFindUniqueArgs} args - Arguments to find a RevoProject
   * @example
   * // Get one RevoProject
   * const revoProject = await prisma.revoProject.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RevoProjectFindUniqueArgs>(args: Prisma.SelectSubset<T, RevoProjectFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RevoProjectClient<runtime.Types.Result.GetResult<Prisma.$RevoProjectPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RevoProject that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RevoProjectFindUniqueOrThrowArgs} args - Arguments to find a RevoProject
   * @example
   * // Get one RevoProject
   * const revoProject = await prisma.revoProject.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RevoProjectFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RevoProjectFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RevoProjectClient<runtime.Types.Result.GetResult<Prisma.$RevoProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RevoProject that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RevoProjectFindFirstArgs} args - Arguments to find a RevoProject
   * @example
   * // Get one RevoProject
   * const revoProject = await prisma.revoProject.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RevoProjectFindFirstArgs>(args?: Prisma.SelectSubset<T, RevoProjectFindFirstArgs<ExtArgs>>): Prisma.Prisma__RevoProjectClient<runtime.Types.Result.GetResult<Prisma.$RevoProjectPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RevoProject that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RevoProjectFindFirstOrThrowArgs} args - Arguments to find a RevoProject
   * @example
   * // Get one RevoProject
   * const revoProject = await prisma.revoProject.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RevoProjectFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RevoProjectFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RevoProjectClient<runtime.Types.Result.GetResult<Prisma.$RevoProjectPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RevoProjects that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RevoProjectFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RevoProjects
   * const revoProjects = await prisma.revoProject.findMany()
   * 
   * // Get first 10 RevoProjects
   * const revoProjects = await prisma.revoProject.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const revoProjectWithIdOnly = await prisma.revoProject.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RevoProjectFindManyArgs>(args?: Prisma.SelectSubset<T, RevoProjectFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RevoProjectPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RevoProject.
   * @param {RevoProjectCreateArgs} args - Arguments to create a RevoProject.
   * @example
   * // Create one RevoProject
   * const RevoProject = await prisma.revoProject.create({
   *   data: {
   *     // ... data to create a RevoProject
   *   }
   * })
   * 
   */
  create<T extends RevoProjectCreateArgs>(args: Prisma.SelectSubset<T, RevoProjectCreateArgs<ExtArgs>>): Prisma.Prisma__RevoProjectClient<runtime.Types.Result.GetResult<Prisma.$RevoProjectPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RevoProjects.
   * @param {RevoProjectCreateManyArgs} args - Arguments to create many RevoProjects.
   * @example
   * // Create many RevoProjects
   * const revoProject = await prisma.revoProject.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RevoProjectCreateManyArgs>(args?: Prisma.SelectSubset<T, RevoProjectCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RevoProjects and returns the data saved in the database.
   * @param {RevoProjectCreateManyAndReturnArgs} args - Arguments to create many RevoProjects.
   * @example
   * // Create many RevoProjects
   * const revoProject = await prisma.revoProject.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RevoProjects and only return the `id`
   * const revoProjectWithIdOnly = await prisma.revoProject.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RevoProjectCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RevoProjectCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RevoProjectPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RevoProject.
   * @param {RevoProjectDeleteArgs} args - Arguments to delete one RevoProject.
   * @example
   * // Delete one RevoProject
   * const RevoProject = await prisma.revoProject.delete({
   *   where: {
   *     // ... filter to delete one RevoProject
   *   }
   * })
   * 
   */
  delete<T extends RevoProjectDeleteArgs>(args: Prisma.SelectSubset<T, RevoProjectDeleteArgs<ExtArgs>>): Prisma.Prisma__RevoProjectClient<runtime.Types.Result.GetResult<Prisma.$RevoProjectPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RevoProject.
   * @param {RevoProjectUpdateArgs} args - Arguments to update one RevoProject.
   * @example
   * // Update one RevoProject
   * const revoProject = await prisma.revoProject.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RevoProjectUpdateArgs>(args: Prisma.SelectSubset<T, RevoProjectUpdateArgs<ExtArgs>>): Prisma.Prisma__RevoProjectClient<runtime.Types.Result.GetResult<Prisma.$RevoProjectPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RevoProjects.
   * @param {RevoProjectDeleteManyArgs} args - Arguments to filter RevoProjects to delete.
   * @example
   * // Delete a few RevoProjects
   * const { count } = await prisma.revoProject.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RevoProjectDeleteManyArgs>(args?: Prisma.SelectSubset<T, RevoProjectDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RevoProjects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RevoProjectUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RevoProjects
   * const revoProject = await prisma.revoProject.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RevoProjectUpdateManyArgs>(args: Prisma.SelectSubset<T, RevoProjectUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RevoProjects and returns the data updated in the database.
   * @param {RevoProjectUpdateManyAndReturnArgs} args - Arguments to update many RevoProjects.
   * @example
   * // Update many RevoProjects
   * const revoProject = await prisma.revoProject.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RevoProjects and only return the `id`
   * const revoProjectWithIdOnly = await prisma.revoProject.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RevoProjectUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RevoProjectUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RevoProjectPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RevoProject.
   * @param {RevoProjectUpsertArgs} args - Arguments to update or create a RevoProject.
   * @example
   * // Update or create a RevoProject
   * const revoProject = await prisma.revoProject.upsert({
   *   create: {
   *     // ... data to create a RevoProject
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RevoProject we want to update
   *   }
   * })
   */
  upsert<T extends RevoProjectUpsertArgs>(args: Prisma.SelectSubset<T, RevoProjectUpsertArgs<ExtArgs>>): Prisma.Prisma__RevoProjectClient<runtime.Types.Result.GetResult<Prisma.$RevoProjectPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RevoProjects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RevoProjectCountArgs} args - Arguments to filter RevoProjects to count.
   * @example
   * // Count the number of RevoProjects
   * const count = await prisma.revoProject.count({
   *   where: {
   *     // ... the filter for the RevoProjects we want to count
   *   }
   * })
  **/
  count<T extends RevoProjectCountArgs>(
    args?: Prisma.Subset<T, RevoProjectCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RevoProjectCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RevoProject.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RevoProjectAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RevoProjectAggregateArgs>(args: Prisma.Subset<T, RevoProjectAggregateArgs>): Prisma.PrismaPromise<GetRevoProjectAggregateType<T>>

  /**
   * Group by RevoProject.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RevoProjectGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RevoProjectGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RevoProjectGroupByArgs['orderBy'] }
      : { orderBy?: RevoProjectGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RevoProjectGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRevoProjectGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RevoProject model
 */
readonly fields: RevoProjectFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RevoProject.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RevoProjectClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  revisiumBranches<T extends Prisma.RevoProject$revisiumBranchesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RevoProject$revisiumBranchesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BranchPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RevoProject model
 */
export interface RevoProjectFieldRefs {
  readonly id: Prisma.FieldRef<"RevoProject", 'String'>
  readonly createdAt: Prisma.FieldRef<"RevoProject", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"RevoProject", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"RevoProject", 'DateTime'>
  readonly kind: Prisma.FieldRef<"RevoProject", 'RevoProjectKind'>
  readonly name: Prisma.FieldRef<"RevoProject", 'String'>
  readonly slug: Prisma.FieldRef<"RevoProject", 'String'>
  readonly status: Prisma.FieldRef<"RevoProject", 'RevoProjectStatus'>
}
    

// Custom InputTypes
/**
 * RevoProject findUnique
 */
export type RevoProjectFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevoProject
   */
  select?: Prisma.RevoProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevoProject
   */
  omit?: Prisma.RevoProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RevoProjectInclude<ExtArgs> | null
  /**
   * Filter, which RevoProject to fetch.
   */
  where: Prisma.RevoProjectWhereUniqueInput
}

/**
 * RevoProject findUniqueOrThrow
 */
export type RevoProjectFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevoProject
   */
  select?: Prisma.RevoProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevoProject
   */
  omit?: Prisma.RevoProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RevoProjectInclude<ExtArgs> | null
  /**
   * Filter, which RevoProject to fetch.
   */
  where: Prisma.RevoProjectWhereUniqueInput
}

/**
 * RevoProject findFirst
 */
export type RevoProjectFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevoProject
   */
  select?: Prisma.RevoProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevoProject
   */
  omit?: Prisma.RevoProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RevoProjectInclude<ExtArgs> | null
  /**
   * Filter, which RevoProject to fetch.
   */
  where?: Prisma.RevoProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RevoProjects to fetch.
   */
  orderBy?: Prisma.RevoProjectOrderByWithRelationInput | Prisma.RevoProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RevoProjects.
   */
  cursor?: Prisma.RevoProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RevoProjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RevoProjects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RevoProjects.
   */
  distinct?: Prisma.RevoProjectScalarFieldEnum | Prisma.RevoProjectScalarFieldEnum[]
}

/**
 * RevoProject findFirstOrThrow
 */
export type RevoProjectFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevoProject
   */
  select?: Prisma.RevoProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevoProject
   */
  omit?: Prisma.RevoProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RevoProjectInclude<ExtArgs> | null
  /**
   * Filter, which RevoProject to fetch.
   */
  where?: Prisma.RevoProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RevoProjects to fetch.
   */
  orderBy?: Prisma.RevoProjectOrderByWithRelationInput | Prisma.RevoProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RevoProjects.
   */
  cursor?: Prisma.RevoProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RevoProjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RevoProjects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RevoProjects.
   */
  distinct?: Prisma.RevoProjectScalarFieldEnum | Prisma.RevoProjectScalarFieldEnum[]
}

/**
 * RevoProject findMany
 */
export type RevoProjectFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevoProject
   */
  select?: Prisma.RevoProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevoProject
   */
  omit?: Prisma.RevoProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RevoProjectInclude<ExtArgs> | null
  /**
   * Filter, which RevoProjects to fetch.
   */
  where?: Prisma.RevoProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RevoProjects to fetch.
   */
  orderBy?: Prisma.RevoProjectOrderByWithRelationInput | Prisma.RevoProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RevoProjects.
   */
  cursor?: Prisma.RevoProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RevoProjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RevoProjects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RevoProjects.
   */
  distinct?: Prisma.RevoProjectScalarFieldEnum | Prisma.RevoProjectScalarFieldEnum[]
}

/**
 * RevoProject create
 */
export type RevoProjectCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevoProject
   */
  select?: Prisma.RevoProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevoProject
   */
  omit?: Prisma.RevoProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RevoProjectInclude<ExtArgs> | null
  /**
   * The data needed to create a RevoProject.
   */
  data: Prisma.XOR<Prisma.RevoProjectCreateInput, Prisma.RevoProjectUncheckedCreateInput>
}

/**
 * RevoProject createMany
 */
export type RevoProjectCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RevoProjects.
   */
  data: Prisma.RevoProjectCreateManyInput | Prisma.RevoProjectCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RevoProject createManyAndReturn
 */
export type RevoProjectCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevoProject
   */
  select?: Prisma.RevoProjectSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RevoProject
   */
  omit?: Prisma.RevoProjectOmit<ExtArgs> | null
  /**
   * The data used to create many RevoProjects.
   */
  data: Prisma.RevoProjectCreateManyInput | Prisma.RevoProjectCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RevoProject update
 */
export type RevoProjectUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevoProject
   */
  select?: Prisma.RevoProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevoProject
   */
  omit?: Prisma.RevoProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RevoProjectInclude<ExtArgs> | null
  /**
   * The data needed to update a RevoProject.
   */
  data: Prisma.XOR<Prisma.RevoProjectUpdateInput, Prisma.RevoProjectUncheckedUpdateInput>
  /**
   * Choose, which RevoProject to update.
   */
  where: Prisma.RevoProjectWhereUniqueInput
}

/**
 * RevoProject updateMany
 */
export type RevoProjectUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RevoProjects.
   */
  data: Prisma.XOR<Prisma.RevoProjectUpdateManyMutationInput, Prisma.RevoProjectUncheckedUpdateManyInput>
  /**
   * Filter which RevoProjects to update
   */
  where?: Prisma.RevoProjectWhereInput
  /**
   * Limit how many RevoProjects to update.
   */
  limit?: number
}

/**
 * RevoProject updateManyAndReturn
 */
export type RevoProjectUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevoProject
   */
  select?: Prisma.RevoProjectSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RevoProject
   */
  omit?: Prisma.RevoProjectOmit<ExtArgs> | null
  /**
   * The data used to update RevoProjects.
   */
  data: Prisma.XOR<Prisma.RevoProjectUpdateManyMutationInput, Prisma.RevoProjectUncheckedUpdateManyInput>
  /**
   * Filter which RevoProjects to update
   */
  where?: Prisma.RevoProjectWhereInput
  /**
   * Limit how many RevoProjects to update.
   */
  limit?: number
}

/**
 * RevoProject upsert
 */
export type RevoProjectUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevoProject
   */
  select?: Prisma.RevoProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevoProject
   */
  omit?: Prisma.RevoProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RevoProjectInclude<ExtArgs> | null
  /**
   * The filter to search for the RevoProject to update in case it exists.
   */
  where: Prisma.RevoProjectWhereUniqueInput
  /**
   * In case the RevoProject found by the `where` argument doesn't exist, create a new RevoProject with this data.
   */
  create: Prisma.XOR<Prisma.RevoProjectCreateInput, Prisma.RevoProjectUncheckedCreateInput>
  /**
   * In case the RevoProject was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RevoProjectUpdateInput, Prisma.RevoProjectUncheckedUpdateInput>
}

/**
 * RevoProject delete
 */
export type RevoProjectDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevoProject
   */
  select?: Prisma.RevoProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevoProject
   */
  omit?: Prisma.RevoProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RevoProjectInclude<ExtArgs> | null
  /**
   * Filter which RevoProject to delete.
   */
  where: Prisma.RevoProjectWhereUniqueInput
}

/**
 * RevoProject deleteMany
 */
export type RevoProjectDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RevoProjects to delete
   */
  where?: Prisma.RevoProjectWhereInput
  /**
   * Limit how many RevoProjects to delete.
   */
  limit?: number
}

/**
 * RevoProject.revisiumBranches
 */
export type RevoProject$revisiumBranchesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Branch
   */
  select?: Prisma.BranchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Branch
   */
  omit?: Prisma.BranchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BranchInclude<ExtArgs> | null
  where?: Prisma.BranchWhereInput
  orderBy?: Prisma.BranchOrderByWithRelationInput | Prisma.BranchOrderByWithRelationInput[]
  cursor?: Prisma.BranchWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BranchScalarFieldEnum | Prisma.BranchScalarFieldEnum[]
}

/**
 * RevoProject without action
 */
export type RevoProjectDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevoProject
   */
  select?: Prisma.RevoProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevoProject
   */
  omit?: Prisma.RevoProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RevoProjectInclude<ExtArgs> | null
}
