
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RunOutput` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model RunOutput
 * 
 */
export type RunOutputModel = runtime.Types.Result.DefaultSelection<Prisma.$RunOutputPayload>

export type AggregateRunOutput = {
  _count: RunOutputCountAggregateOutputType | null
  _avg: RunOutputAvgAggregateOutputType | null
  _sum: RunOutputSumAggregateOutputType | null
  _min: RunOutputMinAggregateOutputType | null
  _max: RunOutputMaxAggregateOutputType | null
}

export type RunOutputAvgAggregateOutputType = {
  ordinal: number | null
}

export type RunOutputSumAggregateOutputType = {
  ordinal: number | null
}

export type RunOutputMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  runId: string | null
  nodeId: string | null
  ordinal: number | null
  name: string | null
  schemaRef: string | null
  payloadRef: string | null
  attemptId: string | null
  producedAt: Date | null
}

export type RunOutputMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  runId: string | null
  nodeId: string | null
  ordinal: number | null
  name: string | null
  schemaRef: string | null
  payloadRef: string | null
  attemptId: string | null
  producedAt: Date | null
}

export type RunOutputCountAggregateOutputType = {
  id: number
  createdAt: number
  runId: number
  nodeId: number
  ordinal: number
  name: number
  schemaRef: number
  payload: number
  payloadRef: number
  attemptId: number
  producedAt: number
  _all: number
}


export type RunOutputAvgAggregateInputType = {
  ordinal?: true
}

export type RunOutputSumAggregateInputType = {
  ordinal?: true
}

export type RunOutputMinAggregateInputType = {
  id?: true
  createdAt?: true
  runId?: true
  nodeId?: true
  ordinal?: true
  name?: true
  schemaRef?: true
  payloadRef?: true
  attemptId?: true
  producedAt?: true
}

export type RunOutputMaxAggregateInputType = {
  id?: true
  createdAt?: true
  runId?: true
  nodeId?: true
  ordinal?: true
  name?: true
  schemaRef?: true
  payloadRef?: true
  attemptId?: true
  producedAt?: true
}

export type RunOutputCountAggregateInputType = {
  id?: true
  createdAt?: true
  runId?: true
  nodeId?: true
  ordinal?: true
  name?: true
  schemaRef?: true
  payload?: true
  payloadRef?: true
  attemptId?: true
  producedAt?: true
  _all?: true
}

export type RunOutputAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RunOutput to aggregate.
   */
  where?: Prisma.RunOutputWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RunOutputs to fetch.
   */
  orderBy?: Prisma.RunOutputOrderByWithRelationInput | Prisma.RunOutputOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RunOutputWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RunOutputs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RunOutputs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RunOutputs
  **/
  _count?: true | RunOutputCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RunOutputAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RunOutputSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RunOutputMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RunOutputMaxAggregateInputType
}

export type GetRunOutputAggregateType<T extends RunOutputAggregateArgs> = {
      [P in keyof T & keyof AggregateRunOutput]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRunOutput[P]>
    : Prisma.GetScalarType<T[P], AggregateRunOutput[P]>
}




export type RunOutputGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RunOutputWhereInput
  orderBy?: Prisma.RunOutputOrderByWithAggregationInput | Prisma.RunOutputOrderByWithAggregationInput[]
  by: Prisma.RunOutputScalarFieldEnum[] | Prisma.RunOutputScalarFieldEnum
  having?: Prisma.RunOutputScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RunOutputCountAggregateInputType | true
  _avg?: RunOutputAvgAggregateInputType
  _sum?: RunOutputSumAggregateInputType
  _min?: RunOutputMinAggregateInputType
  _max?: RunOutputMaxAggregateInputType
}

export type RunOutputGroupByOutputType = {
  id: string
  createdAt: Date
  runId: string
  nodeId: string
  ordinal: number
  name: string
  schemaRef: string
  payload: runtime.JsonValue
  payloadRef: string
  attemptId: string
  producedAt: Date
  _count: RunOutputCountAggregateOutputType | null
  _avg: RunOutputAvgAggregateOutputType | null
  _sum: RunOutputSumAggregateOutputType | null
  _min: RunOutputMinAggregateOutputType | null
  _max: RunOutputMaxAggregateOutputType | null
}

export type GetRunOutputGroupByPayload<T extends RunOutputGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RunOutputGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RunOutputGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RunOutputGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RunOutputGroupByOutputType[P]>
      }
    >
  >



export type RunOutputWhereInput = {
  AND?: Prisma.RunOutputWhereInput | Prisma.RunOutputWhereInput[]
  OR?: Prisma.RunOutputWhereInput[]
  NOT?: Prisma.RunOutputWhereInput | Prisma.RunOutputWhereInput[]
  id?: Prisma.StringFilter<"RunOutput"> | string
  createdAt?: Prisma.DateTimeFilter<"RunOutput"> | Date | string
  runId?: Prisma.StringFilter<"RunOutput"> | string
  nodeId?: Prisma.StringFilter<"RunOutput"> | string
  ordinal?: Prisma.IntFilter<"RunOutput"> | number
  name?: Prisma.StringFilter<"RunOutput"> | string
  schemaRef?: Prisma.StringFilter<"RunOutput"> | string
  payload?: Prisma.JsonFilter<"RunOutput">
  payloadRef?: Prisma.StringFilter<"RunOutput"> | string
  attemptId?: Prisma.StringFilter<"RunOutput"> | string
  producedAt?: Prisma.DateTimeFilter<"RunOutput"> | Date | string
  run?: Prisma.XOR<Prisma.TaskRunScalarRelationFilter, Prisma.TaskRunWhereInput>
}

export type RunOutputOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  runId?: Prisma.SortOrder
  nodeId?: Prisma.SortOrder
  ordinal?: Prisma.SortOrder
  name?: Prisma.SortOrder
  schemaRef?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  payloadRef?: Prisma.SortOrder
  attemptId?: Prisma.SortOrder
  producedAt?: Prisma.SortOrder
  run?: Prisma.TaskRunOrderByWithRelationInput
  _relevance?: Prisma.RunOutputOrderByRelevanceInput
}

export type RunOutputWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  runId_nodeId_ordinal?: Prisma.RunOutputRunIdNodeIdOrdinalCompoundUniqueInput
  AND?: Prisma.RunOutputWhereInput | Prisma.RunOutputWhereInput[]
  OR?: Prisma.RunOutputWhereInput[]
  NOT?: Prisma.RunOutputWhereInput | Prisma.RunOutputWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"RunOutput"> | Date | string
  runId?: Prisma.StringFilter<"RunOutput"> | string
  nodeId?: Prisma.StringFilter<"RunOutput"> | string
  ordinal?: Prisma.IntFilter<"RunOutput"> | number
  name?: Prisma.StringFilter<"RunOutput"> | string
  schemaRef?: Prisma.StringFilter<"RunOutput"> | string
  payload?: Prisma.JsonFilter<"RunOutput">
  payloadRef?: Prisma.StringFilter<"RunOutput"> | string
  attemptId?: Prisma.StringFilter<"RunOutput"> | string
  producedAt?: Prisma.DateTimeFilter<"RunOutput"> | Date | string
  run?: Prisma.XOR<Prisma.TaskRunScalarRelationFilter, Prisma.TaskRunWhereInput>
}, "id" | "runId_nodeId_ordinal">

export type RunOutputOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  runId?: Prisma.SortOrder
  nodeId?: Prisma.SortOrder
  ordinal?: Prisma.SortOrder
  name?: Prisma.SortOrder
  schemaRef?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  payloadRef?: Prisma.SortOrder
  attemptId?: Prisma.SortOrder
  producedAt?: Prisma.SortOrder
  _count?: Prisma.RunOutputCountOrderByAggregateInput
  _avg?: Prisma.RunOutputAvgOrderByAggregateInput
  _max?: Prisma.RunOutputMaxOrderByAggregateInput
  _min?: Prisma.RunOutputMinOrderByAggregateInput
  _sum?: Prisma.RunOutputSumOrderByAggregateInput
}

export type RunOutputScalarWhereWithAggregatesInput = {
  AND?: Prisma.RunOutputScalarWhereWithAggregatesInput | Prisma.RunOutputScalarWhereWithAggregatesInput[]
  OR?: Prisma.RunOutputScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RunOutputScalarWhereWithAggregatesInput | Prisma.RunOutputScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"RunOutput"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"RunOutput"> | Date | string
  runId?: Prisma.StringWithAggregatesFilter<"RunOutput"> | string
  nodeId?: Prisma.StringWithAggregatesFilter<"RunOutput"> | string
  ordinal?: Prisma.IntWithAggregatesFilter<"RunOutput"> | number
  name?: Prisma.StringWithAggregatesFilter<"RunOutput"> | string
  schemaRef?: Prisma.StringWithAggregatesFilter<"RunOutput"> | string
  payload?: Prisma.JsonWithAggregatesFilter<"RunOutput">
  payloadRef?: Prisma.StringWithAggregatesFilter<"RunOutput"> | string
  attemptId?: Prisma.StringWithAggregatesFilter<"RunOutput"> | string
  producedAt?: Prisma.DateTimeWithAggregatesFilter<"RunOutput"> | Date | string
}

export type RunOutputCreateInput = {
  id: string
  createdAt?: Date | string
  nodeId: string
  ordinal: number
  name: string
  schemaRef?: string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  payloadRef?: string
  attemptId?: string
  producedAt?: Date | string
  run: Prisma.TaskRunCreateNestedOneWithoutOutputsInput
}

export type RunOutputUncheckedCreateInput = {
  id: string
  createdAt?: Date | string
  runId: string
  nodeId: string
  ordinal: number
  name: string
  schemaRef?: string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  payloadRef?: string
  attemptId?: string
  producedAt?: Date | string
}

export type RunOutputUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nodeId?: Prisma.StringFieldUpdateOperationsInput | string
  ordinal?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  schemaRef?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  payloadRef?: Prisma.StringFieldUpdateOperationsInput | string
  attemptId?: Prisma.StringFieldUpdateOperationsInput | string
  producedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  run?: Prisma.TaskRunUpdateOneRequiredWithoutOutputsNestedInput
}

export type RunOutputUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  runId?: Prisma.StringFieldUpdateOperationsInput | string
  nodeId?: Prisma.StringFieldUpdateOperationsInput | string
  ordinal?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  schemaRef?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  payloadRef?: Prisma.StringFieldUpdateOperationsInput | string
  attemptId?: Prisma.StringFieldUpdateOperationsInput | string
  producedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RunOutputCreateManyInput = {
  id: string
  createdAt?: Date | string
  runId: string
  nodeId: string
  ordinal: number
  name: string
  schemaRef?: string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  payloadRef?: string
  attemptId?: string
  producedAt?: Date | string
}

export type RunOutputUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nodeId?: Prisma.StringFieldUpdateOperationsInput | string
  ordinal?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  schemaRef?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  payloadRef?: Prisma.StringFieldUpdateOperationsInput | string
  attemptId?: Prisma.StringFieldUpdateOperationsInput | string
  producedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RunOutputUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  runId?: Prisma.StringFieldUpdateOperationsInput | string
  nodeId?: Prisma.StringFieldUpdateOperationsInput | string
  ordinal?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  schemaRef?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  payloadRef?: Prisma.StringFieldUpdateOperationsInput | string
  attemptId?: Prisma.StringFieldUpdateOperationsInput | string
  producedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RunOutputListRelationFilter = {
  every?: Prisma.RunOutputWhereInput
  some?: Prisma.RunOutputWhereInput
  none?: Prisma.RunOutputWhereInput
}

export type RunOutputOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RunOutputOrderByRelevanceInput = {
  fields: Prisma.RunOutputOrderByRelevanceFieldEnum | Prisma.RunOutputOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type RunOutputRunIdNodeIdOrdinalCompoundUniqueInput = {
  runId: string
  nodeId: string
  ordinal: number
}

export type RunOutputCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  runId?: Prisma.SortOrder
  nodeId?: Prisma.SortOrder
  ordinal?: Prisma.SortOrder
  name?: Prisma.SortOrder
  schemaRef?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  payloadRef?: Prisma.SortOrder
  attemptId?: Prisma.SortOrder
  producedAt?: Prisma.SortOrder
}

export type RunOutputAvgOrderByAggregateInput = {
  ordinal?: Prisma.SortOrder
}

export type RunOutputMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  runId?: Prisma.SortOrder
  nodeId?: Prisma.SortOrder
  ordinal?: Prisma.SortOrder
  name?: Prisma.SortOrder
  schemaRef?: Prisma.SortOrder
  payloadRef?: Prisma.SortOrder
  attemptId?: Prisma.SortOrder
  producedAt?: Prisma.SortOrder
}

export type RunOutputMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  runId?: Prisma.SortOrder
  nodeId?: Prisma.SortOrder
  ordinal?: Prisma.SortOrder
  name?: Prisma.SortOrder
  schemaRef?: Prisma.SortOrder
  payloadRef?: Prisma.SortOrder
  attemptId?: Prisma.SortOrder
  producedAt?: Prisma.SortOrder
}

export type RunOutputSumOrderByAggregateInput = {
  ordinal?: Prisma.SortOrder
}

export type RunOutputCreateNestedManyWithoutRunInput = {
  create?: Prisma.XOR<Prisma.RunOutputCreateWithoutRunInput, Prisma.RunOutputUncheckedCreateWithoutRunInput> | Prisma.RunOutputCreateWithoutRunInput[] | Prisma.RunOutputUncheckedCreateWithoutRunInput[]
  connectOrCreate?: Prisma.RunOutputCreateOrConnectWithoutRunInput | Prisma.RunOutputCreateOrConnectWithoutRunInput[]
  createMany?: Prisma.RunOutputCreateManyRunInputEnvelope
  connect?: Prisma.RunOutputWhereUniqueInput | Prisma.RunOutputWhereUniqueInput[]
}

export type RunOutputUncheckedCreateNestedManyWithoutRunInput = {
  create?: Prisma.XOR<Prisma.RunOutputCreateWithoutRunInput, Prisma.RunOutputUncheckedCreateWithoutRunInput> | Prisma.RunOutputCreateWithoutRunInput[] | Prisma.RunOutputUncheckedCreateWithoutRunInput[]
  connectOrCreate?: Prisma.RunOutputCreateOrConnectWithoutRunInput | Prisma.RunOutputCreateOrConnectWithoutRunInput[]
  createMany?: Prisma.RunOutputCreateManyRunInputEnvelope
  connect?: Prisma.RunOutputWhereUniqueInput | Prisma.RunOutputWhereUniqueInput[]
}

export type RunOutputUpdateManyWithoutRunNestedInput = {
  create?: Prisma.XOR<Prisma.RunOutputCreateWithoutRunInput, Prisma.RunOutputUncheckedCreateWithoutRunInput> | Prisma.RunOutputCreateWithoutRunInput[] | Prisma.RunOutputUncheckedCreateWithoutRunInput[]
  connectOrCreate?: Prisma.RunOutputCreateOrConnectWithoutRunInput | Prisma.RunOutputCreateOrConnectWithoutRunInput[]
  upsert?: Prisma.RunOutputUpsertWithWhereUniqueWithoutRunInput | Prisma.RunOutputUpsertWithWhereUniqueWithoutRunInput[]
  createMany?: Prisma.RunOutputCreateManyRunInputEnvelope
  set?: Prisma.RunOutputWhereUniqueInput | Prisma.RunOutputWhereUniqueInput[]
  disconnect?: Prisma.RunOutputWhereUniqueInput | Prisma.RunOutputWhereUniqueInput[]
  delete?: Prisma.RunOutputWhereUniqueInput | Prisma.RunOutputWhereUniqueInput[]
  connect?: Prisma.RunOutputWhereUniqueInput | Prisma.RunOutputWhereUniqueInput[]
  update?: Prisma.RunOutputUpdateWithWhereUniqueWithoutRunInput | Prisma.RunOutputUpdateWithWhereUniqueWithoutRunInput[]
  updateMany?: Prisma.RunOutputUpdateManyWithWhereWithoutRunInput | Prisma.RunOutputUpdateManyWithWhereWithoutRunInput[]
  deleteMany?: Prisma.RunOutputScalarWhereInput | Prisma.RunOutputScalarWhereInput[]
}

export type RunOutputUncheckedUpdateManyWithoutRunNestedInput = {
  create?: Prisma.XOR<Prisma.RunOutputCreateWithoutRunInput, Prisma.RunOutputUncheckedCreateWithoutRunInput> | Prisma.RunOutputCreateWithoutRunInput[] | Prisma.RunOutputUncheckedCreateWithoutRunInput[]
  connectOrCreate?: Prisma.RunOutputCreateOrConnectWithoutRunInput | Prisma.RunOutputCreateOrConnectWithoutRunInput[]
  upsert?: Prisma.RunOutputUpsertWithWhereUniqueWithoutRunInput | Prisma.RunOutputUpsertWithWhereUniqueWithoutRunInput[]
  createMany?: Prisma.RunOutputCreateManyRunInputEnvelope
  set?: Prisma.RunOutputWhereUniqueInput | Prisma.RunOutputWhereUniqueInput[]
  disconnect?: Prisma.RunOutputWhereUniqueInput | Prisma.RunOutputWhereUniqueInput[]
  delete?: Prisma.RunOutputWhereUniqueInput | Prisma.RunOutputWhereUniqueInput[]
  connect?: Prisma.RunOutputWhereUniqueInput | Prisma.RunOutputWhereUniqueInput[]
  update?: Prisma.RunOutputUpdateWithWhereUniqueWithoutRunInput | Prisma.RunOutputUpdateWithWhereUniqueWithoutRunInput[]
  updateMany?: Prisma.RunOutputUpdateManyWithWhereWithoutRunInput | Prisma.RunOutputUpdateManyWithWhereWithoutRunInput[]
  deleteMany?: Prisma.RunOutputScalarWhereInput | Prisma.RunOutputScalarWhereInput[]
}

export type RunOutputCreateWithoutRunInput = {
  id: string
  createdAt?: Date | string
  nodeId: string
  ordinal: number
  name: string
  schemaRef?: string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  payloadRef?: string
  attemptId?: string
  producedAt?: Date | string
}

export type RunOutputUncheckedCreateWithoutRunInput = {
  id: string
  createdAt?: Date | string
  nodeId: string
  ordinal: number
  name: string
  schemaRef?: string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  payloadRef?: string
  attemptId?: string
  producedAt?: Date | string
}

export type RunOutputCreateOrConnectWithoutRunInput = {
  where: Prisma.RunOutputWhereUniqueInput
  create: Prisma.XOR<Prisma.RunOutputCreateWithoutRunInput, Prisma.RunOutputUncheckedCreateWithoutRunInput>
}

export type RunOutputCreateManyRunInputEnvelope = {
  data: Prisma.RunOutputCreateManyRunInput | Prisma.RunOutputCreateManyRunInput[]
  skipDuplicates?: boolean
}

export type RunOutputUpsertWithWhereUniqueWithoutRunInput = {
  where: Prisma.RunOutputWhereUniqueInput
  update: Prisma.XOR<Prisma.RunOutputUpdateWithoutRunInput, Prisma.RunOutputUncheckedUpdateWithoutRunInput>
  create: Prisma.XOR<Prisma.RunOutputCreateWithoutRunInput, Prisma.RunOutputUncheckedCreateWithoutRunInput>
}

export type RunOutputUpdateWithWhereUniqueWithoutRunInput = {
  where: Prisma.RunOutputWhereUniqueInput
  data: Prisma.XOR<Prisma.RunOutputUpdateWithoutRunInput, Prisma.RunOutputUncheckedUpdateWithoutRunInput>
}

export type RunOutputUpdateManyWithWhereWithoutRunInput = {
  where: Prisma.RunOutputScalarWhereInput
  data: Prisma.XOR<Prisma.RunOutputUpdateManyMutationInput, Prisma.RunOutputUncheckedUpdateManyWithoutRunInput>
}

export type RunOutputScalarWhereInput = {
  AND?: Prisma.RunOutputScalarWhereInput | Prisma.RunOutputScalarWhereInput[]
  OR?: Prisma.RunOutputScalarWhereInput[]
  NOT?: Prisma.RunOutputScalarWhereInput | Prisma.RunOutputScalarWhereInput[]
  id?: Prisma.StringFilter<"RunOutput"> | string
  createdAt?: Prisma.DateTimeFilter<"RunOutput"> | Date | string
  runId?: Prisma.StringFilter<"RunOutput"> | string
  nodeId?: Prisma.StringFilter<"RunOutput"> | string
  ordinal?: Prisma.IntFilter<"RunOutput"> | number
  name?: Prisma.StringFilter<"RunOutput"> | string
  schemaRef?: Prisma.StringFilter<"RunOutput"> | string
  payload?: Prisma.JsonFilter<"RunOutput">
  payloadRef?: Prisma.StringFilter<"RunOutput"> | string
  attemptId?: Prisma.StringFilter<"RunOutput"> | string
  producedAt?: Prisma.DateTimeFilter<"RunOutput"> | Date | string
}

export type RunOutputCreateManyRunInput = {
  id: string
  createdAt?: Date | string
  nodeId: string
  ordinal: number
  name: string
  schemaRef?: string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  payloadRef?: string
  attemptId?: string
  producedAt?: Date | string
}

export type RunOutputUpdateWithoutRunInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nodeId?: Prisma.StringFieldUpdateOperationsInput | string
  ordinal?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  schemaRef?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  payloadRef?: Prisma.StringFieldUpdateOperationsInput | string
  attemptId?: Prisma.StringFieldUpdateOperationsInput | string
  producedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RunOutputUncheckedUpdateWithoutRunInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nodeId?: Prisma.StringFieldUpdateOperationsInput | string
  ordinal?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  schemaRef?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  payloadRef?: Prisma.StringFieldUpdateOperationsInput | string
  attemptId?: Prisma.StringFieldUpdateOperationsInput | string
  producedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RunOutputUncheckedUpdateManyWithoutRunInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nodeId?: Prisma.StringFieldUpdateOperationsInput | string
  ordinal?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  schemaRef?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  payloadRef?: Prisma.StringFieldUpdateOperationsInput | string
  attemptId?: Prisma.StringFieldUpdateOperationsInput | string
  producedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type RunOutputSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  runId?: boolean
  nodeId?: boolean
  ordinal?: boolean
  name?: boolean
  schemaRef?: boolean
  payload?: boolean
  payloadRef?: boolean
  attemptId?: boolean
  producedAt?: boolean
  run?: boolean | Prisma.TaskRunDefaultArgs<ExtArgs>
}, ExtArgs["result"]["runOutput"]>

export type RunOutputSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  runId?: boolean
  nodeId?: boolean
  ordinal?: boolean
  name?: boolean
  schemaRef?: boolean
  payload?: boolean
  payloadRef?: boolean
  attemptId?: boolean
  producedAt?: boolean
  run?: boolean | Prisma.TaskRunDefaultArgs<ExtArgs>
}, ExtArgs["result"]["runOutput"]>

export type RunOutputSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  runId?: boolean
  nodeId?: boolean
  ordinal?: boolean
  name?: boolean
  schemaRef?: boolean
  payload?: boolean
  payloadRef?: boolean
  attemptId?: boolean
  producedAt?: boolean
  run?: boolean | Prisma.TaskRunDefaultArgs<ExtArgs>
}, ExtArgs["result"]["runOutput"]>

export type RunOutputSelectScalar = {
  id?: boolean
  createdAt?: boolean
  runId?: boolean
  nodeId?: boolean
  ordinal?: boolean
  name?: boolean
  schemaRef?: boolean
  payload?: boolean
  payloadRef?: boolean
  attemptId?: boolean
  producedAt?: boolean
}

export type RunOutputOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "runId" | "nodeId" | "ordinal" | "name" | "schemaRef" | "payload" | "payloadRef" | "attemptId" | "producedAt", ExtArgs["result"]["runOutput"]>
export type RunOutputInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  run?: boolean | Prisma.TaskRunDefaultArgs<ExtArgs>
}
export type RunOutputIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  run?: boolean | Prisma.TaskRunDefaultArgs<ExtArgs>
}
export type RunOutputIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  run?: boolean | Prisma.TaskRunDefaultArgs<ExtArgs>
}

export type $RunOutputPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RunOutput"
  objects: {
    run: Prisma.$TaskRunPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    runId: string
    nodeId: string
    ordinal: number
    name: string
    schemaRef: string
    payload: runtime.JsonValue
    payloadRef: string
    attemptId: string
    producedAt: Date
  }, ExtArgs["result"]["runOutput"]>
  composites: {}
}

export type RunOutputGetPayload<S extends boolean | null | undefined | RunOutputDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RunOutputPayload, S>

export type RunOutputCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RunOutputFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RunOutputCountAggregateInputType | true
  }

export interface RunOutputDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RunOutput'], meta: { name: 'RunOutput' } }
  /**
   * Find zero or one RunOutput that matches the filter.
   * @param {RunOutputFindUniqueArgs} args - Arguments to find a RunOutput
   * @example
   * // Get one RunOutput
   * const runOutput = await prisma.runOutput.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RunOutputFindUniqueArgs>(args: Prisma.SelectSubset<T, RunOutputFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RunOutputClient<runtime.Types.Result.GetResult<Prisma.$RunOutputPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RunOutput that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RunOutputFindUniqueOrThrowArgs} args - Arguments to find a RunOutput
   * @example
   * // Get one RunOutput
   * const runOutput = await prisma.runOutput.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RunOutputFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RunOutputFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RunOutputClient<runtime.Types.Result.GetResult<Prisma.$RunOutputPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RunOutput that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RunOutputFindFirstArgs} args - Arguments to find a RunOutput
   * @example
   * // Get one RunOutput
   * const runOutput = await prisma.runOutput.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RunOutputFindFirstArgs>(args?: Prisma.SelectSubset<T, RunOutputFindFirstArgs<ExtArgs>>): Prisma.Prisma__RunOutputClient<runtime.Types.Result.GetResult<Prisma.$RunOutputPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RunOutput that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RunOutputFindFirstOrThrowArgs} args - Arguments to find a RunOutput
   * @example
   * // Get one RunOutput
   * const runOutput = await prisma.runOutput.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RunOutputFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RunOutputFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RunOutputClient<runtime.Types.Result.GetResult<Prisma.$RunOutputPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RunOutputs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RunOutputFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RunOutputs
   * const runOutputs = await prisma.runOutput.findMany()
   * 
   * // Get first 10 RunOutputs
   * const runOutputs = await prisma.runOutput.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const runOutputWithIdOnly = await prisma.runOutput.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RunOutputFindManyArgs>(args?: Prisma.SelectSubset<T, RunOutputFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RunOutputPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RunOutput.
   * @param {RunOutputCreateArgs} args - Arguments to create a RunOutput.
   * @example
   * // Create one RunOutput
   * const RunOutput = await prisma.runOutput.create({
   *   data: {
   *     // ... data to create a RunOutput
   *   }
   * })
   * 
   */
  create<T extends RunOutputCreateArgs>(args: Prisma.SelectSubset<T, RunOutputCreateArgs<ExtArgs>>): Prisma.Prisma__RunOutputClient<runtime.Types.Result.GetResult<Prisma.$RunOutputPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RunOutputs.
   * @param {RunOutputCreateManyArgs} args - Arguments to create many RunOutputs.
   * @example
   * // Create many RunOutputs
   * const runOutput = await prisma.runOutput.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RunOutputCreateManyArgs>(args?: Prisma.SelectSubset<T, RunOutputCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RunOutputs and returns the data saved in the database.
   * @param {RunOutputCreateManyAndReturnArgs} args - Arguments to create many RunOutputs.
   * @example
   * // Create many RunOutputs
   * const runOutput = await prisma.runOutput.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RunOutputs and only return the `id`
   * const runOutputWithIdOnly = await prisma.runOutput.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RunOutputCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RunOutputCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RunOutputPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RunOutput.
   * @param {RunOutputDeleteArgs} args - Arguments to delete one RunOutput.
   * @example
   * // Delete one RunOutput
   * const RunOutput = await prisma.runOutput.delete({
   *   where: {
   *     // ... filter to delete one RunOutput
   *   }
   * })
   * 
   */
  delete<T extends RunOutputDeleteArgs>(args: Prisma.SelectSubset<T, RunOutputDeleteArgs<ExtArgs>>): Prisma.Prisma__RunOutputClient<runtime.Types.Result.GetResult<Prisma.$RunOutputPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RunOutput.
   * @param {RunOutputUpdateArgs} args - Arguments to update one RunOutput.
   * @example
   * // Update one RunOutput
   * const runOutput = await prisma.runOutput.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RunOutputUpdateArgs>(args: Prisma.SelectSubset<T, RunOutputUpdateArgs<ExtArgs>>): Prisma.Prisma__RunOutputClient<runtime.Types.Result.GetResult<Prisma.$RunOutputPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RunOutputs.
   * @param {RunOutputDeleteManyArgs} args - Arguments to filter RunOutputs to delete.
   * @example
   * // Delete a few RunOutputs
   * const { count } = await prisma.runOutput.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RunOutputDeleteManyArgs>(args?: Prisma.SelectSubset<T, RunOutputDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RunOutputs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RunOutputUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RunOutputs
   * const runOutput = await prisma.runOutput.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RunOutputUpdateManyArgs>(args: Prisma.SelectSubset<T, RunOutputUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RunOutputs and returns the data updated in the database.
   * @param {RunOutputUpdateManyAndReturnArgs} args - Arguments to update many RunOutputs.
   * @example
   * // Update many RunOutputs
   * const runOutput = await prisma.runOutput.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RunOutputs and only return the `id`
   * const runOutputWithIdOnly = await prisma.runOutput.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RunOutputUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RunOutputUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RunOutputPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RunOutput.
   * @param {RunOutputUpsertArgs} args - Arguments to update or create a RunOutput.
   * @example
   * // Update or create a RunOutput
   * const runOutput = await prisma.runOutput.upsert({
   *   create: {
   *     // ... data to create a RunOutput
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RunOutput we want to update
   *   }
   * })
   */
  upsert<T extends RunOutputUpsertArgs>(args: Prisma.SelectSubset<T, RunOutputUpsertArgs<ExtArgs>>): Prisma.Prisma__RunOutputClient<runtime.Types.Result.GetResult<Prisma.$RunOutputPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RunOutputs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RunOutputCountArgs} args - Arguments to filter RunOutputs to count.
   * @example
   * // Count the number of RunOutputs
   * const count = await prisma.runOutput.count({
   *   where: {
   *     // ... the filter for the RunOutputs we want to count
   *   }
   * })
  **/
  count<T extends RunOutputCountArgs>(
    args?: Prisma.Subset<T, RunOutputCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RunOutputCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RunOutput.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RunOutputAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RunOutputAggregateArgs>(args: Prisma.Subset<T, RunOutputAggregateArgs>): Prisma.PrismaPromise<GetRunOutputAggregateType<T>>

  /**
   * Group by RunOutput.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RunOutputGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RunOutputGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RunOutputGroupByArgs['orderBy'] }
      : { orderBy?: RunOutputGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RunOutputGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRunOutputGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RunOutput model
 */
readonly fields: RunOutputFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RunOutput.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RunOutputClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  run<T extends Prisma.TaskRunDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TaskRunDefaultArgs<ExtArgs>>): Prisma.Prisma__TaskRunClient<runtime.Types.Result.GetResult<Prisma.$TaskRunPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RunOutput model
 */
export interface RunOutputFieldRefs {
  readonly id: Prisma.FieldRef<"RunOutput", 'String'>
  readonly createdAt: Prisma.FieldRef<"RunOutput", 'DateTime'>
  readonly runId: Prisma.FieldRef<"RunOutput", 'String'>
  readonly nodeId: Prisma.FieldRef<"RunOutput", 'String'>
  readonly ordinal: Prisma.FieldRef<"RunOutput", 'Int'>
  readonly name: Prisma.FieldRef<"RunOutput", 'String'>
  readonly schemaRef: Prisma.FieldRef<"RunOutput", 'String'>
  readonly payload: Prisma.FieldRef<"RunOutput", 'Json'>
  readonly payloadRef: Prisma.FieldRef<"RunOutput", 'String'>
  readonly attemptId: Prisma.FieldRef<"RunOutput", 'String'>
  readonly producedAt: Prisma.FieldRef<"RunOutput", 'DateTime'>
}
    

// Custom InputTypes
/**
 * RunOutput findUnique
 */
export type RunOutputFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RunOutput
   */
  select?: Prisma.RunOutputSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RunOutput
   */
  omit?: Prisma.RunOutputOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunOutputInclude<ExtArgs> | null
  /**
   * Filter, which RunOutput to fetch.
   */
  where: Prisma.RunOutputWhereUniqueInput
}

/**
 * RunOutput findUniqueOrThrow
 */
export type RunOutputFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RunOutput
   */
  select?: Prisma.RunOutputSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RunOutput
   */
  omit?: Prisma.RunOutputOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunOutputInclude<ExtArgs> | null
  /**
   * Filter, which RunOutput to fetch.
   */
  where: Prisma.RunOutputWhereUniqueInput
}

/**
 * RunOutput findFirst
 */
export type RunOutputFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RunOutput
   */
  select?: Prisma.RunOutputSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RunOutput
   */
  omit?: Prisma.RunOutputOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunOutputInclude<ExtArgs> | null
  /**
   * Filter, which RunOutput to fetch.
   */
  where?: Prisma.RunOutputWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RunOutputs to fetch.
   */
  orderBy?: Prisma.RunOutputOrderByWithRelationInput | Prisma.RunOutputOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RunOutputs.
   */
  cursor?: Prisma.RunOutputWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RunOutputs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RunOutputs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RunOutputs.
   */
  distinct?: Prisma.RunOutputScalarFieldEnum | Prisma.RunOutputScalarFieldEnum[]
}

/**
 * RunOutput findFirstOrThrow
 */
export type RunOutputFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RunOutput
   */
  select?: Prisma.RunOutputSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RunOutput
   */
  omit?: Prisma.RunOutputOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunOutputInclude<ExtArgs> | null
  /**
   * Filter, which RunOutput to fetch.
   */
  where?: Prisma.RunOutputWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RunOutputs to fetch.
   */
  orderBy?: Prisma.RunOutputOrderByWithRelationInput | Prisma.RunOutputOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RunOutputs.
   */
  cursor?: Prisma.RunOutputWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RunOutputs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RunOutputs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RunOutputs.
   */
  distinct?: Prisma.RunOutputScalarFieldEnum | Prisma.RunOutputScalarFieldEnum[]
}

/**
 * RunOutput findMany
 */
export type RunOutputFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RunOutput
   */
  select?: Prisma.RunOutputSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RunOutput
   */
  omit?: Prisma.RunOutputOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunOutputInclude<ExtArgs> | null
  /**
   * Filter, which RunOutputs to fetch.
   */
  where?: Prisma.RunOutputWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RunOutputs to fetch.
   */
  orderBy?: Prisma.RunOutputOrderByWithRelationInput | Prisma.RunOutputOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RunOutputs.
   */
  cursor?: Prisma.RunOutputWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RunOutputs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RunOutputs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RunOutputs.
   */
  distinct?: Prisma.RunOutputScalarFieldEnum | Prisma.RunOutputScalarFieldEnum[]
}

/**
 * RunOutput create
 */
export type RunOutputCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RunOutput
   */
  select?: Prisma.RunOutputSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RunOutput
   */
  omit?: Prisma.RunOutputOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunOutputInclude<ExtArgs> | null
  /**
   * The data needed to create a RunOutput.
   */
  data: Prisma.XOR<Prisma.RunOutputCreateInput, Prisma.RunOutputUncheckedCreateInput>
}

/**
 * RunOutput createMany
 */
export type RunOutputCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RunOutputs.
   */
  data: Prisma.RunOutputCreateManyInput | Prisma.RunOutputCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RunOutput createManyAndReturn
 */
export type RunOutputCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RunOutput
   */
  select?: Prisma.RunOutputSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RunOutput
   */
  omit?: Prisma.RunOutputOmit<ExtArgs> | null
  /**
   * The data used to create many RunOutputs.
   */
  data: Prisma.RunOutputCreateManyInput | Prisma.RunOutputCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunOutputIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RunOutput update
 */
export type RunOutputUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RunOutput
   */
  select?: Prisma.RunOutputSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RunOutput
   */
  omit?: Prisma.RunOutputOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunOutputInclude<ExtArgs> | null
  /**
   * The data needed to update a RunOutput.
   */
  data: Prisma.XOR<Prisma.RunOutputUpdateInput, Prisma.RunOutputUncheckedUpdateInput>
  /**
   * Choose, which RunOutput to update.
   */
  where: Prisma.RunOutputWhereUniqueInput
}

/**
 * RunOutput updateMany
 */
export type RunOutputUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RunOutputs.
   */
  data: Prisma.XOR<Prisma.RunOutputUpdateManyMutationInput, Prisma.RunOutputUncheckedUpdateManyInput>
  /**
   * Filter which RunOutputs to update
   */
  where?: Prisma.RunOutputWhereInput
  /**
   * Limit how many RunOutputs to update.
   */
  limit?: number
}

/**
 * RunOutput updateManyAndReturn
 */
export type RunOutputUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RunOutput
   */
  select?: Prisma.RunOutputSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RunOutput
   */
  omit?: Prisma.RunOutputOmit<ExtArgs> | null
  /**
   * The data used to update RunOutputs.
   */
  data: Prisma.XOR<Prisma.RunOutputUpdateManyMutationInput, Prisma.RunOutputUncheckedUpdateManyInput>
  /**
   * Filter which RunOutputs to update
   */
  where?: Prisma.RunOutputWhereInput
  /**
   * Limit how many RunOutputs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunOutputIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RunOutput upsert
 */
export type RunOutputUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RunOutput
   */
  select?: Prisma.RunOutputSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RunOutput
   */
  omit?: Prisma.RunOutputOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunOutputInclude<ExtArgs> | null
  /**
   * The filter to search for the RunOutput to update in case it exists.
   */
  where: Prisma.RunOutputWhereUniqueInput
  /**
   * In case the RunOutput found by the `where` argument doesn't exist, create a new RunOutput with this data.
   */
  create: Prisma.XOR<Prisma.RunOutputCreateInput, Prisma.RunOutputUncheckedCreateInput>
  /**
   * In case the RunOutput was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RunOutputUpdateInput, Prisma.RunOutputUncheckedUpdateInput>
}

/**
 * RunOutput delete
 */
export type RunOutputDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RunOutput
   */
  select?: Prisma.RunOutputSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RunOutput
   */
  omit?: Prisma.RunOutputOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunOutputInclude<ExtArgs> | null
  /**
   * Filter which RunOutput to delete.
   */
  where: Prisma.RunOutputWhereUniqueInput
}

/**
 * RunOutput deleteMany
 */
export type RunOutputDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RunOutputs to delete
   */
  where?: Prisma.RunOutputWhereInput
  /**
   * Limit how many RunOutputs to delete.
   */
  limit?: number
}

/**
 * RunOutput without action
 */
export type RunOutputDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RunOutput
   */
  select?: Prisma.RunOutputSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RunOutput
   */
  omit?: Prisma.RunOutputOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunOutputInclude<ExtArgs> | null
}
