
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RunTask` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model RunTask
 * 
 */
export type RunTaskModel = runtime.Types.Result.DefaultSelection<Prisma.$RunTaskPayload>

export type AggregateRunTask = {
  _count: RunTaskCountAggregateOutputType | null
  _avg: RunTaskAvgAggregateOutputType | null
  _sum: RunTaskSumAggregateOutputType | null
  _min: RunTaskMinAggregateOutputType | null
  _max: RunTaskMaxAggregateOutputType | null
}

export type RunTaskAvgAggregateOutputType = {
  priority: number | null
}

export type RunTaskSumAggregateOutputType = {
  priority: number | null
}

export type RunTaskMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  runId: string | null
  repoRef: string | null
  roleHint: string | null
  title: string | null
  status: string | null
  scope: string | null
  priority: number | null
}

export type RunTaskMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  runId: string | null
  repoRef: string | null
  roleHint: string | null
  title: string | null
  status: string | null
  scope: string | null
  priority: number | null
}

export type RunTaskCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  runId: number
  repoRef: number
  roleHint: number
  title: number
  status: number
  dependsOn: number
  scope: number
  priority: number
  _all: number
}


export type RunTaskAvgAggregateInputType = {
  priority?: true
}

export type RunTaskSumAggregateInputType = {
  priority?: true
}

export type RunTaskMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  runId?: true
  repoRef?: true
  roleHint?: true
  title?: true
  status?: true
  scope?: true
  priority?: true
}

export type RunTaskMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  runId?: true
  repoRef?: true
  roleHint?: true
  title?: true
  status?: true
  scope?: true
  priority?: true
}

export type RunTaskCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  runId?: true
  repoRef?: true
  roleHint?: true
  title?: true
  status?: true
  dependsOn?: true
  scope?: true
  priority?: true
  _all?: true
}

export type RunTaskAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RunTask to aggregate.
   */
  where?: Prisma.RunTaskWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RunTasks to fetch.
   */
  orderBy?: Prisma.RunTaskOrderByWithRelationInput | Prisma.RunTaskOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RunTaskWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RunTasks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RunTasks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RunTasks
  **/
  _count?: true | RunTaskCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RunTaskAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RunTaskSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RunTaskMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RunTaskMaxAggregateInputType
}

export type GetRunTaskAggregateType<T extends RunTaskAggregateArgs> = {
      [P in keyof T & keyof AggregateRunTask]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRunTask[P]>
    : Prisma.GetScalarType<T[P], AggregateRunTask[P]>
}




export type RunTaskGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RunTaskWhereInput
  orderBy?: Prisma.RunTaskOrderByWithAggregationInput | Prisma.RunTaskOrderByWithAggregationInput[]
  by: Prisma.RunTaskScalarFieldEnum[] | Prisma.RunTaskScalarFieldEnum
  having?: Prisma.RunTaskScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RunTaskCountAggregateInputType | true
  _avg?: RunTaskAvgAggregateInputType
  _sum?: RunTaskSumAggregateInputType
  _min?: RunTaskMinAggregateInputType
  _max?: RunTaskMaxAggregateInputType
}

export type RunTaskGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  runId: string
  repoRef: string
  roleHint: string
  title: string
  status: string
  dependsOn: string[]
  scope: string
  priority: number
  _count: RunTaskCountAggregateOutputType | null
  _avg: RunTaskAvgAggregateOutputType | null
  _sum: RunTaskSumAggregateOutputType | null
  _min: RunTaskMinAggregateOutputType | null
  _max: RunTaskMaxAggregateOutputType | null
}

export type GetRunTaskGroupByPayload<T extends RunTaskGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RunTaskGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RunTaskGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RunTaskGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RunTaskGroupByOutputType[P]>
      }
    >
  >



export type RunTaskWhereInput = {
  AND?: Prisma.RunTaskWhereInput | Prisma.RunTaskWhereInput[]
  OR?: Prisma.RunTaskWhereInput[]
  NOT?: Prisma.RunTaskWhereInput | Prisma.RunTaskWhereInput[]
  id?: Prisma.StringFilter<"RunTask"> | string
  createdAt?: Prisma.DateTimeFilter<"RunTask"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RunTask"> | Date | string
  runId?: Prisma.StringFilter<"RunTask"> | string
  repoRef?: Prisma.StringFilter<"RunTask"> | string
  roleHint?: Prisma.StringFilter<"RunTask"> | string
  title?: Prisma.StringFilter<"RunTask"> | string
  status?: Prisma.StringFilter<"RunTask"> | string
  dependsOn?: Prisma.StringNullableListFilter<"RunTask">
  scope?: Prisma.StringFilter<"RunTask"> | string
  priority?: Prisma.IntFilter<"RunTask"> | number
  run?: Prisma.XOR<Prisma.TaskRunScalarRelationFilter, Prisma.TaskRunWhereInput>
}

export type RunTaskOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  runId?: Prisma.SortOrder
  repoRef?: Prisma.SortOrder
  roleHint?: Prisma.SortOrder
  title?: Prisma.SortOrder
  status?: Prisma.SortOrder
  dependsOn?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  run?: Prisma.TaskRunOrderByWithRelationInput
  _relevance?: Prisma.RunTaskOrderByRelevanceInput
}

export type RunTaskWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.RunTaskWhereInput | Prisma.RunTaskWhereInput[]
  OR?: Prisma.RunTaskWhereInput[]
  NOT?: Prisma.RunTaskWhereInput | Prisma.RunTaskWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"RunTask"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RunTask"> | Date | string
  runId?: Prisma.StringFilter<"RunTask"> | string
  repoRef?: Prisma.StringFilter<"RunTask"> | string
  roleHint?: Prisma.StringFilter<"RunTask"> | string
  title?: Prisma.StringFilter<"RunTask"> | string
  status?: Prisma.StringFilter<"RunTask"> | string
  dependsOn?: Prisma.StringNullableListFilter<"RunTask">
  scope?: Prisma.StringFilter<"RunTask"> | string
  priority?: Prisma.IntFilter<"RunTask"> | number
  run?: Prisma.XOR<Prisma.TaskRunScalarRelationFilter, Prisma.TaskRunWhereInput>
}, "id">

export type RunTaskOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  runId?: Prisma.SortOrder
  repoRef?: Prisma.SortOrder
  roleHint?: Prisma.SortOrder
  title?: Prisma.SortOrder
  status?: Prisma.SortOrder
  dependsOn?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  _count?: Prisma.RunTaskCountOrderByAggregateInput
  _avg?: Prisma.RunTaskAvgOrderByAggregateInput
  _max?: Prisma.RunTaskMaxOrderByAggregateInput
  _min?: Prisma.RunTaskMinOrderByAggregateInput
  _sum?: Prisma.RunTaskSumOrderByAggregateInput
}

export type RunTaskScalarWhereWithAggregatesInput = {
  AND?: Prisma.RunTaskScalarWhereWithAggregatesInput | Prisma.RunTaskScalarWhereWithAggregatesInput[]
  OR?: Prisma.RunTaskScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RunTaskScalarWhereWithAggregatesInput | Prisma.RunTaskScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"RunTask"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"RunTask"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"RunTask"> | Date | string
  runId?: Prisma.StringWithAggregatesFilter<"RunTask"> | string
  repoRef?: Prisma.StringWithAggregatesFilter<"RunTask"> | string
  roleHint?: Prisma.StringWithAggregatesFilter<"RunTask"> | string
  title?: Prisma.StringWithAggregatesFilter<"RunTask"> | string
  status?: Prisma.StringWithAggregatesFilter<"RunTask"> | string
  dependsOn?: Prisma.StringNullableListFilter<"RunTask">
  scope?: Prisma.StringWithAggregatesFilter<"RunTask"> | string
  priority?: Prisma.IntWithAggregatesFilter<"RunTask"> | number
}

export type RunTaskCreateInput = {
  id: string
  createdAt?: Date | string
  updatedAt?: Date | string
  repoRef?: string
  roleHint?: string
  title: string
  status: string
  dependsOn?: Prisma.RunTaskCreatedependsOnInput | string[]
  scope?: string
  priority?: number
  run: Prisma.TaskRunCreateNestedOneWithoutTasksInput
}

export type RunTaskUncheckedCreateInput = {
  id: string
  createdAt?: Date | string
  updatedAt?: Date | string
  runId: string
  repoRef?: string
  roleHint?: string
  title: string
  status: string
  dependsOn?: Prisma.RunTaskCreatedependsOnInput | string[]
  scope?: string
  priority?: number
}

export type RunTaskUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  repoRef?: Prisma.StringFieldUpdateOperationsInput | string
  roleHint?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  dependsOn?: Prisma.RunTaskUpdatedependsOnInput | string[]
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  run?: Prisma.TaskRunUpdateOneRequiredWithoutTasksNestedInput
}

export type RunTaskUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  runId?: Prisma.StringFieldUpdateOperationsInput | string
  repoRef?: Prisma.StringFieldUpdateOperationsInput | string
  roleHint?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  dependsOn?: Prisma.RunTaskUpdatedependsOnInput | string[]
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
}

export type RunTaskCreateManyInput = {
  id: string
  createdAt?: Date | string
  updatedAt?: Date | string
  runId: string
  repoRef?: string
  roleHint?: string
  title: string
  status: string
  dependsOn?: Prisma.RunTaskCreatedependsOnInput | string[]
  scope?: string
  priority?: number
}

export type RunTaskUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  repoRef?: Prisma.StringFieldUpdateOperationsInput | string
  roleHint?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  dependsOn?: Prisma.RunTaskUpdatedependsOnInput | string[]
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
}

export type RunTaskUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  runId?: Prisma.StringFieldUpdateOperationsInput | string
  repoRef?: Prisma.StringFieldUpdateOperationsInput | string
  roleHint?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  dependsOn?: Prisma.RunTaskUpdatedependsOnInput | string[]
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
}

export type RunTaskListRelationFilter = {
  every?: Prisma.RunTaskWhereInput
  some?: Prisma.RunTaskWhereInput
  none?: Prisma.RunTaskWhereInput
}

export type RunTaskOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RunTaskOrderByRelevanceInput = {
  fields: Prisma.RunTaskOrderByRelevanceFieldEnum | Prisma.RunTaskOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type RunTaskCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  runId?: Prisma.SortOrder
  repoRef?: Prisma.SortOrder
  roleHint?: Prisma.SortOrder
  title?: Prisma.SortOrder
  status?: Prisma.SortOrder
  dependsOn?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  priority?: Prisma.SortOrder
}

export type RunTaskAvgOrderByAggregateInput = {
  priority?: Prisma.SortOrder
}

export type RunTaskMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  runId?: Prisma.SortOrder
  repoRef?: Prisma.SortOrder
  roleHint?: Prisma.SortOrder
  title?: Prisma.SortOrder
  status?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  priority?: Prisma.SortOrder
}

export type RunTaskMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  runId?: Prisma.SortOrder
  repoRef?: Prisma.SortOrder
  roleHint?: Prisma.SortOrder
  title?: Prisma.SortOrder
  status?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  priority?: Prisma.SortOrder
}

export type RunTaskSumOrderByAggregateInput = {
  priority?: Prisma.SortOrder
}

export type RunTaskCreateNestedManyWithoutRunInput = {
  create?: Prisma.XOR<Prisma.RunTaskCreateWithoutRunInput, Prisma.RunTaskUncheckedCreateWithoutRunInput> | Prisma.RunTaskCreateWithoutRunInput[] | Prisma.RunTaskUncheckedCreateWithoutRunInput[]
  connectOrCreate?: Prisma.RunTaskCreateOrConnectWithoutRunInput | Prisma.RunTaskCreateOrConnectWithoutRunInput[]
  createMany?: Prisma.RunTaskCreateManyRunInputEnvelope
  connect?: Prisma.RunTaskWhereUniqueInput | Prisma.RunTaskWhereUniqueInput[]
}

export type RunTaskUncheckedCreateNestedManyWithoutRunInput = {
  create?: Prisma.XOR<Prisma.RunTaskCreateWithoutRunInput, Prisma.RunTaskUncheckedCreateWithoutRunInput> | Prisma.RunTaskCreateWithoutRunInput[] | Prisma.RunTaskUncheckedCreateWithoutRunInput[]
  connectOrCreate?: Prisma.RunTaskCreateOrConnectWithoutRunInput | Prisma.RunTaskCreateOrConnectWithoutRunInput[]
  createMany?: Prisma.RunTaskCreateManyRunInputEnvelope
  connect?: Prisma.RunTaskWhereUniqueInput | Prisma.RunTaskWhereUniqueInput[]
}

export type RunTaskUpdateManyWithoutRunNestedInput = {
  create?: Prisma.XOR<Prisma.RunTaskCreateWithoutRunInput, Prisma.RunTaskUncheckedCreateWithoutRunInput> | Prisma.RunTaskCreateWithoutRunInput[] | Prisma.RunTaskUncheckedCreateWithoutRunInput[]
  connectOrCreate?: Prisma.RunTaskCreateOrConnectWithoutRunInput | Prisma.RunTaskCreateOrConnectWithoutRunInput[]
  upsert?: Prisma.RunTaskUpsertWithWhereUniqueWithoutRunInput | Prisma.RunTaskUpsertWithWhereUniqueWithoutRunInput[]
  createMany?: Prisma.RunTaskCreateManyRunInputEnvelope
  set?: Prisma.RunTaskWhereUniqueInput | Prisma.RunTaskWhereUniqueInput[]
  disconnect?: Prisma.RunTaskWhereUniqueInput | Prisma.RunTaskWhereUniqueInput[]
  delete?: Prisma.RunTaskWhereUniqueInput | Prisma.RunTaskWhereUniqueInput[]
  connect?: Prisma.RunTaskWhereUniqueInput | Prisma.RunTaskWhereUniqueInput[]
  update?: Prisma.RunTaskUpdateWithWhereUniqueWithoutRunInput | Prisma.RunTaskUpdateWithWhereUniqueWithoutRunInput[]
  updateMany?: Prisma.RunTaskUpdateManyWithWhereWithoutRunInput | Prisma.RunTaskUpdateManyWithWhereWithoutRunInput[]
  deleteMany?: Prisma.RunTaskScalarWhereInput | Prisma.RunTaskScalarWhereInput[]
}

export type RunTaskUncheckedUpdateManyWithoutRunNestedInput = {
  create?: Prisma.XOR<Prisma.RunTaskCreateWithoutRunInput, Prisma.RunTaskUncheckedCreateWithoutRunInput> | Prisma.RunTaskCreateWithoutRunInput[] | Prisma.RunTaskUncheckedCreateWithoutRunInput[]
  connectOrCreate?: Prisma.RunTaskCreateOrConnectWithoutRunInput | Prisma.RunTaskCreateOrConnectWithoutRunInput[]
  upsert?: Prisma.RunTaskUpsertWithWhereUniqueWithoutRunInput | Prisma.RunTaskUpsertWithWhereUniqueWithoutRunInput[]
  createMany?: Prisma.RunTaskCreateManyRunInputEnvelope
  set?: Prisma.RunTaskWhereUniqueInput | Prisma.RunTaskWhereUniqueInput[]
  disconnect?: Prisma.RunTaskWhereUniqueInput | Prisma.RunTaskWhereUniqueInput[]
  delete?: Prisma.RunTaskWhereUniqueInput | Prisma.RunTaskWhereUniqueInput[]
  connect?: Prisma.RunTaskWhereUniqueInput | Prisma.RunTaskWhereUniqueInput[]
  update?: Prisma.RunTaskUpdateWithWhereUniqueWithoutRunInput | Prisma.RunTaskUpdateWithWhereUniqueWithoutRunInput[]
  updateMany?: Prisma.RunTaskUpdateManyWithWhereWithoutRunInput | Prisma.RunTaskUpdateManyWithWhereWithoutRunInput[]
  deleteMany?: Prisma.RunTaskScalarWhereInput | Prisma.RunTaskScalarWhereInput[]
}

export type RunTaskCreatedependsOnInput = {
  set: string[]
}

export type RunTaskUpdatedependsOnInput = {
  set?: string[]
  push?: string | string[]
}

export type RunTaskCreateWithoutRunInput = {
  id: string
  createdAt?: Date | string
  updatedAt?: Date | string
  repoRef?: string
  roleHint?: string
  title: string
  status: string
  dependsOn?: Prisma.RunTaskCreatedependsOnInput | string[]
  scope?: string
  priority?: number
}

export type RunTaskUncheckedCreateWithoutRunInput = {
  id: string
  createdAt?: Date | string
  updatedAt?: Date | string
  repoRef?: string
  roleHint?: string
  title: string
  status: string
  dependsOn?: Prisma.RunTaskCreatedependsOnInput | string[]
  scope?: string
  priority?: number
}

export type RunTaskCreateOrConnectWithoutRunInput = {
  where: Prisma.RunTaskWhereUniqueInput
  create: Prisma.XOR<Prisma.RunTaskCreateWithoutRunInput, Prisma.RunTaskUncheckedCreateWithoutRunInput>
}

export type RunTaskCreateManyRunInputEnvelope = {
  data: Prisma.RunTaskCreateManyRunInput | Prisma.RunTaskCreateManyRunInput[]
  skipDuplicates?: boolean
}

export type RunTaskUpsertWithWhereUniqueWithoutRunInput = {
  where: Prisma.RunTaskWhereUniqueInput
  update: Prisma.XOR<Prisma.RunTaskUpdateWithoutRunInput, Prisma.RunTaskUncheckedUpdateWithoutRunInput>
  create: Prisma.XOR<Prisma.RunTaskCreateWithoutRunInput, Prisma.RunTaskUncheckedCreateWithoutRunInput>
}

export type RunTaskUpdateWithWhereUniqueWithoutRunInput = {
  where: Prisma.RunTaskWhereUniqueInput
  data: Prisma.XOR<Prisma.RunTaskUpdateWithoutRunInput, Prisma.RunTaskUncheckedUpdateWithoutRunInput>
}

export type RunTaskUpdateManyWithWhereWithoutRunInput = {
  where: Prisma.RunTaskScalarWhereInput
  data: Prisma.XOR<Prisma.RunTaskUpdateManyMutationInput, Prisma.RunTaskUncheckedUpdateManyWithoutRunInput>
}

export type RunTaskScalarWhereInput = {
  AND?: Prisma.RunTaskScalarWhereInput | Prisma.RunTaskScalarWhereInput[]
  OR?: Prisma.RunTaskScalarWhereInput[]
  NOT?: Prisma.RunTaskScalarWhereInput | Prisma.RunTaskScalarWhereInput[]
  id?: Prisma.StringFilter<"RunTask"> | string
  createdAt?: Prisma.DateTimeFilter<"RunTask"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RunTask"> | Date | string
  runId?: Prisma.StringFilter<"RunTask"> | string
  repoRef?: Prisma.StringFilter<"RunTask"> | string
  roleHint?: Prisma.StringFilter<"RunTask"> | string
  title?: Prisma.StringFilter<"RunTask"> | string
  status?: Prisma.StringFilter<"RunTask"> | string
  dependsOn?: Prisma.StringNullableListFilter<"RunTask">
  scope?: Prisma.StringFilter<"RunTask"> | string
  priority?: Prisma.IntFilter<"RunTask"> | number
}

export type RunTaskCreateManyRunInput = {
  id: string
  createdAt?: Date | string
  updatedAt?: Date | string
  repoRef?: string
  roleHint?: string
  title: string
  status: string
  dependsOn?: Prisma.RunTaskCreatedependsOnInput | string[]
  scope?: string
  priority?: number
}

export type RunTaskUpdateWithoutRunInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  repoRef?: Prisma.StringFieldUpdateOperationsInput | string
  roleHint?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  dependsOn?: Prisma.RunTaskUpdatedependsOnInput | string[]
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
}

export type RunTaskUncheckedUpdateWithoutRunInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  repoRef?: Prisma.StringFieldUpdateOperationsInput | string
  roleHint?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  dependsOn?: Prisma.RunTaskUpdatedependsOnInput | string[]
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
}

export type RunTaskUncheckedUpdateManyWithoutRunInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  repoRef?: Prisma.StringFieldUpdateOperationsInput | string
  roleHint?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  dependsOn?: Prisma.RunTaskUpdatedependsOnInput | string[]
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
}



export type RunTaskSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  runId?: boolean
  repoRef?: boolean
  roleHint?: boolean
  title?: boolean
  status?: boolean
  dependsOn?: boolean
  scope?: boolean
  priority?: boolean
  run?: boolean | Prisma.TaskRunDefaultArgs<ExtArgs>
}, ExtArgs["result"]["runTask"]>

export type RunTaskSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  runId?: boolean
  repoRef?: boolean
  roleHint?: boolean
  title?: boolean
  status?: boolean
  dependsOn?: boolean
  scope?: boolean
  priority?: boolean
  run?: boolean | Prisma.TaskRunDefaultArgs<ExtArgs>
}, ExtArgs["result"]["runTask"]>

export type RunTaskSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  runId?: boolean
  repoRef?: boolean
  roleHint?: boolean
  title?: boolean
  status?: boolean
  dependsOn?: boolean
  scope?: boolean
  priority?: boolean
  run?: boolean | Prisma.TaskRunDefaultArgs<ExtArgs>
}, ExtArgs["result"]["runTask"]>

export type RunTaskSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  runId?: boolean
  repoRef?: boolean
  roleHint?: boolean
  title?: boolean
  status?: boolean
  dependsOn?: boolean
  scope?: boolean
  priority?: boolean
}

export type RunTaskOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "runId" | "repoRef" | "roleHint" | "title" | "status" | "dependsOn" | "scope" | "priority", ExtArgs["result"]["runTask"]>
export type RunTaskInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  run?: boolean | Prisma.TaskRunDefaultArgs<ExtArgs>
}
export type RunTaskIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  run?: boolean | Prisma.TaskRunDefaultArgs<ExtArgs>
}
export type RunTaskIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  run?: boolean | Prisma.TaskRunDefaultArgs<ExtArgs>
}

export type $RunTaskPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RunTask"
  objects: {
    run: Prisma.$TaskRunPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    runId: string
    repoRef: string
    roleHint: string
    title: string
    status: string
    dependsOn: string[]
    scope: string
    priority: number
  }, ExtArgs["result"]["runTask"]>
  composites: {}
}

export type RunTaskGetPayload<S extends boolean | null | undefined | RunTaskDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RunTaskPayload, S>

export type RunTaskCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RunTaskFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RunTaskCountAggregateInputType | true
  }

export interface RunTaskDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RunTask'], meta: { name: 'RunTask' } }
  /**
   * Find zero or one RunTask that matches the filter.
   * @param {RunTaskFindUniqueArgs} args - Arguments to find a RunTask
   * @example
   * // Get one RunTask
   * const runTask = await prisma.runTask.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RunTaskFindUniqueArgs>(args: Prisma.SelectSubset<T, RunTaskFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RunTaskClient<runtime.Types.Result.GetResult<Prisma.$RunTaskPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RunTask that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RunTaskFindUniqueOrThrowArgs} args - Arguments to find a RunTask
   * @example
   * // Get one RunTask
   * const runTask = await prisma.runTask.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RunTaskFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RunTaskFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RunTaskClient<runtime.Types.Result.GetResult<Prisma.$RunTaskPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RunTask that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RunTaskFindFirstArgs} args - Arguments to find a RunTask
   * @example
   * // Get one RunTask
   * const runTask = await prisma.runTask.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RunTaskFindFirstArgs>(args?: Prisma.SelectSubset<T, RunTaskFindFirstArgs<ExtArgs>>): Prisma.Prisma__RunTaskClient<runtime.Types.Result.GetResult<Prisma.$RunTaskPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RunTask that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RunTaskFindFirstOrThrowArgs} args - Arguments to find a RunTask
   * @example
   * // Get one RunTask
   * const runTask = await prisma.runTask.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RunTaskFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RunTaskFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RunTaskClient<runtime.Types.Result.GetResult<Prisma.$RunTaskPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RunTasks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RunTaskFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RunTasks
   * const runTasks = await prisma.runTask.findMany()
   * 
   * // Get first 10 RunTasks
   * const runTasks = await prisma.runTask.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const runTaskWithIdOnly = await prisma.runTask.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RunTaskFindManyArgs>(args?: Prisma.SelectSubset<T, RunTaskFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RunTaskPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RunTask.
   * @param {RunTaskCreateArgs} args - Arguments to create a RunTask.
   * @example
   * // Create one RunTask
   * const RunTask = await prisma.runTask.create({
   *   data: {
   *     // ... data to create a RunTask
   *   }
   * })
   * 
   */
  create<T extends RunTaskCreateArgs>(args: Prisma.SelectSubset<T, RunTaskCreateArgs<ExtArgs>>): Prisma.Prisma__RunTaskClient<runtime.Types.Result.GetResult<Prisma.$RunTaskPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RunTasks.
   * @param {RunTaskCreateManyArgs} args - Arguments to create many RunTasks.
   * @example
   * // Create many RunTasks
   * const runTask = await prisma.runTask.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RunTaskCreateManyArgs>(args?: Prisma.SelectSubset<T, RunTaskCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RunTasks and returns the data saved in the database.
   * @param {RunTaskCreateManyAndReturnArgs} args - Arguments to create many RunTasks.
   * @example
   * // Create many RunTasks
   * const runTask = await prisma.runTask.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RunTasks and only return the `id`
   * const runTaskWithIdOnly = await prisma.runTask.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RunTaskCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RunTaskCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RunTaskPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RunTask.
   * @param {RunTaskDeleteArgs} args - Arguments to delete one RunTask.
   * @example
   * // Delete one RunTask
   * const RunTask = await prisma.runTask.delete({
   *   where: {
   *     // ... filter to delete one RunTask
   *   }
   * })
   * 
   */
  delete<T extends RunTaskDeleteArgs>(args: Prisma.SelectSubset<T, RunTaskDeleteArgs<ExtArgs>>): Prisma.Prisma__RunTaskClient<runtime.Types.Result.GetResult<Prisma.$RunTaskPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RunTask.
   * @param {RunTaskUpdateArgs} args - Arguments to update one RunTask.
   * @example
   * // Update one RunTask
   * const runTask = await prisma.runTask.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RunTaskUpdateArgs>(args: Prisma.SelectSubset<T, RunTaskUpdateArgs<ExtArgs>>): Prisma.Prisma__RunTaskClient<runtime.Types.Result.GetResult<Prisma.$RunTaskPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RunTasks.
   * @param {RunTaskDeleteManyArgs} args - Arguments to filter RunTasks to delete.
   * @example
   * // Delete a few RunTasks
   * const { count } = await prisma.runTask.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RunTaskDeleteManyArgs>(args?: Prisma.SelectSubset<T, RunTaskDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RunTasks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RunTaskUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RunTasks
   * const runTask = await prisma.runTask.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RunTaskUpdateManyArgs>(args: Prisma.SelectSubset<T, RunTaskUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RunTasks and returns the data updated in the database.
   * @param {RunTaskUpdateManyAndReturnArgs} args - Arguments to update many RunTasks.
   * @example
   * // Update many RunTasks
   * const runTask = await prisma.runTask.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RunTasks and only return the `id`
   * const runTaskWithIdOnly = await prisma.runTask.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RunTaskUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RunTaskUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RunTaskPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RunTask.
   * @param {RunTaskUpsertArgs} args - Arguments to update or create a RunTask.
   * @example
   * // Update or create a RunTask
   * const runTask = await prisma.runTask.upsert({
   *   create: {
   *     // ... data to create a RunTask
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RunTask we want to update
   *   }
   * })
   */
  upsert<T extends RunTaskUpsertArgs>(args: Prisma.SelectSubset<T, RunTaskUpsertArgs<ExtArgs>>): Prisma.Prisma__RunTaskClient<runtime.Types.Result.GetResult<Prisma.$RunTaskPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RunTasks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RunTaskCountArgs} args - Arguments to filter RunTasks to count.
   * @example
   * // Count the number of RunTasks
   * const count = await prisma.runTask.count({
   *   where: {
   *     // ... the filter for the RunTasks we want to count
   *   }
   * })
  **/
  count<T extends RunTaskCountArgs>(
    args?: Prisma.Subset<T, RunTaskCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RunTaskCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RunTask.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RunTaskAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RunTaskAggregateArgs>(args: Prisma.Subset<T, RunTaskAggregateArgs>): Prisma.PrismaPromise<GetRunTaskAggregateType<T>>

  /**
   * Group by RunTask.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RunTaskGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RunTaskGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RunTaskGroupByArgs['orderBy'] }
      : { orderBy?: RunTaskGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RunTaskGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRunTaskGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RunTask model
 */
readonly fields: RunTaskFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RunTask.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RunTaskClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  run<T extends Prisma.TaskRunDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TaskRunDefaultArgs<ExtArgs>>): Prisma.Prisma__TaskRunClient<runtime.Types.Result.GetResult<Prisma.$TaskRunPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RunTask model
 */
export interface RunTaskFieldRefs {
  readonly id: Prisma.FieldRef<"RunTask", 'String'>
  readonly createdAt: Prisma.FieldRef<"RunTask", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"RunTask", 'DateTime'>
  readonly runId: Prisma.FieldRef<"RunTask", 'String'>
  readonly repoRef: Prisma.FieldRef<"RunTask", 'String'>
  readonly roleHint: Prisma.FieldRef<"RunTask", 'String'>
  readonly title: Prisma.FieldRef<"RunTask", 'String'>
  readonly status: Prisma.FieldRef<"RunTask", 'String'>
  readonly dependsOn: Prisma.FieldRef<"RunTask", 'String[]'>
  readonly scope: Prisma.FieldRef<"RunTask", 'String'>
  readonly priority: Prisma.FieldRef<"RunTask", 'Int'>
}
    

// Custom InputTypes
/**
 * RunTask findUnique
 */
export type RunTaskFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RunTask
   */
  select?: Prisma.RunTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RunTask
   */
  omit?: Prisma.RunTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunTaskInclude<ExtArgs> | null
  /**
   * Filter, which RunTask to fetch.
   */
  where: Prisma.RunTaskWhereUniqueInput
}

/**
 * RunTask findUniqueOrThrow
 */
export type RunTaskFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RunTask
   */
  select?: Prisma.RunTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RunTask
   */
  omit?: Prisma.RunTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunTaskInclude<ExtArgs> | null
  /**
   * Filter, which RunTask to fetch.
   */
  where: Prisma.RunTaskWhereUniqueInput
}

/**
 * RunTask findFirst
 */
export type RunTaskFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RunTask
   */
  select?: Prisma.RunTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RunTask
   */
  omit?: Prisma.RunTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunTaskInclude<ExtArgs> | null
  /**
   * Filter, which RunTask to fetch.
   */
  where?: Prisma.RunTaskWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RunTasks to fetch.
   */
  orderBy?: Prisma.RunTaskOrderByWithRelationInput | Prisma.RunTaskOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RunTasks.
   */
  cursor?: Prisma.RunTaskWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RunTasks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RunTasks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RunTasks.
   */
  distinct?: Prisma.RunTaskScalarFieldEnum | Prisma.RunTaskScalarFieldEnum[]
}

/**
 * RunTask findFirstOrThrow
 */
export type RunTaskFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RunTask
   */
  select?: Prisma.RunTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RunTask
   */
  omit?: Prisma.RunTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunTaskInclude<ExtArgs> | null
  /**
   * Filter, which RunTask to fetch.
   */
  where?: Prisma.RunTaskWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RunTasks to fetch.
   */
  orderBy?: Prisma.RunTaskOrderByWithRelationInput | Prisma.RunTaskOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RunTasks.
   */
  cursor?: Prisma.RunTaskWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RunTasks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RunTasks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RunTasks.
   */
  distinct?: Prisma.RunTaskScalarFieldEnum | Prisma.RunTaskScalarFieldEnum[]
}

/**
 * RunTask findMany
 */
export type RunTaskFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RunTask
   */
  select?: Prisma.RunTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RunTask
   */
  omit?: Prisma.RunTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunTaskInclude<ExtArgs> | null
  /**
   * Filter, which RunTasks to fetch.
   */
  where?: Prisma.RunTaskWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RunTasks to fetch.
   */
  orderBy?: Prisma.RunTaskOrderByWithRelationInput | Prisma.RunTaskOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RunTasks.
   */
  cursor?: Prisma.RunTaskWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RunTasks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RunTasks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RunTasks.
   */
  distinct?: Prisma.RunTaskScalarFieldEnum | Prisma.RunTaskScalarFieldEnum[]
}

/**
 * RunTask create
 */
export type RunTaskCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RunTask
   */
  select?: Prisma.RunTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RunTask
   */
  omit?: Prisma.RunTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunTaskInclude<ExtArgs> | null
  /**
   * The data needed to create a RunTask.
   */
  data: Prisma.XOR<Prisma.RunTaskCreateInput, Prisma.RunTaskUncheckedCreateInput>
}

/**
 * RunTask createMany
 */
export type RunTaskCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RunTasks.
   */
  data: Prisma.RunTaskCreateManyInput | Prisma.RunTaskCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RunTask createManyAndReturn
 */
export type RunTaskCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RunTask
   */
  select?: Prisma.RunTaskSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RunTask
   */
  omit?: Prisma.RunTaskOmit<ExtArgs> | null
  /**
   * The data used to create many RunTasks.
   */
  data: Prisma.RunTaskCreateManyInput | Prisma.RunTaskCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunTaskIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RunTask update
 */
export type RunTaskUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RunTask
   */
  select?: Prisma.RunTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RunTask
   */
  omit?: Prisma.RunTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunTaskInclude<ExtArgs> | null
  /**
   * The data needed to update a RunTask.
   */
  data: Prisma.XOR<Prisma.RunTaskUpdateInput, Prisma.RunTaskUncheckedUpdateInput>
  /**
   * Choose, which RunTask to update.
   */
  where: Prisma.RunTaskWhereUniqueInput
}

/**
 * RunTask updateMany
 */
export type RunTaskUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RunTasks.
   */
  data: Prisma.XOR<Prisma.RunTaskUpdateManyMutationInput, Prisma.RunTaskUncheckedUpdateManyInput>
  /**
   * Filter which RunTasks to update
   */
  where?: Prisma.RunTaskWhereInput
  /**
   * Limit how many RunTasks to update.
   */
  limit?: number
}

/**
 * RunTask updateManyAndReturn
 */
export type RunTaskUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RunTask
   */
  select?: Prisma.RunTaskSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RunTask
   */
  omit?: Prisma.RunTaskOmit<ExtArgs> | null
  /**
   * The data used to update RunTasks.
   */
  data: Prisma.XOR<Prisma.RunTaskUpdateManyMutationInput, Prisma.RunTaskUncheckedUpdateManyInput>
  /**
   * Filter which RunTasks to update
   */
  where?: Prisma.RunTaskWhereInput
  /**
   * Limit how many RunTasks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunTaskIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RunTask upsert
 */
export type RunTaskUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RunTask
   */
  select?: Prisma.RunTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RunTask
   */
  omit?: Prisma.RunTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunTaskInclude<ExtArgs> | null
  /**
   * The filter to search for the RunTask to update in case it exists.
   */
  where: Prisma.RunTaskWhereUniqueInput
  /**
   * In case the RunTask found by the `where` argument doesn't exist, create a new RunTask with this data.
   */
  create: Prisma.XOR<Prisma.RunTaskCreateInput, Prisma.RunTaskUncheckedCreateInput>
  /**
   * In case the RunTask was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RunTaskUpdateInput, Prisma.RunTaskUncheckedUpdateInput>
}

/**
 * RunTask delete
 */
export type RunTaskDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RunTask
   */
  select?: Prisma.RunTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RunTask
   */
  omit?: Prisma.RunTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunTaskInclude<ExtArgs> | null
  /**
   * Filter which RunTask to delete.
   */
  where: Prisma.RunTaskWhereUniqueInput
}

/**
 * RunTask deleteMany
 */
export type RunTaskDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RunTasks to delete
   */
  where?: Prisma.RunTaskWhereInput
  /**
   * Limit how many RunTasks to delete.
   */
  limit?: number
}

/**
 * RunTask without action
 */
export type RunTaskDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RunTask
   */
  select?: Prisma.RunTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RunTask
   */
  omit?: Prisma.RunTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RunTaskInclude<ExtArgs> | null
}
